### ISSUE TITLE
Zsh Widget on macOS

### ISSUE THREAD

**Issue by NeoNeuron** [denisidoro/navi#104]
I'm working on my macOS terminal. And I can not activate `navi` widget on zsh with `alt+g` hotkey. 
I'm not sure whether it has something to do with the `alt` key on Apple keyboard layout. Can I change the default activation hotkey?

**Comment by denisidoro** [comment]
I'm on OSX as well. Did you follow the instructions for sourcing the widget in `.zshrc`?
Did you try `option+g` or `cmd+g`?

In any case, [this is the line](https://github.com/denisidoro/navi/blob/0c960fca545dbc48b7c2d7ba094dfb5fb2f85f3a/shell/widget.zsh#L11) where you can change the keybinding. [This is an article](https://dev.to/ecologic/using-keyboard-shortcuts-with-zsh-16b) showcasing different keybindings.

**Comment by denisidoro** [comment]
https://github.com/denisidoro/navi/pull/105 changes the default keybinding to `Ctrl-G`, so even if this bugs with `Alt` exists, it should be fixed.
