### ISSUE TITLE
Unable to find command for '<anything>'

### ISSUE THREAD

**Issue by tuping** [denisidoro/navi#111]
When I call navi from command line I always get "Unable to find command for '...".
It seems like navi is ignoring the first character under selected item. Refer to image, please.

![navi](https://user-images.githubusercontent.com/128622/66165270-c757eb00-e60a-11e9-859c-452182fa2f08.png)

I have just cloned the repo and tried whith the *navi* executable.

```bash
git clone git@github.com:denisidoro/navi.git
cd navi
./navi
```
![navi](https://user-images.githubusercontent.com/128622/66165912-2ff39780-e60c-11e9-86e2-bdcd969a7536.gif)

**Comment by denisidoro** [comment]
What OS are you using?

**Comment by denisidoro** [comment]
I'm not able to reproduce the error on OSX nor on an alpine docker container 😞

**Comment by denisidoro** [comment]
Could you check if the following works?
```
cd "$(navi home)"
git pull
git checkout workaround/111
./navi
```

It's hacky, though.

**Comment by denisidoro** [comment]
And could you check the following?
```sh
cd "$(navi home)"
./test/run
```

This way, I can (hopefully) know exactly where the error is occurring.

**Comment by denisidoro** [comment]
Are you using termux on Android? I got the same error

**Comment by denisidoro** [comment]
I already know the fix. I'll release a new version next Monday
