### ISSUE TITLE
Support skim?

### ISSUE THREAD

**Issue by jedahan** [denisidoro/navi#115]
I've been using [skim](https://github.com/lotabout/skim) for a while now, and if I change the commands from `fzf` to `sk`, it invokes fine, but interactive searching doesn't work so well. I'm sure there are some differences between `-i` in both tools, but do not know how to move forward.

**Comment by denisidoro** [comment]
I've never used skim, but it should be straightforward to support it: one just needs to create a "bridge" in [ui::fzf](https://github.com/denisidoro/navi/blob/master/src/ui.sh#L3), translating fzf arguments to skim arguments.

If you're willing to start the work, I can finish it 👍

**Comment by denisidoro** [comment]
I've debugged a little bit and it seems that `skim` doesn't play nice with all arguments from `fzf`. 

The command for `preview` is a little bit different, for instance; `--select-1` won't work; and so on. 

That said, the solution to support remains the same, but it's not as trivial as I imagined (we would need to create custom code to simulate `--select-1` for example.

**Comment by denisidoro** [comment]
Closing because I don't plan to focus on this at the moment. Future readers: feel free to reopen this issue or open a PR! 👍
