### ISSUE TITLE
how to use in linux?

### ISSUE THREAD

**Issue by chaijian2019** [denisidoro/navi#118]
anyone who can tell me how to use it in centos7 ? i can not install it in linux ,it did not work

**Comment by denisidoro** [comment]
doesn't this work?
```
git clone --depth 1 https://github.com/denisidoro/navi /opt/navi
cd /opt/navi
./navi
```

**Comment by denisidoro** [comment]
and here is a [step by step guide](https://www.katacoda.com/denisidoro/scenarios/navi)

**Comment by chaijian2019** [comment]
> doesn't this work?
> 
> ```
> git clone --depth 1 https://github.com/denisidoro/navi /opt/navi
> cd /opt/navi
> ./navi
> ```
 Tks for your reply.，it has been solved now. The reason is that i am not the root account and FZF mirror download speed is too slow.
