### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by IvanVas** [denisidoro/navi#119]
Is there a chance the license to be changed?
Some big tech companies have AGPL-3 blacklisted.

**Comment by denisidoro** [comment]
Do you suggest any other license?
And why do some big tech companies blacklist AGPL-3? 🤔 
(I'm not an expert on licensing 😞)

**Comment by IvanVas** [comment]
This copy-left license is vague enough to create a potential risk for them.

Those would work:
https://opensource.org/licenses/GPL-2.0
https://opensource.org/licenses/bsd-license.php
https://opensource.org/licenses/apache2.0.php

Thanks.

**Comment by denisidoro** [comment]
Thanks for the reply, @IvanVas!

However, even though I'd like to maximize the reach of this tool, I don't want to make this decision without thinking about it thoroughly.

For those out there reading this: if you think this is a problem in your company as well, please upvote the issue so that I can have a better understanding of the problem!

**Comment by designMoreWeb** [comment]
I agree I feel that the copy-left license is vague

**Comment by IvanVas** [comment]
> Thanks for the reply, @IvanVas!
> 
> However, even though I'd like to maximize the reach of this tool, I don't want to make this decision without thinking about it thoroughly.
> 
> For those out there reading this: if you think this is a problem in your company as well, please upvote the issue so that I can have a better understanding of the problem!

Thanks for looking into this. I wouldn't expect lots of upvotes, though. Most of those who can't use the tool will just close the tab after seeing checking the license. Survivor bias in reverse.

**Comment by denisidoro** [comment]
I'll read more about it and hopefully by next week have a decision already.

**Comment by denisidoro** [comment]
Another question: from a legal standpoint, can I change the license as I wish?

I mean, if I said that the project is licensed under AGPL3, could I turn it into shareware, for example? (not saying that I would do that. It's just a thought experiment considering the end of the spectrum)

**Comment by IvanVas** [comment]
AFAIU, you can distribute the newer version with the new license. Not sure, though.

**Comment by denisidoro** [comment]
I plan to change to Apache 2.0 for the next release
