### ISSUE TITLE
Variable suggestion window does not show when upgrade navi from v0.11.1 to v0.12.0

### ISSUE THREAD

**Issue by lpy-neo** [denisidoro/navi#125]
Reproduce steps:
1. input `git checkout`
2. press Enter key
3. Got following error: 
     Unable to fetch suggestions for 'branch'!

Environment:
 mac
 iterm2
 zsh
 fzf: 0.17.1 (brew)

**Comment by denisidoro** [comment]
Thanks for the report! I'll look into it tomorrow

**Comment by denisidoro** [comment]
In the meantime, could you try running the (unreleased) version from master? You'll need to manually git clone.

Maybe the problem is already solved.

**Comment by lpy-neo** [comment]
> In the meantime, could you try running the (unreleased) version from master? You'll need to manually git clone.
> 
> Maybe the problem is already solved.

I've tried the master branch, but the problem still exists.

**Comment by denisidoro** [comment]
Strange... I'm not able to reproduce the problem :(

Does the variable suggestion fail to all variables or just for `<branch<`?

**Comment by lpy-neo** [comment]
https://github.com/denisidoro/navi/blob/76e216b24ae10a575a9dc03dbe0b8bfbd1d3089e/src/ui.sh#L14
I found I can fix this problem by changing the above code to:
"$fzf_cmd" ${args[@]:-} --inline-info "$@"

I guess the reason why you can't reproduce is because your shell is not zsh.

**Comment by denisidoro** [comment]
I use zsh as well but actually that makes no difference. When the script is invoked, it's executed with bash.

What's your bash version?

I can open a PR if you want (or you can open yourself so that you'll be a contributor to the project)

**Comment by lpy-neo** [comment]
The version info of the bash I use:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

After some experiments, I found the bash version may not be the cause. However, I guess it's the Gnu Readline library which is a dependency of bash.

I'll be happy to open a PR~

**Comment by undeflife** [comment]
this issue still persists
``` 
$ brew info navi                                                                                                                                
navi: stable 0.15.2 (bottled)
Interactive cheatsheet tool for the command-line
https://github.com/denisidoro/navi
/usr/local/Cellar/navi/0.15.2 (62 files, 82.9KB) *
  Built from source on 2019-11-15 at 16:15:22
```

Environment:
macOS 10.15.1
iterm2
zsh 5.7.1 (x86_64-apple-darwin19.0)
fzf: stable 0.18.0 (bottled), HEAD
