### ISSUE TITLE
fail conda activation

### ISSUE THREAD

**Issue by subaiwen** [denisidoro/navi#134]
When I use `conda activate <env>` in zsh, and type `env: base`. It failed.

1. I already followed the steps in the steps in *Installation using oh-my-zsh* and added `export PATH=$PATH:"$ZSH_CUSTOM/plugins/navi"` in my `~/.zshrc`.

2. I also tried and `conda init zsh`. It doesn't work.

Here are Error commands:
```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

**Comment by denisidoro** [comment]
Could you try running the script as a shell widget? Please refer to the README and use Ctrl+G

Does the error occur as well?

**Comment by subaiwen** [comment]
> Could you try running the script as a shell widget? Please refer to the README and use Ctrl+G
> 
> Does the error occur as well?

Thank you!
If I use `Ctrl+G`, it works perfectly, no error at all. I am just curious why the code cannot be run using `navi`.

**Comment by denisidoro** [comment]
I believe this happens because when you run `navi`, the snippet will be executed inside bash. If you use the widget, it will be executed inside zsh.

Maybe running `conda init bash` will do the trick?
