### ISSUE TITLE
Mixed comments and snippets in search mode

### ISSUE THREAD

**Issue by SamuelDSR** [denisidoro/navi#137]
# Issue Description
## Environment
- System: Ubuntu18.04
- Installation method: linuxbrew

When search a snippet, the comments and commands of all candidate snippet are interleved in a random way. 
Please see snapshot below :)

![image](https://user-images.githubusercontent.com/2304703/67469800-fe8b4c00-f64c-11e9-9dfc-bf0cab251ab8.png)

**Comment by wallace11** [comment]
Yeah I agree too that this is very confusing. We already have the preview window so maybe we can have the list show only desc / only command and the preview show the other one  (should be configurable imho).

**Comment by denisidoro** [comment]
Ah, one important info: there's no way to hide the snippets and search for them, for example. fzf requires it to be visible to be searchable

**Comment by denisidoro** [comment]
One can use the hidden ANSI code to hide some content, but that won't work on most terminal emulators

**Comment by wallace11** [comment]
Yeah, you have a point there
Maybe it's possible to put the command/comment on the same line with muted color next to category.
It's almost certainly going to overflow but fzf auto-calculates that and we have the preview to compensate.

**Comment by denisidoro** [comment]
Yeah, I'm thinking on something like
```
change branch  [git]  git checkout
get logs       [git]  git logs
reset          [git]  git reset
```

**Comment by denisidoro** [comment]
Some quick experiments:

![Capture d’écran 2019-10-24 à 12 17 57](https://user-images.githubusercontent.com/3226564/67500012-6abf7d00-f658-11e9-8f0e-3f1237f2feef.png)
![Capture d’écran 2019-10-24 à 12 17 27](https://user-images.githubusercontent.com/3226564/67500013-6b581380-f658-11e9-81eb-5f4a6330e846.png)
![Capture d’écran 2019-10-24 à 12 16 41](https://user-images.githubusercontent.com/3226564/67500014-6b581380-f658-11e9-8892-3798507636ee.png)

**Comment by denisidoro** [comment]
I believe the width of a given column should be limited otherwise all the other content will become invisible. I'm not sure if we should use magic numbers or make if dependent on the terminal width

**Comment by denisidoro** [comment]
![Capture d’écran 2019-10-24 à 12 29 51](https://user-images.githubusercontent.com/3226564/67501073-03a2c800-f65a-11e9-89b6-bc6b32b8149c.png)

**Comment by denisidoro** [comment]
This way it will become impossible to read the whole comment if it's too big, though

**Comment by denisidoro** [comment]
The preview could always contain 2 lines: one for the comment and another one for the snippet :)

**Comment by denisidoro** [comment]
![Capture d’écran 2019-10-24 à 13 10 32](https://user-images.githubusercontent.com/3226564/67504427-b6c1f000-f65f-11e9-9b73-4ca7f820f69e.png)

**Comment by wallace11** [comment]
Last one looks superb.
If you provided the full echo command I can paste here more examples of how it looks.

**Comment by denisidoro** [comment]
I'm about to open a PR so you can test it using another branch 👍

**Comment by denisidoro** [comment]
@SamuelDSR and @wallace11: could you try the [table/refactor](https://github.com/denisidoro/navi/pull/138) and give your feedback?

**Comment by SamuelDSR** [comment]
> @SamuelDSR and @wallace11: could you try the [table/refactor](https://github.com/denisidoro/navi/pull/138) branch and give your feedback?

The branch [table/refactor](https://github.com/denisidoro/navi/pull/138) works perfectly in search mode under both mac iterm2/ ubuntu bash [tested].  Thanks very much. @denisidoro 

![Capture d’écran 2019-10-28 à 11 25 13](https://user-images.githubusercontent.com/2304703/67671707-c0589a00-f976-11e9-98e3-b566cb1d1805.png)

**Comment by denisidoro** [comment]
Cool! The branch introduces new options to customize which columns are shown and so on. I'll probably merge it this week
