### ISSUE TITLE
How to change install script for different bin folder on Termux

### ISSUE THREAD

**Issue by StephanBeer** [denisidoro/navi#142]
I'm trying to get navi installed on termux via git but the binaries folder is located differently. Doing a pwd gives '/data/data/com.termux/files/usr/bin'. Whats the correct way to change the install script?

#usr/bin/env bash
set -euo pipefail

export NAVI_HOME="$(cd "$(dirname "$0")/.." && pwd)"

script() {
   echo "#!/usr/bin/env bash"
   echo "${NAVI_HOME}/navi" '"$@"'
}

folder="${1:/data/data/com.termux/files/usr/bin}"
bin="${folder}/navi"

script > "$bin"
chmod +x "$bin"

**Comment by denisidoro** [comment]
Could you try the following?

```sh
pkg install unstable-repo
apt install coreutils
pkg install util-linux
pkg install termux-packages
pkg install ncurses-utils
pkg install grep sed
pkg install proot
termux-chroot

cd $HOME
mkdir -p bin || true
git clone --depth 1 https://github.com/denisidoro/navi
cd navi
./scripts/install $HOME/bin/navi
```

**Comment by StephanBeer** [comment]
Most of the packages you listed were already installed. When following your steps and starting the install- script i get this error message:

./scripts/install: line 14: /data/data/com.termux/files/home/bin/navi/navi: No such file or directory

**Comment by StephanBeer** [comment]
./scripts/install $HOME/bin is working but now i got a bin folder with navi* executable inside in my home directory, rather then having it in the /usr/bin folder for having it in PATH. Folder structure is slightly different on termux. From the home dir going into the parent folder one up, you have home directory and usr directory. In the usr directory theres the bin folder with all the executables....

**Comment by denisidoro** [comment]
Then you can run `./scripts/install /data/data/com.termux/files/usr/bin`

**Comment by denisidoro** [comment]
But maybe that requires root. I'm not sure

**Comment by StephanBeer** [comment]
The last one did it and it worked without root ! Now navi is starting globaly when typing navi. My fault was trying to change the path in the script rather than just changing the argument path when starting the script.

**Comment by denisidoro** [comment]
Actually it should make no difference, but I'm glad that worked 👍

**Comment by StephanBeer** [comment]
Thank you for helping me out Denis. Just one more thing : is the install script also copying the fish functions to the right locations ?

**Comment by denisidoro** [comment]
No. Assuming `navi` is available in your `$PATH`, you just need to add `source (navi widget fish)` to your `.fishrc` file
