### ISSUE TITLE
Failed to read /dev/tty

### ISSUE THREAD

**Issue by ZCDu** [denisidoro/navi#146]
Hi. When I want to try the navi using ssh, I get the issue, how to solve it? 
![error](https://user-images.githubusercontent.com/28478805/67999103-dd9ea880-fc95-11e9-94eb-672c24610228.png)

**Comment by denisidoro** [comment]
Does this happen as soon as the script starts up or does it happen when it's about to prompt for input for a variable?

**Comment by ZCDu** [comment]
It happen when I input navi. I use oh-my-zsh to install navi




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Denis Isidoro"<notifications@github.com&gt;; 
发送时间: 2019年11月1日(星期五) 晚上7:39
收件人: "denisidoro/navi"<navi@noreply.github.com&gt;; 
抄送: "终了 散？"<437677825@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [denisidoro/navi] Failed to read /dev/tty (#146)




Does this happen as soon as the script starts up or does it happen when it's about to prompt for input for a variable?

**Comment by denisidoro** [comment]
As this issue has been thoroughly discussed in the fzf repo, I'll close this one, alright?
