### ISSUE TITLE
Hotkey to yank command / snippet to clipboard

### ISSUE THREAD

**Issue by zweicoder** [denisidoro/navi#152]
i have an alias for `navi --print | xclip -sel clip` but just wanted to suggest adding a hotkey like ctrl-y for this

**Comment by denisidoro** [comment]
This is pretty easy to do it. Hopefully by the end of this week I'll release a new version with it :)

**Comment by denisidoro** [comment]
The hardest thing is to generalize clipboard actions (xclip vs pbcopy vs ...)

**Comment by edubxb** [comment]
Would be very nice is if configurable, I personally use [gpaste](https://github.com/Keruspe/GPaste) to manage the clipboard that has a very nice cli.

**Comment by denisidoro** [comment]
Could anyone give a feedback to https://github.com/denisidoro/navi/pull/155?
