### ISSUE TITLE
Select columns, counting from the right

### ISSUE THREAD

**Issue by spoki0** [denisidoro/navi#153]
Due to some outputs being unreliable or with potential for spaces in the value, is it possible to support selection of columns, counting from the right? 

NAME      | VALUE
------------ | -------------
hello         | world
foo bar | baz

As in this example, providing `--- --column 2` would incorrectly fetch "bar" instead of "baz" in the second row.

**Comment by denisidoro** [comment]
Interesting... What if you could pass a separator such as `\s\s+`?

**Comment by denisidoro** [comment]
@spoki0 could you check if https://github.com/denisidoro/navi/pull/156 fixes your issue?
