### ISSUE TITLE
Add autocompletion on cheats.

### ISSUE THREAD

**Issue by thepenguinthatwants** [denisidoro/navi#161]
**Is your feature request related to a problem? Please describe.**
I sometimes create  cheets that has to fill some information such as file path's while I can write it by hand it would be nice to have tab completions.

**Describe the solution you'd like**
Like writing /home/user/Doc <tab> it will fill in Documents instead of  adding multiple lines.

**Comment by thepenguinthatwants** [comment]
If its too hard to implement then possibly input the command into the terminal instead of straight launch it.

**Comment by denisidoro** [comment]
Hi! I can think of 2 solutions:

1) to define the possible outputs for a given variable. Please check the `tar` cheats for reference

2) to use the shell widget and finish writing the command in your shell. Please check the README for instructions

**Comment by denisidoro** [comment]
I'll close this because of inactivity. Feel free to reopen it, though!
