### ISSUE TITLE
How to have navi prompt for files to fill a variable?

### ISSUE THREAD

**Issue by curio77** [denisidoro/navi#170]
What's the correct way to have navi prompt for a file selection?  If I have something like this:

```
some_command <file>

$ file: ls
```

I get a file selection, but if the selected file name happens to contain non-alphanumeric characters, you run into issues:

  1. If the selected file name contains a single quote character (`'`), neither the file name nor the single quote is escaped in the resulting command.  Contrarily, if the file name contains white space, it is put into double quotes.
  2. If the selected file name happens to contain an ampersand (`&`), navi gets stuck in a file selection loop, prompting again and again for a file.  Once a file without an ampersand in its name is selected, the loop ends and the file name inserted into the command is a mish-mash of all the intermittently selected file names.

For the record, using `ls -Q` is no better, and `fzf` cannot be used because then navi gets stuck without prompting.  navi is up-to-date.

Any ideas?

**Comment by denisidoro** [comment]
Hi, thanks for reporting this!

Unfortunately I'll need to rewrite the escaping logic for these cases to work. I'll take a look at this next week

**Comment by denisidoro** [comment]
Hi, @curio77. Sorry for the extremely late response. I was on vacations.

I'm not able to reproduce the problem. Using `fish 3.0.2` on `OSX` I am able to select the values accordingly.

Do you still face this issue in the latest version? I know I'm asking too much, but maybe you could find a minimal docker image that has this problem?

I wonder if there's a system-level config/binary determining this behavior, as you reported two bugs that I'm not able to reproduce.

**Comment by denisidoro** [comment]
https://github.com/denisidoro/navi/issues/171#issuecomment-574355956
