### ISSUE TITLE
I can not install , make: go: Command not found| I solved it

### ISSUE THREAD

**Issue by geekyouth** [denisidoro/navi#172]
![image](https://user-images.githubusercontent.com/12899262/72197174-5b7eed00-3459-11ea-807c-d350404c2a2e.png)

![image](https://user-images.githubusercontent.com/12899262/72197175-6043a100-3459-11ea-9052-abc17f650353.png)

![image](https://user-images.githubusercontent.com/12899262/72197176-633e9180-3459-11ea-9549-d61b4641612f.png)

# The experience is terrible

**Comment by geekyouth** [comment]
```bash
cat /etc/issue
# CentOS release 6.9 (Final)

cd 
git clone https://github.com/junegunn/fzf ./fzf
cd fzf; ll 
sh install
source ~/.bashrc

git clone --depth 1 https://github.com/denisidoro/navi navi
cd navi 
sudo make install

```
### now enjoy it 😘 but how to enable zh-CN language ???

![image](https://user-images.githubusercontent.com/12899262/72197443-5ec7a800-345c-11ea-95aa-fdb6684f1336.png)

**Comment by denisidoro** [comment]
Hi, @geekyouth!

For zh-CN you can copy-paste the existing cheats and translate them accordingly

If you want a more structure i18n, please feel free to reopen this issue 👍
