### ISSUE TITLE
support fzf multiple choice

### ISSUE THREAD

**Issue by beardnick** [denisidoro/navi#173]
take git add for example:
git add file1 file2 file2 ...

git can add multiple files in one time and fzf support selecting multiple items in one time too.

so we can write cheat like:
git add [files]

files means an array type variable

and you may want to add a separator to the array items:
git add [files/ ]

the space after / suggest that use space as separator

**Comment by denisidoro** [comment]
Cool idea. I'm worried about `[` `]`, though. I imagine there are cases where one really wants to use these characters in the snippet itself. Any other ideas?

What if this behavior were determined in `$ files: ...`?
