### ISSUE TITLE
Add integration with github.com/cheat/cheat

### ISSUE THREAD

**Issue by rpietro** [denisidoro/navi#176]
This post is neither a bug nor a feature request, but I wasn't sure where else to place it. Here is what I am trying to do: I pointed navi's path toward a cheat https://github.com/cheat/cheat directory with personal cheat files. The problem is that these files don't end in .cheat. If I change them to include .cheat, then cheat doesn't recognize those files

The question then is: how can I make navi recognize my cheat files even if they don't have a .cheat ending?

**Comment by denisidoro** [comment]
I could make navi behave like this:

- If `$NAVI_PATH` is `/folder/with/cheats` and `/cheats` is a folder, then it will search for files that end with `.cheat` for backward compatibility.

- If `$NAVI_PATH` is `/folder/with/cheats/*` and `/cheats/foo` is a file, then navi will consider it as well.

**Comment by rpietro** [comment]
@denisidoro thanks. if I use your first option it does what you expected since my files have no .cheat ending:

```
[user@computer ~/Desktop]$ navi
cat: /home/use/.dotfiles/cheat/.cheat/: Is a directory
No valid cheatsheet!
```

if I try your second option, I do not get an error, it does give me a typical fzf menu, but when I type something like "tar" (I do have a cheat file for tar) it shows nothing.

**Comment by denisidoro** [comment]
Oh, I think my message wasn't clear. As of now, `navi` won't work for your use case. My previous message was a suggestion for an implementation that would fit for you.

Do you think this suggestion makes sense? If so, I can try to implement it in the near future.

**Comment by rpietro** [comment]
@denisidoro got it now, it does make perfect sense. thanks a lot

**Comment by denisidoro** [comment]
As soon as we have https://github.com/denisidoro/navi/issues/237, this should be trivial

**Comment by denisidoro** [comment]
Given that navi supports git repos now and one could simply download a repo for other cheatsheet tool + apply some script to convert it, I don't plan to support this anymore.

If you think this would be useful, please feel free to reopen it.
