### ISSUE TITLE
Escaping issue with fish as of commit e9dc75555b4bf5287f77209670994a0ac693840c

### ISSUE THREAD

**Issue by curio77** [denisidoro/navi#179]
**Describe the bug**
Getting `fish: Unexpected end of string, quotes are not balanced` as of commit `e9dc75555b4bf5287f77209670994a0ac693840c`, see attached screenshot.

**To Reproduce**
1. Active navi in a fish environment.  It doesn't matter whether per keyboard shortcut or via command `navi`.
2. Observe the above effect irrespective of the selected cheat.

**Expected behavior**
Instead of the error message, a preview of the selected command should be shown as per usual.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/973703/72833739-ba2d3d80-3c87-11ea-8d9c-67bf06dece82.png)

**Versions:**
 - OS: Linux (Gentoo)
 - Shell Version: fish v3.0.2
 - navi version: v0.18.1

**Comment by denisidoro** [comment]
😢 I'm in this fight with escaping vs bash for more time than I would like...

I plan to rewrite this project to Rust in a few weeks (let's see if my plan goes well) and this issue shouldn't happen anymore. 

I'll try to revert my latest change. 

Until then, could you please use an older version?

**Comment by curio77** [comment]
Yes, of course, I'll just revert my clone. Good luck with the Rust port, and thanks for your work!
