### ISSUE TITLE
Not resolving custom cheats

### ISSUE THREAD

**Issue by aserrallerios** [denisidoro/navi#183]
Navi cannot find cheats of a custom cheats file.
```
> echo $NAVI_PATH
/Users/xxxx/.cheats
> ls $NAVI_PATH
kubectl.cheat
> cat $NAVI_PATH/kubectl.cheat
% kubernetes, kubectl, k8s

# Scale a deployment
kubectl scale deployment --replicas <number> <deployment>
```
When I do Ctrl+G and search for "Scale", it shows nothing.

I load navi via zsh plugin and PATH.
```
# load plugin with antibody
NAVI_PATH="$HOME/.cheats"
PATH=$_navi_path:$PATH
```

**Comment by enisozgen** [comment]
There must be something wrong, in your environment.  I am using same feature.

I tried to imitate your configuration with your `.cheats` folder and `kubectl.cheat`. It is working. perfect. It directly it asks for `<number>`

There is `_call_navi` function in project. Use `echo $your_variables(PATH NAVIPATH etc)` there and try to see they still show correct directory or value. 

I think easily you can see what is problem there. 

BR

**Comment by aserrallerios** [comment]
Sorry, I don't understand the part about `echo $your_variables(PATH NAVIPATH etc)`. Can you write an example?

**Comment by aserrallerios** [comment]
BTW, if I execute navi like this, it works totally fine (it asks me the number):

`navi --path "~/.cheats"`

**Comment by aserrallerios** [comment]
Ok, that was a little clue to my problem. I wasn't _exporting_ the variable. This fixed it:

```
+export NAVI_PATH="$HOME/.cheats:$_navi_path/cheats"
```
