### ISSUE TITLE
Variables: Take user input from STDIN

### ISSUE THREAD

**Issue by knodesec** [denisidoro/navi#184]
Sometimes a command may require user input, at the moment, I can't see a clear way of reading from STDIN to take user input, unless I have missed something.

**Comment by denisidoro** [comment]
You can simply write a cheat such as `echo <myvar>` without specifying the possible results of `myvar`. In this case, navi will prompt from stdin

**Comment by knodesec** [comment]
Perfect, I must have missed this in the docs somewhere. Thanks!
