### ISSUE TITLE
Escaping ANSI sequences.

### ISSUE THREAD

**Issue by bitozoid** [denisidoro/navi#186]
**Describe the bug**

This command on a cheatsheet does not work well:

```
# reset terminal title
echo -ne "\033]0;$(hostname)\007"
```

**To Reproduce**

Append this to a cheatsheet.

```
# reset terminal title
echo -ne "\033]0;$(hostname)\007"
```

Paste with navi on a terminal, and then get

```
$ echo -ne "
stname)
```

**Expected behavior**

```
$ echo -ne "\033]0;$(hostname)\007"
```

**Versions:**

 - OS: exherbo Linux
 - zsh 5.7.1 (x86_64-pc-linux-gnu)

**Comment by denisidoro** [comment]
Similar to https://github.com/denisidoro/navi/issues/131

**Comment by denisidoro** [comment]
The version at master doesn't have this bug
