### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [denisidoro/navi#2]
There is no LICENSE or COPYING file for this project. The default is copyright.

You should license this project under the AGPL3 or GPL3 license. Directions on how to apply the license are at the bottom of the license file under the `How to Apply These Terms to Your New Programs` heading.  There is a helpful guide for the GPL at https://www.gnu.org/licenses/gpl-howto.en.html.  If you would like me to submit a PR to make this easier, I would be happy to do that.

**Comment by AndresMPR** [comment]
This is an important step and will help with other people’s adoption and use of this tool!
