### ISSUE TITLE
Validate argument names

### ISSUE THREAD

**Issue by denisidoro** [denisidoro/navi#20]
The script should be aborted if a regex isn't matched, to avoid arbitrary code execution

**Comment by MetalDent** [comment]
Hi, is anyone working on this?

**Comment by denisidoro** [comment]
I'm not!

For anyone interested, it's need to add something like `abort_if_unsafe_arg "$escaped_arg"` right before [this line](https://github.com/denisidoro/navi/blob/master/src/main.sh#L42) and maybe after [this one](https://github.com/denisidoro/navi/blob/master/src/main.sh#L45).

**Comment by MetalDent** [comment]
Here `escaped_arg` is the regex and `arg` is to be checked, right?

**Comment by denisidoro** [comment]
No, `escaped_arg` is equal to `arg` but with some dash vs underscore differences.

The regex is [this one](https://github.com/denisidoro/navi/blob/master/src/arg.sh#L3).
