### ISSUE TITLE
Can`t install from source

### ISSUE THREAD

**Issue by ruabmbua** [denisidoro/navi#211]
**Describe the bug**
I can not install from source. Tried the suggested install procedure, but I get:

```
ln: die symbolische Verknüpfung '/usr/bin/navi' konnte nicht angelegt werden: Keine Berechtigung
ln: die symbolische Verknüpfung '/usr/local/bin/navi' konnte nicht angelegt werden: Keine Berechtigung
```

Which means, its trying to install to /usr.
Can I install NAVI without root?

**To Reproduce**
1. `make install`

**Expected behavior**
Installs somewhere, where it does not requite root permissions.

**Versions:**
 - OS: ArchLinux
 - zsh 5.8 (x86_64-pc-linux-gnu)
 - GNU bash, Version 5.0.16(1)-release (x86_64-pc-linux-gnu)

**Comment by denisidoro** [comment]
Where could I install it to? I could install it to, say, ~/.navi, but the used would need to add it to $PATH. WDYT?

**Comment by ruabmbua** [comment]
I would actually prefer setting up the PATH env on my own.

sudo make install also does not work, because my root does not have a rust toolchain installed. I imagine this will be the case for many people.

**Comment by denisidoro** [comment]
Could you review it, please? ^
