### ISSUE TITLE
Metacomments.

### ISSUE THREAD

**Issue by bitozoid** [denisidoro/navi#215]
**Is your feature request related to a problem? Please describe.**

I miss to trace back the reasons why a long command looks the way it has been defined in a cheatsheet.

**Describe the solution you'd like**

I'd like to add non-searchable comments (metacomments) to my cheatsheet to explain some commands.

**Describe alternatives you've considered**

Add to the syntax something like:

```
## non searchable comment
```

**Comment by denisidoro** [comment]
Would `;` work for you?

`##` is trickier because it's more expensive to check for a substring instead of a single char

**Comment by bitozoid** [comment]
Looks great to me.
