### ISSUE TITLE
Can't source the widget scripts

### ISSUE THREAD

**Issue by alebianco** [denisidoro/navi#224]
**Describe the bug**
Can't source widget when installing from brew

**To Reproduce**
1. Follow the readme to install and source the bash widget
2. $ brew install denisidoro/tools/navi
3. $ source "$(navi widget bash)"

**Expected behavior**
bash script is found and sourced to make navi available

**Screenshots**
![Screenshot 2020-03-11 at 20 32 31](https://user-images.githubusercontent.com/772115/76456698-ae344100-63d7-11ea-81ce-581e359c14c3.png)

**Versions:**
 - OS: macOs 10.14
 - Shell Version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

**Additional context**
The brew formula moves shell scripts and cheats to libexec while the widget command looks for them in the bin folder

**Comment by denisidoro** [comment]
Although they seem unrelated, it's equivalent to https://github.com/denisidoro/navi/issues/223

**Comment by alebianco** [comment]
Yep, related and version 2.0.4 partially addresses the issue.

The path where the brew formula installs the plugins and the cheats it's still different from there the widget command looks for the files tho.

❯ navi widget bash
/usr/local/bin/../Cellar/navi/2.0.4/**bin/shell**/navi.plugin.bash

❯ ll /usr/local/bin/../Cellar/navi/2.0.4/**libexec/shell/**
Permissions Size User    Date Modified Name
.rw-r--r--   157 abianco 12 Mar  0:34  navi.plugin.bash
.rw-r--r--   351 abianco 12 Mar  0:34  navi.plugin.fish
.rw-r--r--   209 abianco 12 Mar  0:34  navi.plugin.zsh
