### ISSUE TITLE
Integration with Skim

### ISSUE THREAD

**Issue by ngirard** [denisidoro/navi#227]
[Skim](https://github.com/lotabout/skim) is a nice Rust equivalent for Fzf.

How about integrating Navi with Skim ? In could consist in either
- make it possible to call the `skim` binary as an alternative for `fzf` ;
- use Skim as a library.

**Comment by denisidoro** [comment]
Duplicate #115

**Comment by denisidoro** [comment]
In the past I tried to support skim but I gave up because it would require too many changes.

With the current implementation, this is the only file one needs to change: https://github.com/denisidoro/navi/blob/master/src/fzf.rs

**Comment by denisidoro** [comment]
Related: https://github.com/lotabout/skim#use-as-a-library
