### ISSUE TITLE
navi --path panics if path contains no .cheat files

### ISSUE THREAD

**Issue by kbknapp** [denisidoro/navi#228]
First, thanks for `navi`! It's a super cool project!

**Describe the bug**
navi --path panics if path contains no .cheat files.

**To Reproduce**
1. `navi --path ~/.local` (or any path that contains no `.cheat` files

**Expected behavior**
Either, `navi` runs with no cheat suggestions/options, or an error of something like, `error: no cheat files found` would be fine.

**Screenshots**

```
❯ navi -p ~/.local
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: Other, message: "Is a directory" }', src/cheat.rs:81:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Failed to read /dev/tty
```
After applying the following patch to ensure no `Err` is `unwrap()`ed:

```
diff --git a/src/cheat.rs b/src/cheat.rs
index f670214..8693e94 100644
--- a/src/cheat.rs
+++ b/src/cheat.rs
@@ -77,7 +77,7 @@ fn read_file(
     let (tag_width, comment_width) = *display::WIDTHS;

     if let Ok(lines) = filesystem::read_lines(path) {
-        for l in lines {
+        for l in lines.filter(|l| l.is_ok()) {
             let line = l.unwrap();

             // tag
```

It then just hangs until Ctrl+C
```
❯ navi -p ~/.local

^C
❯
```

**Versions:**
 - OS: Regolith Linux (Ubuntu 19.10)
 - Shell Version: zsh 5.7.1 (x86_64-ubuntu-linux-gnu)

**Additional context**
N/A

**Comment by mxzel** [comment]
I have the same error. In Macos system, if a directory that store .cheat files contains a .DS_Store file, the program will produce a same error.
Anyway, it does a cool project, really thanks!
