### ISSUE TITLE
Make fzf --exact optional

### ISSUE THREAD

**Issue by itmecho** [denisidoro/navi#232]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to choose not to invoke `fzf` with the `--exact` option as this disables the fuzzy finding capabilities which are extremely useful.

https://github.com/denisidoro/navi/blob/4dffbe6f2987124aa1c148486a785f66169d905c/src/fzf.rs#L55

**Describe the solution you'd like**
Don't invoke `fzf` with `--exact` by default. I think this is something that people can add with `--fzf-overrides`.

**Describe alternatives you've considered**
If you don't want to change the default behaviour, it could be a flag along the lines of `--fzf-fuzzy-enable` or something.

**Comment by denisidoro** [comment]
Hi, you can use `navi --fzf-overrides ' --no-exact'` for that purpose. Please let me know it that works out for you.

**Comment by itmecho** [comment]
Ah yea, that works! I was trying that with the environment variable but it wasn't working:

    # This didn't work
    FZF_DEFAULT_OPTS=" --no-exact" navi --print
    
    # Neither did this
    export FZF_DEFAULT_OPTS=" --no-exact"
    navi --print
    
    # but your suggestion of the override flag does work
    navi --print --fzf-overrides ' --no-exact'

Am I using the environment variable incorrectly or is it just not working properly? I'd like to set it in my `.zshrc` =]
