### ISSUE TITLE
Use a standardised config location

### ISSUE THREAD

**Issue by itmecho** [denisidoro/navi#233]
**Is your feature request related to a problem? Please describe.**
Not a problem as such, more a nicety. Also, only a suggestion!

**Describe the solution you'd like**
I'm the maintainer of the `navi-bin` AUR package and it would be great if `navi` could look for cheat files in a standard location like `~/.config/navi`. This would make it a lot easier to install as you could have `~/.config/navi/builtin` for the bundled cheats and `~/.config/navi/custom` for custom cheats. This way it's not loading the cheats relative to where the binary is located.

**Describe alternatives you've considered**
Currently I'm using the `NAVI_HOME` variable to point navi to my cheats but there isn't really a nice way to set that when installing from the AUR.

You could also have it store the builtin cheats somewhere like `/usr/share/navi/cheats` and then load any other cheats from `~/.config/navi` if that folder exists.

**Comment by denisidoro** [comment]
I'm totally for this!

But I don't know to implement this. Help needed!

Related comments: [here](https://github.com/denisidoro/navi/issues/223#issuecomment-598144375) and [there](https://github.com/denisidoro/navi/issues/223#issuecomment-598249133).

**Comment by ngirard** [comment]
@denisidoro, you can use the [dirs](https://lib.rs/crates/dirs) crate for this. It provides you with `dirs::config_dir()`.

**Comment by itmecho** [comment]
Thanks @ngirard I didn't know about the `data_dir` function! I've added it to my PR =]

**Comment by denisidoro** [comment]
Could you please review https://github.com/denisidoro/navi/pull/258?
