### ISSUE TITLE
panic if expected cheats dir is missing (even if not used/empty)

### ISSUE THREAD

**Issue by kbknapp** [denisidoro/navi#243]
**Describe the bug**
[`navi` looks for several standard `cheats` directories relative to the current exe](https://github.com/denisidoro/navi/blob/95ed76f40ce29f21b4925b68f4f529ec9569b41e/src/filesystem.rs#L45). If none of these directories are found, `navi` will `panic`.

My use case is I have my own `.cheat` files, but none of the standard files. My binary is located in `~/.local/bin` yet my cheats are located in my `~/.dotfiles/navi` directory. 

I have an alias that runs `navi --path ~/.dotfiles/navi`

Adding an empty `cheats` dir relative to the binary fixes the panic. However, this shouldn't be required when using `--path`. Also, using `../` or `../../` within hard coded relative paths may not be advisable within security contexts, but I haven't put enough thought into this and if it's actually an issue or not.

**To Reproduce**
1. Ensure none of [these directories exist (relative to the `navi` binary)](https://github.com/denisidoro/navi/blob/95ed76f40ce29f21b4925b68f4f529ec9569b41e/src/filesystem.rs#L45)
2. Run `navi`

**Expected behavior**
If using `--path` with valid `.cheat` files, those cheats are displayed. If not `--path` then no cheats are displayed (i.e. a blank window).

**Screenshots**
The panic is:

```
❯ navi
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/cheat.rs:137:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Failed to read /dev/tty
```

However, after:

```
❯ mkdir -p ~/.local/bin/cheats
❯  navi

<< blank window displayed correctly >>
```

**Versions:**
 - OS: Regolith Linux (Ubuntu 19.10)
 - Shell Version: zsh 5.7.1 (x86_64-ubuntu-linux-gnu)
 - `navi` Version: 2.0.6

**Additional context**
N/A

**Comment by denisidoro** [comment]
I believe the version at master fixes this. I'll test it tomorrow.
