### ISSUE TITLE
Sections with lots of tags are not searchable by all tags

### ISSUE THREAD

**Issue by OriR** [denisidoro/navi#249]
**Describe the bug**
sections with a lot of tags aren't searchable in smallish terminals.

It looks like because the tags are trimmed to a certain length before being passed to `fzf` then `fzf` can't seem to search them.
For instance, if you search `js` then you wouldn't find the `js` snippets in a small enough terminal.

**To Reproduce**
1. Open a terminal
2. Shrink the terminal
3. Ctrl+g to use navi
4. Search for `js`
5. See that no `js` snippet is found

**Expected behavior**
Be able to search snippets through all tags.

**Screenshots**
![image](https://user-images.githubusercontent.com/2384068/76603064-f147fe80-6514-11ea-8683-7bbbe80a7e29.png)
![image](https://user-images.githubusercontent.com/2384068/76603154-205e7000-6515-11ea-835b-e7d58f2b1778.png)

You can see that `js` tag is part of this cheat
https://github.com/denisidoro/navi/blob/f8e8da018bcd2598a47260581faad2cbafad7f3a/cheats/javascript.cheat#L1

**Versions:**
 - OS: ChromeOS (with debian linux)
 - Shell Version: zsh 5.3.1

**Comment by denisidoro** [comment]
That's a known problem but I'm afraid there's no way to fix it :disappointed:

fzf won't allow one to search for something that isn't displayed on the screen. 

And if I don't trim columns, they won't be aligned and potentially you'll only be able to see the first column.

**Comment by denisidoro** [comment]
Related: https://github.com/junegunn/fzf/issues/1440#issuecomment-443480229

**Comment by OriR** [comment]
😞 

That's a shame because it kinda makes the tags a bit redundant for me. I'd rather put these tags as the description of the commands which is given a lot more space in the UI.
I know I tend to search using keywords rather than sentences, as well as most other developers I know.

But, In theory it's possible, if we were to call `fzf` without letting take over the terminal (`--filter`) and then draw the UI ourselves, simply using `fzf` for a fuzzy search we could decouple the filtered string from the displayed string.

Also, #227 could help here as we'd send the full line to skim as it's just a library, and again, build the UI ourselves.

**Comment by denisidoro** [comment]
Supporting skim does seem to be a nice idea.

Regarding your use-case, this would be helpful: https://github.com/denisidoro/navi/issues/202

**Comment by OriR** [comment]
Looking forward to being able to resize columns :)

**Comment by denisidoro** [comment]
Hi! Sorry for the late reply.

Being 100% honest here: this is a feature it would be nice to have but unfortunately I haven't had much free time lately, so I have no plans to implement this in the near future.

If anyone could submit a PR for this, I'll gladly accept it, though! 👍 

(One additional comment: skim is already supported --as a binary, not as a library. Maybe this issue already has a workaround?)
