### ISSUE TITLE
$ variables as "recomendation"

### ISSUE THREAD

**Issue by mrVanDalo** [denisidoro/navi#253]
**Is your feature request related to a problem? Please describe.**

in this snippet

```
# login to a server and forward to ssh key (dangerous but usefull for bastion hosts)
ssh -A <user>@<server>
```

I would like to give just "recommendations" for `user`.

This just sets it to `whoami`
```
$ user : whoami 
```

This opens fzf and let me type something but typing something like `root` lets `navi` crash
```
$ user : whoami && echo 
```
```
thread 'main' panicked at 'byte index 18446744073709551615 is out of bounds of ``', src/libcore/str/mod.rs:2017:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I also tried 
```
$ user : whoami && echo --- --print-query
```
but this resulted in the same error.

**Describe the solution you'd like**

I would like to write this
```
$ user : whoami && echo "root" --- --print-query
```
or
```
$ user : whoami --- --print-query --no-select-1
```

to use `whoami` and `root` only as recommendation, so I can type what ever I want.

**Comment by denisidoro** [comment]
<img width="578" alt="Capture d’écran 2020-03-13 à 12 32 09" src="https://user-images.githubusercontent.com/3226564/76635754-b222a900-6526-11ea-86c8-d0773a8b0552.png">

In this case, if I type `d<enter>` what should be the expected value? `d` or `denis.isidoro`?

**Comment by mrVanDalo** [comment]
Good point.

**Comment by denisidoro** [comment]
fzf returns what you typed as the first line and the best result as the second one

**Comment by mrVanDalo** [comment]
I see, I'm not too familiar with `fzf`. Did I make my idea, workflow clear? Do you think this make sense? or is possible to implement?

**Comment by denisidoro** [comment]
Yes! My only question is: in your case, if you type `p<enter>` I don't know what to return. If `p` or `palo`. 

If you say `palo`, what if the user really wants `p` as value?
If you say `p`, then the suggestion won't be useful.

WDYT?

**Comment by mrVanDalo** [comment]
Hmm not a simple question I would say. I guess it makes more sens `palo` if I would set `<user>` to `peter` I have to write it out anyway. The only problem arises when I want to set `<user>` to a value which is a substing of `palo`, which is  `pal` or `pa` or `p`.
In this case it seems obvious that should not be a problem, but in other cases
it might result in problems. I can't think of any so far though.

**Comment by denisidoro** [comment]
This may work, I guess
```
x="$(echo -e "$(whoami)\nroot" | fzf --print-query --expect tab,enter)"; echo "x is $x."
```

**Comment by mrVanDalo** [comment]
So when the user presses `tab` it will use the second line and the user presses `enter` it will use the first line?

**Comment by denisidoro** [comment]
Yes, unless the user hit `enter` without input. Then it would use the last line. Does that make sense?

**Comment by mrVanDalo** [comment]
Make sense, I mean it is kinda hidden in the `cheat` file. The user does not know of this behavior, because he can't see it. But I guess this is a good default.

So `tab` and `enter` will be interpreted like that?

**Comment by denisidoro** [comment]
Yeah, the final syntax could be:
```
$ user: whoami; echo root -- --allow-extra
```

and the code would take care of the rest.

A documentation entry could be provided.

**Comment by mrVanDalo** [comment]
> A documentation entry could be provided.

Do you mean someone (I could do that) should write something in the README or a explanation window in `fzf` will be set and describes the `tab` and `enter` interpretation?

**Comment by denisidoro** [comment]
Hmm, I'm not sure I'm following. Before documenting it we need to implement it hahaha
You can't add any custom `fzf` option after `---`.
That's why I suggest we create the `--allow-extra` option and add the relevant code.

**Comment by mrVanDalo** [comment]
I could try to implement it, tomorrow though. It's quite late where I am.

**Comment by mrVanDalo** [comment]
I have some time today, will work on this issue.

**Comment by mrVanDalo** [comment]
I'm on that, and it seems `--multi` and `--allow-extra` can't be used at the same time.
