### ISSUE TITLE
Add back multiline support

### ISSUE THREAD

**Issue by AlexanderThaller** [denisidoro/navi#260]
It seems to be that multi-line command where supported in an older version (https://github.com/denisidoro/navi/issues/88).

Is that a feature that will be coming back? I can also try to implement it and open a pull request but want to make sure that this is a feature that is actually wanted first.

Thanks for all your work its a nice tool :D

**Comment by AlexanderThaller** [comment]
Right now multiline commands look like this which I dont think is super usefull:


![](https://upload.thaller.ws/files/1af0cae9a27297aa95c0f333bca2e0de71147665/2020-03-14_17-38-42_14479.png)

I'm not totally sure how to display multiline commands yet.
Maybe displaying the newlines as \n in the command would be good enough for now. I think making sure that the newlines are put back when the command is printed/executed would be a good idea so that snippets that rely on newlines to be correct are still working.

**Comment by denisidoro** [comment]
You can write multi-line commands using `\`

Could you share your `.cheat`?

**Comment by denisidoro** [comment]
I'm working on a PR that doesn't require `\`

**Comment by AlexanderThaller** [comment]
Thank you for the quick response
