### ISSUE TITLE
Include ZSH history

### ISSUE THREAD

**Issue by StarpTech** [denisidoro/navi#263]
Hi, is it possible to put all entries of my `.zsh_history` into the search context?

I tried

> You can use navi as a widget to your shell. This way, your history is correctly populated and you can edit the command as you wish before executing it.

but it doesn't work.

**Comment by denisidoro** [comment]
I'm not sure I'm following. Do you mean you want to use your `.zsh_history` as a cheatsheet? Or do you mean to add an entry to `.zsh_history` every time you use navi?

**Comment by denisidoro** [comment]
If it's the former, you could write a simple script that maps `.zsh_history` to a `.cheat`, but what would you use as 'tag` and `description`?

**Comment by StarpTech** [comment]
Hi @denisidoro I think I mixed it up. Navi is for sheet cheats only. I use https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/fzf for now. Thanks for the fast response.
