### ISSUE TITLE
Cheats stored in wrong directory

### ISSUE THREAD

**Issue by ngirard** [denisidoro/navi#269]
Using `navi` v2.1.0, when started for the first time, it downloads cheats in `~/.local/config`, which is IMHO inappropriate.
Cheat files are indeed data rather than configuration, and are supposed to be stored into `dirs::data_dir` or `dirs::document_dir`, as suggested in #233.

**Comment by denisidoro** [comment]
Honest question: why is `data_dir` better than `config_dir`?
AFAIK, neovim, ranger and a lot of other CLIs store config files in "$HOME/.config". WDYT?

**Comment by denisidoro** [comment]
My bad, you answered it already 😅

**Comment by denisidoro** [comment]
https://github.com/denisidoro/navi/commit/07134996e44b04402bdecc4561ab8cf30e23afb3

**Comment by ngirard** [comment]
Great, thanks !
