### ISSUE TITLE
Installation quirks when using pre-compiled binaries

### ISSUE THREAD

**Issue by ngirard** [denisidoro/navi#270]
When using pre-compiled binaries to install Navi, the following problems arise:
1. the installation instructions in the README are incomplete, since they don't explain how to install the completion files ;
2. the package doesn't contain the completion files nor any installation script.

Also, it would be nice if the packaged files were placed into a parent `navi-${version}` directory.

**Comment by denisidoro** [comment]
By completion files you mean the cheatsheets? navi should suggest installing cheats from a remote repo in the first run.

**Comment by ngirard** [comment]
I mean the shell completion files.

**Comment by denisidoro** [comment]
I've haven't setup any completion files yet

**Comment by denisidoro** [comment]
Related: https://clap.rs/2016/10/25/an-update/

**Comment by ngirard** [comment]
@denisidoro, I'm talking about the navi.plugin.{bash,fish,zsh} files: they are not packaged currently.

**Comment by denisidoro** [comment]
They shouldn't be anymore. Please follow these instructions: https://github.com/denisidoro/navi/blob/master/README.md#shell-widget

I'll add a message to the install script such as "to install the shell widget, please add..." so people don't need to check the README

**Comment by ngirard** [comment]
Ooh, so you added them statically within the program ? That's nice !

**Comment by ngirard** [comment]
In this case, I'm closing this issue.

Still, could you please add the version number to the name of the tarball, e.g. `navi-2.1.1-x86_64-unknown-linux-musl.tar.gz` ? Thanks in advance !
