### ISSUE TITLE
Default values for variables

### ISSUE THREAD

**Issue by kbknapp** [denisidoro/navi#279]
**Is your feature request related to a problem? Please describe.**

There are times I have a complex command that 95% of the time uses a particular value, but that other 5% needs to be entered manually (i.e. not from a known list of values).

**Describe the solution you'd like**

I would like to be able to give a default value for a variable, but still have the option to edit it. I.e. in FZF I'd be presented with the default, but be allowed to type in something totally different if desired.

For example I tried `$ foo: echo 'default ' | tr ' ' '\n'` which displays the default, but upon typing something different `navi` panics (presumably because nothing was selected?).

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/fzf.rs:142:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Describe alternatives you've considered**

Currently in `navi` I have to either enter it manually 100% of the time (by not listing it in `$` lines), or just be happy with a default and edit the line manually after `navi` exits.

**Additional context**

N/A

**Comment by denisidoro** [comment]
Could you use `--allow-extra`? https://github.com/denisidoro/navi/blob/master/README.md#advanced-variable-options

Does that cover your use case?

**Comment by kbknapp** [comment]
That works for me! I didn't know that's what `--allow-extra` did. Thanks!
