### ISSUE TITLE
Deduplicate results

### ISSUE THREAD

**Issue by kbknapp** [denisidoro/navi#283]
(disclaimer: Hopefully you don't mind all the issues I've been filing. I really enjoy this project so I'm trying to list the things I'm hitting/wishing for :smile: )

This could be a bug or feature-request depending on how you look at it.

**Is your feature request related to a problem? Please describe.**

`navi` duplicates results. I.e. I have a personal repository of `.cheat` files, as well as a shared repository at work of `.cheat` files. There are .cheat files I have in my personal repo, that are also applicable to my work/co-workers, however I don't want to "move" my personal cheat files into the work repository since I may not be at that job forever, and co-workers can also make changes that my not fit my personal flows.

However, having the same cheats in two places means I get duplicate results cluttering the navigation window and taking time to figure out if they really are duplicates, or just similar (we have a lot of similar cheats as well, that look like duplicates at first glance).

**Describe the solution you'd like**

Results are filtered. Exact duplicates are only displayed once.

**Describe alternatives you've considered**

Only alternatives are manually curating cheat files, or living with duplication.

**Additional context**

Implementation wise, I'd prefer each cheat line to be looked at independently, and not cheat files as a whole. I.e. my personal `git.cheat` isn't an exact duplicate of my work's `git.cheat`, however many cheats inside that file *are*.

I would imagine hashing the the lines would solve this and would be fast enough that it wouldn't impact performance. I'm sure there's some fashion in which the cheats could be lazily hashed as well, (since for example there may be 10,000 cheats, but only 100 or so can fit on a page at once).

I'd be happy to take a look at the impl for this given a starting point of where to look.

**Comment by denisidoro** [comment]
You could create a hashset here https://github.com/denisidoro/navi/blob/master/src/cheat.rs#L124 and if the line is already there, just continue.

I won't be able to implement it today, but feel free to do so and I'll review and merge it :+1:

I won't require any advanced benchmarks, but to whoever implement this, please make sure there's no noticible lag for, say, 1500 lines + there's no substantial increase in RAM.

**Comment by denisidoro** [comment]
Actually the hashset should be create outside this function because we want to maintain the values from previous calls of this function.

**Comment by kbknapp** [comment]
I'll take a stab at it after work today. I'll dig around too and see the flow and where the best place to do some hashing may be, I just needed a jumping off point :wink:

**Comment by denisidoro** [comment]
Maybe consider: https://docs.rs/bloom/0.3.2/bloom/

**Comment by kbknapp** [comment]
The problem with a bloom filter is you want the opposite guarantee it provides. A false positive in `navi` terms would be not adding a cheat to the displayed list, when in there are actually no duplicates. Having the occasional false negative (adding a duplicate by accident) would be a better outcome. I try and look at some benchmarks to see how big of a difference it makes

**Comment by denisidoro** [comment]
Don't worry about performance too much, though
