### ISSUE TITLE
`preview` subcommand?

### ISSUE THREAD

**Issue by Kibouo** [denisidoro/navi#286]
What is (/was?) the `preview` sub-command supposed to do? Can't find any references to it.

**Comment by Kibouo** [comment]
P.S.: maybe a `questions` tag would be useful?

**Comment by denisidoro** [comment]
Do you mean `preview`? If so, it's for internal usage only (to show content in fzf's preview window)

**Comment by Kibouo** [comment]
Yes, `preview`. Misread it.

I see. Is there a reason as to why it's a public subcommand? Could it not be handled internally? (Trying to understand the codebase).

**Comment by denisidoro** [comment]
When I call fzf, I can't determine the preview contents directly. I must pass an arbitrary code for fzf to use. In this case it's `navi preview`.

If must be public, then. But the I wrote it it won't appear in the --help window.

**Comment by Kibouo** [comment]
Thanks for the explanation!
