### ISSUE TITLE
Multi select only returns first selection

### ISSUE THREAD

**Issue by itmecho** [denisidoro/navi#288]
**Describe the bug**
When passing the `--multi` variable option, navi only prints the first selection from fzf

**To Reproduce**
Add this cheat, run it and select multiple pods:
```
% kubernetes, pods

# Dynamically delete pods in the current namespace
kubectl delete pod <pods>

$ pods: kubectl get pods --- --column 1 --header-lines 1 --delimiter '\s\s+' --multi
```

**Expected behavior**
Should print something like `kubectl delete pod pod-1 pod-2`

**Versions:**
 - OS: Arch `Linux core 5.5.9-arch1-2 #1 SMP PREEMPT Thu, 12 Mar 2020 23:01:33 +0000 x86_64 GNU/Linux`
 - Shell: `zsh 5.8 (x86_64-pc-linux-gnu)`
 - Navi: `navi 2.1.3`

**Additional context**

**Comment by denisidoro** [comment]
Maybe it's printing this?
```
kubectt delete pod pod1
pod2
```

I confess the README is wrong as it doesn't mention the newline. 

I've tested this at master and it worked: https://github.com/denisidoro/navi/blob/master/tests/cheats/corner_cases.cheat#L35

**Comment by denisidoro** [comment]
Maybe the bug you reported is specific to the case where multi is used with column. I'll need to check that

**Comment by denisidoro** [comment]
That's probably the case: https://github.com/denisidoro/navi/blob/master/src/fzf.rs#L40

We need to perform this regex for each line.

**Comment by itmecho** [comment]
Thanks! 

I'm still not seeing the correct behavior in `2.2.0`. It runs the command with the first command and then just prints out the second argument afterwards.

Example:
```
$ navi
$ kubectl delete pod pod-1
pod "pod-1" deleted
$ pod-2
zsh: command not found: pod-2
$ pod-3
zsh: command not found: pod-3
```

**Comment by denisidoro** [comment]
That's expected. I've decided not to imply that when `--multi` is used, the user wants each line to be a different argument.

Could you try [this](https://github.com/denisidoro/navi#variable-as-multiple-arguments) instead?
