### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by Kibouo** [denisidoro/navi#291]
There is a lot of `unwrap()` used all over the code. It's very hard to locate the reason for crashes when they do happen.

This is related to [this TODO item](https://github.com/denisidoro/navi/projects/1#card-33715856), and I'd like to tackle it.

Questions:
1. To what extent may function signatures be changed? As in making the return type a `Result`? Some `unwrap`s feel uncomfortable and should be bubbled up imho. (I've limited experience working on other people's projects and API changes.)
2. What is your opinion on adding the [anyhow](https://github.com/dtolnay/anyhow) crate? It makes adding context (cause of error) easy, pretty formats error chains, and allows different library error types to interoperate nicely.

**Comment by denisidoro** [comment]
1. I agree the code is very bad and non-idiomatic as-is. This was my first project in Rust and I was learning the language while I was coding it. That said, feel free to make any changes you feel like, including signature changes. I'll happily accept them! :+1: (but please start from the `multi-col` branch in case it hasn't been merged yet)

2. :+1: from me

**Comment by denisidoro** [comment]
Just let me know if you plan on working on this so that our efforts won't overlap, please

**Comment by Kibouo** [comment]
Yes, I will work on it this weekend.On 19 Mar 2020 22:46, Denis Isidoro <notifications@github.com> wrote:
Just let me know if you plan on working on this so that our efforts won't overlap, please

**Comment by Kibouo** [comment]
Closed by #299 🎉
