### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by itmecho** [denisidoro/navi#295]
It would be great to get a short description attached to the release to make it easier to know what's new without having to compare tot he previous tag. Even better would be a list of issues that were added/fixed! A short description would be fine though as I'm sure you want to spend more time working on the code than putting together release notes at this stage :stuck_out_tongue:

**Comment by denisidoro** [comment]
Nice point! I'll try to create a script that builds the changelog based on git log.

As I always squash + merge I only need to make sure the PR descriptions are well written.

**Comment by itmecho** [comment]
That would be great! :grinning:

**Comment by ngirard** [comment]
Admittedly this project is a bit difficult to keep up with.
I'd recommend creating a CHANGELOG.md and adhering to the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines.

**Comment by denisidoro** [comment]
:construction_worker_man:  :construction: :+1:

**Comment by denisidoro** [comment]
I'll use [this](https://github.com/denisidoro/navi/blob/3004112fedde307e410a64e04c89a833c09c2eba/CHANGELOG.md) as base and manually edit to give proper messages for some commits.

Does that work you for you?

**Comment by ngirard** [comment]
@denisidoro, sure, that's great !

**Comment by denisidoro** [comment]
Could you review [this file](https://github.com/denisidoro/navi/blob/98c58d9c5f0908cf44d4185447401f1950480028/CHANGELOG.md), please?

This is the "final" version of the changelog.

I plan to add these pieces of info to each release in https://github.com/denisidoro/navi/releases instead of maintaing a CHANGELOG.md.

**Comment by itmecho** [comment]
Looks great! exactly what I was hoping for =]

**Comment by denisidoro** [comment]
Done: https://github.com/denisidoro/navi/releases
