### ISSUE TITLE
Fish widget disables certain ctrl-keys after completion

### ISSUE THREAD

**Issue by DenSA-Inc** [denisidoro/navi#296]
**Describe the bug**
After using the navi widget for the first time after pressing ctrl-g in the fish shell pressing ctrl-g again won't bring up the widget but print `^G` in the shell. Other shortcuts such as ctrl-t and ctrl-u stop to work too. I didn't find any other way to resolve the issue than to restart the shell.

**To Reproduce**
1. Open fish shell
2. Run `navi widget fish | source`
3. Press ctrl-g and select any entry or exit fzf with ctrl-g

**Expected behavior**
After running the widget I expect to bring it up again with ctrl-g or use other shortcuts just like before running the widget.

**Screenshots**

**Versions:**
 - OS: Ubuntu 18.04 and 19
 - Shell: Fish 2.7.1 & 3.1.0
 - navi: 2.2.0

**Additional context**
The problem lies in the call to `stty sane`, I'm no expert on that but I think it changes how the kernels terminal driver or fish handles input. This call changes a few terminal settings that aren't set to their previous values after navi completes. I added `set ttysettings (stty -g)` before and `stty $ttysettings` after the navi invocation in the code of `navi-widget` and that fixed it.

**Comment by denisidoro** [comment]
Thank you for debugging it! Could you please open a PR with the fix? (otherwise I'll open the PR in the weekend)

**Comment by DenSA-Inc** [comment]
You're welcome. I'll open a PR shortly.
