### ISSUE TITLE
Error while downloading default cheats

### ISSUE THREAD

**Issue by ngirard** [denisidoro/navi#300]
Using Navi 2.3.0 on Ubuntu 19.04.

After installing Navi, adding `source <(navi widget bash)` to `~/.bashrc`, opening a new shell and hitting `Ctrl-g`, I'm getting the following error:

```
> navi repo add denisidoro/cheats 
Cloning https://github.com/denisidoro/cheats into /home/ngirard/.local/share/navi/cheats/tmp...

invalid preview window layout: --preview-window right:30%
Error: Custom { kind: InvalidInput, error: "the source path is not an existing regular file" }
```

**Comment by ngirard** [comment]
The problem doesn't arise using Navi 2.2.0.

**Comment by cmonty14** [comment]
I experience the same issue with Navi 2.3.0 on Arch LInux.

**Comment by ngirard** [comment]
Thanks !
