### ISSUE TITLE
File not found error when opening terminal

### ISSUE THREAD

**Issue by cmonty14** [denisidoro/navi#301]
**Describe the bug**
After upgrade to Navi 2.3.0 I get an error in terminal with bash:
```
bash: #!/usr/bin/env bash

__call_navi() {
    printf "$(navi --print)"
}

bind '"\C-g": " \C-b\C-k \C-u`__call_navi`\e\C-e\C-a\C-y\C-h\C-e\e \C-y\ey\C-x\C-x\C-f"': Datei oder Verzeichnis nicht gefunden
[th@pc7-cubi3 ~]$ 

```

**To Reproduce**
1. Open terminal
2. See error

**Expected behavior**
No error in terminal.

**Screenshots**
attached

**Versions:**
 - OS: Arch LInux
 - Shell Version: GNU bash, Version 5.0.16(1)-release (x86_64-pc-linux-gnu)
![ksnip_20200322-125122](https://user-images.githubusercontent.com/12523591/77248726-efc8b580-6c3b-11ea-8381-2f85893c3142.png)

**Comment by denisidoro** [comment]
Hi! There was a breaking change on the way widgets are loaded.
Could you please follow [these steps](https://github.com/denisidoro/navi#shell-widget) and let me know if that work out for you?

**Comment by cmonty14** [comment]
Issue solved with correct shell widget load command.
