### ISSUE TITLE
Shell out to download repos

### ISSUE THREAD

**Issue by denisidoro** [denisidoro/navi#305]
`navi repo add` uses [git2](https://docs.rs/git2/0.13.0/git2/) to clone repos. Some issues have arisen because of this. 

I plan to change this to curl + tar equivalents. I'll probably shell out because I don't want to add curl + tar + gzip dependencies + keep the OpenSSL one. 

### Pros
- cloning will be faster because it will be possible to download the master zip or tar.gz file directly
- smaller binary size
- it won't rely on local git configs

### Cons 
- if the machine running navi doesn't have canonical implementations of curl or tar, things will fail
- cloning private repos that require ssh won't work

I still haven't made my mind yet so if anyone has strong opinions about it, please shout out.

**Comment by itmecho** [comment]
I think it would be better to keep stuff like this in the binary. One of the major benefits of rust is that it ships a single static binary so adding stuff like this means that there's a dependency on the system running `navi` (other than `fzf`).

What issues did you run into using `git2`?

**Comment by denisidoro** [comment]
@itmecho errors like this:
- https://github.com/denisidoro/navi/issues/292#issuecomment-601711023
- https://github.com/denisidoro/navi/issues/292#issuecomment-602242504

**Comment by denisidoro** [comment]
https://github.com/denisidoro/navi/issues/326

**Comment by denisidoro** [comment]
I'll release a version that shells out and if anything goes wrong or tickets start to pop up, I'll revert it, ok?

**Comment by itmecho** [comment]
👍
