### ISSUE TITLE
Superfluous backslash

### ISSUE THREAD

**Issue by syimyuzya** [denisidoro/navi#306]
When retrieving a multiline command (with `\` at the end of each line except the last) using \<C-g\>, the actual output becomes a single line but the backslashes are preserved, which causes bash to parse it incorrectly.

**To Reproduce**

- Install `misc/weather.cheat`.
- Invode navi with \<C-g\> and type `weather`. (In the interactive window the command is shown correctly as `curl -s "wttr.in" | grep -v "New feature" | grep -v Follow`)
- Press enter. The output is `curl -s "wttr.in" \ | grep -v "New feature" \ | grep -v Follow`, which would give an error `grep:  : No such file or directory` (the single space after the second backslach treated as a filename).

**Expected behavior**

The output should be `curl -s "wttr.in" | grep -v "New feature" | grep -v Follow`, as in the interactive window.

**Versions:**
- navi: 3.2.0
- OS: macOS Mojave
- Shell Version: Bash 5.0.16

**Comment by denisidoro** [comment]
I'm not able to reproduce the problem 😞 

Could you please take a screenshot of the preview window for the `weather` command?

**Comment by syimyuzya** [comment]
> I'm not able to reproduce the problem 😞
> 
> Could you please take a screenshot of the preview window for the `weather` command?

`weather.cheat`:

![navi-1](https://user-images.githubusercontent.com/2662820/77272619-a4d09180-6c7f-11ea-95f5-f0c7446cb1de.png)

Preview:

![navi-2](https://user-images.githubusercontent.com/2662820/77272649-b31ead80-6c7f-11ea-9f30-0cd732e669d3.png)

Output:

![navi-3](https://user-images.githubusercontent.com/2662820/77272729-e2cdb580-6c7f-11ea-8211-e9039fbce9de.png)

**Comment by denisidoro** [comment]
Thanks! That was insightful. I'll look into it

**Comment by chubin** [comment]
Just for your information, to switch the `Follow` line off, you can just add the `?F` option:
```
curl wttr.in/Berlin?F
```

See `curl wttr.in/:help` for more options

**Comment by bonsairobo** [comment]
I am still having this problem in the current latest version 2.23.

```sh
> navi --version
navi 2.23.0

> navi --print --query weather
...select in TUI...
curl -s "wttr.in" \     | grep -v "New feature" \     | grep -v Follow
```

And of course the command fails.

**Comment by syimyuzya** [comment]
> P.S. I am confused why the OP said they were using version 3.2.0. AFAICT this version does not exist?

Oops :joy: should be 2.2.0 (latest version at the time when I reported this
