### ISSUE TITLE
Option to provide the resulting command on the prompt before execution

### ISSUE THREAD

**Issue by hlascelles** [denisidoro/navi#319]
### Feature request: Allow seeing the command before execution

This change would let a user choose a command and variables, and have the result returned to the shell. The user can then give it a quick eyeball and hit `<ENTER>` if happy. 

ie, I want the sequence to look like

1. I choose a cheat:

![image](https://user-images.githubusercontent.com/299102/77829031-396f3f80-7117-11ea-819f-618c9a662453.png)

2. I prepare it

![image](https://user-images.githubusercontent.com/299102/77829039-4b50e280-7117-11ea-89fe-4c3e926b75b5.png)

3. I "receive the prepared result"

![image](https://user-images.githubusercontent.com/299102/77829058-63c0fd00-7117-11ea-8cca-004fa9c150df.png)

4. I see it looks good and hit `<ENTER>`

#### Rationale

1. The user may see something wrong before execution (eg suddenly see "production" is in the firing line...)
1. User shell highlighting may identify syntax issues before execution.
1. The user may want all commands they execute in their history (I do).

It can be a config / ENV switch for those who don't (I don't mind if this is not default behaviour).

Thanks!

**Comment by denisidoro** [comment]
I believe that what you want is already implemented: https://github.com/denisidoro/navi/blob/master/README.md#shell-widget

**Comment by hlascelles** [comment]
Aha, thank you! I also didn't notice running the command `navi` does not give this functionality, but when using CTRL+G it does. Can we expose it as a switch?

**Comment by denisidoro** [comment]
AFAIK, a command can't print to the prompt line. Only to stdout/stderr/file descriptors.

Hence the need to do this at a shell level.

**Comment by hlascelles** [comment]
No problem, thanks for the clarification! :+1:
