### ISSUE TITLE
Show snippet in variable prompt

### ISSUE THREAD

**Issue by hlascelles** [denisidoro/navi#320]
### Feature Request

The cheat information should/could stay on screen when choice is selected.

### Rationale

Example: I want to echo a variable, so I find the cheat:

![image](https://user-images.githubusercontent.com/299102/77828936-7a1a8900-7116-11ea-9fb9-6e5d41641bf1.png)

I select the cheat. My screen shows this:

![image](https://user-images.githubusercontent.com/299102/77828945-8a326880-7116-11ea-8bad-7caf68e28e81.png)

I get distracted by a colleague then look back, and I see the above. The screen has very little information about what is going on. I don't know what I am about to execute.

### Resolution

Can we (have an option to) make sure the cheat info is available on screen after selection?

Thank you for producing this tool, it looks great. I may even finally learn Rust for it.

**Comment by denisidoro** [comment]
The variable prompt could be composed by:
```
<(interpolated) command so far>
<variable>:
```

**Comment by denisidoro** [comment]
Actually the prompt can't be multiline. 

We could use `--preview`, though:

<img width="852" alt="Capture d’écran 2020-03-30 à 19 01 25" src="https://user-images.githubusercontent.com/3226564/77966270-0fee1980-72b9-11ea-9df6-5394283f9f18.png">

<img width="978" alt="Capture d’écran 2020-03-30 à 19 00 57" src="https://user-images.githubusercontent.com/3226564/77966241-006ed080-72b9-11ea-87c0-3b5526256cfa.png">

However, if a variable suggestion is of the form `--- --preview 'some custom preview cmd'` this would be overridden.

WDYT?

**Comment by hlascelles** [comment]
Yes, I believe that is what I was thinking of, looks good :+1:

**Comment by denisidoro** [comment]
I've reverted this because it's much more complex than I imagined (for non happy-path cases). 

My initial implementation was broken for multi-line snippets, snippets with `--map` or `--column` and really complex snippets with a lot of quotes + quote escaping.

I'll need to revisit it in the future.

**Comment by denisidoro** [comment]
Hi! Sorry for the late reply.

Being 100% honest here: this is a feature it would be nice to have but unfortunately I haven't had much free time lately, so I have no plans to implement this in the near future.

If anyone could submit a PR for this, I'll gladly accept it, though! 👍

**Comment by denisidoro** [comment]
I'm giving it another go: https://github.com/denisidoro/navi/pull/398
