### ISSUE TITLE
Install Error - use of unstable library feature inner_deref

### ISSUE THREAD

**Issue by budall** [denisidoro/navi#321]
Hi,

On ubuntu 19.10  when I try to install navi via cargo or via compile from binaries, I get the same error: 

Compiling navi v2.4.1 (/home/brad/.navi)
error[E0658]: use of unstable library feature 'inner_deref': newly added
   --> src/fzf.rs:142:24
    |
142 |         opts.delimiter.as_deref(),
    |                        ^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/50264

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `navi`.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:2: install] Error 101

__________________________________________________________
Any help fixing this would be most appreciated.

thanks,

**Comment by budall** [comment]
should read 'compile from source', not binaries!

Sorry

**Comment by denisidoro** [comment]
I'm not very familiar with rust building tools but maybe yiu have an outdated rust compiler version?

What does `cargo --version --verbose` return?

**Comment by budall** [comment]
This is apparently a rust problem, not your problem. Sorry.

So i uninstallled rustc and installed the rustup package manager.

The make now works all the way to the end, but fails on making a symbolic link to the executable:



 Finished release [optimized] target(s) in 1m 41s
ln: failed to create symbolic link '/usr/local/bin/navi': Permission denied
make: *** [Makefile:2: install] Error 1

Any clues on how to solve this? I tried to make this link myself but then get this error:

navi has been rewritten from scratch. The previous way of calling the program isn't supported anymore.
Please check https://github.com/denisidoro/navi/issues/201 for more details.
I'm sorry for the inconvenience.

**Comment by denisidoro** [comment]
Hmm, if you have cargo then you don't need to run `make`. `cargo install navi` should be enough.

Regarding the `Makefile`, it's very error-prone at the moment and I confess I'll need to revisit it sometime.

**Comment by budall** [comment]
Thanks, got it to run by installing rustup.  Something was wrong with my rust install. 

Appreciate the help.

Brad

**Comment by socay1** [comment]
install navi from cargo with command `cargo install navi`, get error:

> error[E0599]: no method named `as_deref` found for type `std::option::Option<std::string::String>` in the current scope
   --> /Users/tony/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.5.0/src/finder/mod.rs:130:65
    |
130 |     let output = get_column(output, opts.column, opts.delimiter.as_deref());
    |                                                                 ^^^^^^^^ help: there is a method with a similar name: `as_ref`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0599`.
error: failed to compile `navi v2.5.0`, intermediate artifacts can be found at `/var/folders/xj/67c78pk54tq8yggbz5llhtsm0000gp/T/cargo-installDN06ih`
Caused by:
  Could not compile `navi`.

mac os version:  10.14.4
`cargo --version --verbose` print:
    cargo 1.37.0
    release: 1.37.0

any suggestion?

**Comment by denisidoro** [comment]
This is available from version 1.40: https://doc.rust-lang.org/std/option/enum.Option.html#method.as_deref
