### ISSUE TITLE
redirect output of command using fzf

### ISSUE THREAD

**Issue by kuzxnia** [denisidoro/navi#322]
Hi,
i am trying to add multi option to example command from README

```bash
docker rmi <image_id>

$ image_id: docker images --- --column 3 --header-lines 1 --delimiter '\s\s+'
```
first step was to add multi option as was written in manual
`$ image_id: docker images --- --multi --column 3 --header-lines 1 --delimiter '\s\s+'`

which reproduce docker_id's without spaces
`docker image rm 9361505e93cc43a05ae5ac99`

my second thought was to cut output into 12char chunks so 
`$ image_id: docker images --- --multi --column 3 --header-lines 1 --delimiter '\s\s+'' | sed -r 's/(.{12})/\1 /g'`

and output looks the same as shown before.
Is there possibility to redirect output of command using yours fzf features? (like --column :smile:)

ps.
meantime one-liner which does the job
`docker image ls | fzf --multi | rg -o "[a-f0-9]{12}" | tr "\n" " "`

**Comment by denisidoro** [comment]
Could you try this? https://github.com/denisidoro/navi/blob/master/README.md#variable-as-multiple-arguments
