### ISSUE TITLE
Need help on variable dependency 

### ISSUE THREAD

**Issue by plaip** [denisidoro/navi#323]
I would to know why the variable dependency is not working in this case. Do I miss something ? 

```
# Update submodule reference
git add <submodule> && git commit -m "Update submodule: <submodule_name>"

$ submodule: git diff --submodule=diff | awk '{ print $2 }'
$ submodule_name: echo "$((submodule))" | sed 's/.*\///
```
Thanks.

**Comment by denisidoro** [comment]
There's a missing single quote in the last line:
```
$ submodule_name: echo "$((submodule))" | sed 's/.*\///'
```

**Comment by ngirard** [comment]
@plaip, while you're giving Rust tools a shot, why not trying [sd](https://github.com/chmln/sd) as a replacement for Sed ?

**Comment by plaip** [comment]
@denisidoro Thanks. Sorry for inconvenience.. 
@ngirard I will try it, thanks for recommendation.

**Comment by plaip** [comment]
@denisidoro I have add the single quote and it's not working.   

I have removed `| sed 's/.*\///'` as below but something wrong. 

```
$ submodule: git diff --submodule=diff | awk '{ print $2 }'
$ submodule_name: echo "$((submodule))"
```

**Comment by plaip** [comment]
@denisidoro  When I run the cheat above, I see this bash error:
`bash: modules/foo: division by 0 (error token is "foo")`

**Comment by denisidoro** [comment]
Could you run `navi --print` and share the result?
If the command is printed as expected, then the problem is with the command itself or how your git repo is setup.

**Comment by plaip** [comment]
navi --print 

```
bash: modules/foo: division by 0 (error token is "foo")
git add modules/foo && git commit -m "Update submodule: "
```

**Comment by plaip** [comment]
`"$((submodule))"` it's only for arithmetic operation right ? It's not working for a path. 
@denisidoro How can I use my variable in another variable?

**Comment by denisidoro** [comment]
✅ https://github.com/denisidoro/navi/commit/e683c0f28c7fcd308a161ad851bc899ecd92ce30#diff-04c6e90faac2675aa89e2176d2eec7d8
