### ISSUE TITLE
Variable Maps (post choice manipulation)

### ISSUE THREAD

**Issue by kbknapp** [denisidoro/navi#325]
**Is your feature request related to a problem? Please describe.**

I find myself writing cheats that have some level of choice, and currently the only way to give choice is to duplicate the individual cheats. 

A simple example is `firewalld` which can have ephemeral settings (i.e. won't survive a restart) or to make settings permanent simply add `--permanent` to any command.

This is a somewhat contrived example, because it's easy to simply type `--permanent` at the end of any navi printed command, but let's assume the `--permanent` must go in a specific place of the arguments (maybe the middle), then this becomes much more cumbersome. The options are either two cheat lines:

```
# add port permanently
firewall-cmd --permanent --add-port=80/tcp

# add port
firewall-cmd --add-port=80/tcp
```
Or I can edit the navi printed cli manually, which again if the change needs to happen in the middle, is a pain.

**Describe the solution you'd like**

Giving navi the ability to do something with a selection *after* the user picked something through FZF would be awesome.

For example, the above would turn into a single cheat (I'm using `~` to mean "after the user has picked a value for the variable...arbitrary an unimportant, it could be anything):

```
# add port
firewall-cmd <PERM> --add-port=80/tcp

$ PERM: echo 'permanent: yes_permanent: no' | tr '_' '\n'
$ ~PERM: awk '{ if ($0 ~ /y/ ) print "--permanent"; }'
```

Which would allow the user to picked if it's permanent or not.

**Describe alternatives you've considered**

See above.

**Additional context**

Maybe FZF already contains such a feature? I'm not aware of one though.

Also how a user would specify the "after" selection commands is totally up to you. I used `~` in the example, but honestly it doesn't matter.

**Comment by kbknapp** [comment]
It would also be fine if the above example used some form of `---` maybe with a new option like `--map` i.e.

```
# add port
firewall-cmd <PERM> --add-port=80/tcp

$ PERM: echo 'permanent: yes_permanent: no' | tr '_' '\n' --- --map "awk '{ if ($0 ~ /y/ ) print \"--permanent\"; }'"
```

**Comment by denisidoro** [comment]
Hi! I really understand your use case but I think I'm not prepared enough to add a new syntax structure at the moment, considering:
1. I want the syntax to be as simple as possible
1. I definitely want to avoid breaking-changes in the future

For example, I regret having created the `--- --column <n>` syntax because, had I created a `$ ~VAR`-equivalent, this logic wouldn't need to be together with the custom fzf options. It would be much more elegant, indeed.

I'll probably implement something along the lines of what you're suggesting but I prefer not to do it now.

In the meantime, you can workaround the problem:
```
# Middle argument
<is_permanent> && arg="--permanent"
echo mycmd <port> foo "${arg:-}" bar 

$ is_permanent: echo 'true false' | tr ' ' '\n'
$ port: echo '80 81 82' | tr ' ' '\n'
```

It's not very concise but it's an implementation over a simple, easy syntax.

Let me know if that covers your use case.

**Comment by kbknapp** [comment]
I totally understand that! The workaround kinda works (I didn't know you could have multiple lines of script), but still not perfect as the final command only evals the "${perm:-}" when not using navi's `--print`. I can live without this feature, it's ok, just wanted to propose it. And if it gets added in the future awesome :+1: 

Also, FWIW so long as navi's major version is increased I don't think breaking changes are a bad thing. I rarely assume a command line program to maintain full backwards compatibility across major version increases.

**Comment by denisidoro** [comment]
I think I'll implement the `--- --map <arbitraty code>` in the near future and mark it as *experimental* so that users will be aware that it may break at any moment.

Then, once we have more data on what would be an elegant API, we can revisit it. WDYT?

**Comment by denisidoro** [comment]
Some complexities arise, though.

Consider this case:
```
--- --map <arbitraty code> --column 2
```

Should we apply `--map` after or before `--column`?

**Comment by kbknapp** [comment]
> Then, once we have more data on what would be an elegant API, we can revisit it. WDYT?

Great! I think that's a good plan!

> Should we apply `--map` after or before `--column`?

I would say *after*. In my mind, the map is applied as the "final" step prior to being inserted into the command line. Reason being if map was applied before, why even use the `--column`? I can select a column as part of the map. However if it's applied *after* I can use `--column` to save some `awk`ing.
