### ISSUE TITLE
Variable dependency without using in script

### ISSUE THREAD

**Issue by plaip** [denisidoro/navi#329]
**Is your feature request related to a problem? Please describe.**
Declaring path variables:
```
$ repo: echo "/home/user/repo"
$ embedded: echo "$repo/embedded"
$ core: echo "$repo/core"
```
If I don't use it in "script" the variable dependency isn't working. 
NOT WORKING
`ls <embedded>`
> ls /embedded 
> ls: cannot access '/embedded': No such file or directory

WORKING
```
echo <repo> > /dev/null
ls <embedded>
```
> dir1 dir2 dir3

**Describe the solution you'd like**
I could have variable dependency  without using it in script.

**Comment by denisidoro** [comment]
I'm not sure I want to support it as it may be misleading / surprise the user if he/she isn't expecting this behavior. I'll need to think about it, ok?

In any case, a workaround is to "force" the use of both variables:
```bash
: <repo>; ls <embedded>
```

`:` is a no-op function in bash

**Comment by denisidoro** [comment]
The implementation for this is difficult, because unless I create a parser for bash that knows what variables are used, I'll need to eval all available `$...` lines. Given that they may be multi-option, that's a difficult problem.

**Comment by plaip** [comment]
Understood ! Can we imagine a another syntax for global variable? With `? ...` by example
```
? repo: echo "/home/user/repo"
$ embedded: echo "$repo/embedded"
$ core: echo "$repo/core"
```

**Comment by denisidoro** [comment]
That's a nice idea, but a line starting with `?` should contain a variable whose command generates a single option, right?

**Comment by plaip** [comment]
Yes, the start character could  be  `?` or another else.

**Comment by plaip** [comment]
Could you consider an implementation?

**Comment by denisidoro** [comment]
Yes! I like the idea you proposed. I can't give you a deadline for this, though. I've just changed jobs so I'll be busier than usual in the following days. 😅

**Comment by plaip** [comment]
NP :) Have fun in your new job

**Comment by denisidoro** [comment]
For future readers: I looked into the code to find a way to implement this and it seems too complex. The way `$ ...` lines are indexed now doesn't allow us to find all other `$ ...` lines that belong to the same category.

A trivial workaround would be to always add the `: <repo>;` part + simply change the display/rendering functions to hide this part using a regex.

I'll gladly accept a PR if anyone has some free time to implement it!
