### ISSUE TITLE
Panic when a comment or a tag is empty

### ISSUE THREAD

**Issue by mpasa** [denisidoro/navi#339]
**Describe the bug**

If a comment or a tag is left empty, Rust is panicking without giving a useful message. 

**To Reproduce**
1. Create a simple cheat file that is lacking a comment and save it in a folder `cheats`.

```
% tag

#
echo "Hello, World!"
```

2. Run `navi --path cheats`
3. Rust will panic with the following message:

```
thread 'main' panicked at 'byte index 2 is out of bounds of `#`', src/libcore/str/mod.rs:2131:9
```

**Expected behavior**
Parse empty comments or tags, or provide a better message error to the user.

**Versions:**
 - OS: Arch Linux
 - Shell Version: `fish, version 3.1.0` 

**Additional context**

On the current master, problems seem to be because comments and tags are supposed to be at least a character long. This can be checked on `parser.rs:173`.

```rust
else if line.starts_with('#') {
    if write_cmd(&tags, &comment, &snippet, tag_width, comment_width, stdin).is_err() {
        should_break = true
    }
    snippet = String::from("");
    comment = String::from(&line[2..]);
}
```

**Comment by denisidoro** [comment]
Thanks! I may add a check for that. But, out of the curiosity, what's the use case for this?

**Comment by mpasa** [comment]
Not a real use case. My cheatsheets were working on the bash version and not on the Rust one. Turned out to be an empty comment which shouldn't be there. In my opinion, the parser should panic with a more useful message in case like this, where the cheatsheet doesn't have a correct format.

**Comment by denisidoro** [comment]
Which one of these you think makes more sense?
1) panic
2) ignore that snippet
3) consider the snippet but without tag or comment

**Comment by mpasa** [comment]
Considering that both comments and tags are both quite important for navi, I would panic. But the current behavior if '#' or '%' are not set is to consider the snippet without tag or comment. So, in this specific case, I would do the same.
