### ISSUE TITLE
Improve support for Alfred

### ISSUE THREAD

**Issue by denisidoro** [denisidoro/navi#348]
- [ ] multiline snippets
- [ ] better handle `.bashrc`
- [x] variables without suggestions
- [ ] `--map` and `--column`
- [x] launch terminal for snippets with no effect otherwise

**Comment by perfectayush** [comment]
Hi, thanks for navi. I had a suggestion here, not sure sure if it's supported yet.
It will be helpful to copy the snippet in clipboard, and paste it in underlying application, instead of executing it (in terminal).

**Comment by lslz627** [comment]
> Hi, thanks for navi. I had a suggestion here, not sure sure if it's supported yet.
> It will be helpful to copy the snippet in clipboard, and paste it in underlying application, instead of executing it (in terminal).

you can add a output `Copy to Clipboard`, and settings `Automatically paste to front most app`, like this

![image](https://user-images.githubusercontent.com/18484770/92557071-fc020700-f29d-11ea-8853-9286db15e0d4.png)

**Comment by perfectayush** [comment]
@lslz627  Thanks, I can modify that. Checking if upstream workflow will support it. It would be great if I don't have to maintain this, other folks can use it as well.

**Comment by denisidoro** [comment]
@perfectayush did you manage to make it work? If so, would you mind opening a PR? I can then maintain it :+1:

**Comment by perfectayush** [comment]
@denisidoro the solution recommended by @Islz627 works. But it will break the existing terminal command workflow. I am not sure what would be the best way to do this in final terminal/else switch.

**Comment by denisidoro** [comment]
Unfortunately I don't have any metrics regarding **navi**'s usage but I bet that, relatively speaking, few people use this Alfred workflow (because it's experimental and hacky).

I'm OK with breaking changes if they are for the greater good.

**Comment by perfectayush** [comment]
@denisidoro I personally feel that best course would be to copy the command to clipboard and paste it in front most app. This is very useful for pasting the command in terminal or a text editor. This also allows for inspecting command before running it. Running it in terminal once evaluated or eval "$(snippet)" is probably not a great idea without user inspection.

From usage point of view, I have also added a hotkey in the beginning to initiate this workflow. I prefer `command + shift + ;`. But ppl can bind this to their own preference.

![image](https://user-images.githubusercontent.com/1427611/93247656-4575b900-f7ac-11ea-81af-9e6c133f8780.png)

I have exported the workflow, I will add a PR if this is acceptable.

**Comment by denisidoro** [comment]
Unfortunately, I'm dropping support for alfred in #509.

Reasons:
- it doesn't work as expected in many scenarios (cheats with `--map`, for example)
- Alfred code makes refactoring navi difficult
- if I decide to give a proper support for the Alfred workflow in the future, I'll need to rewrite the code from scratch, anyway
- I personally don't use the workflow anymore - instead, I'm launching an [alacritty](https://github.com/alacritty/alacritty) window with `dash -c navi` for low latency

Any additional info related to Alfred will be documented in [this page](https://github.com/denisidoro/navi/blob/master/docs/alfred.md).

I'm sorry for all navi+Alfred users out there!
