### ISSUE TITLE
Fix linting issues

### ISSUE THREAD

**Issue by denisidoro** [denisidoro/navi#349]
clippy complains:
```rust
   --> src/parser.rs:140:13
    |
140 |     writer: &mut Box<dyn Writer>,
    |             ^^^^^^^^^^^^^^^^^^^^ help: try: `&mut dyn Writer`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#borrowed_box
```

But in the [same file](https://github.com/denisidoro/navi/blob/master/src/parser.rs), the only way I could come up to assign to a variable a concrete `Writer` implementation is using `Box`:
```rust
    let mut writer: Box<dyn Writer> = if ... {
        Box::new(display::AlfredWriter { ... })
    } else {
        Box::new(display::FinderWriter { ... })
    };
```

I can't figure out a way to convert a `mut Box<dyn T>` into a `&mut dyn T`. Any ideas?

**Comment by denisidoro** [comment]
Nevermind. `&mut *writer` will do the trick. 🚧

**Comment by llogiq** [comment]
To completely get rid of the boxes, you can use deferred initalization and one variable per type as I explained on [my blog](https://llogiq.github.io/2020/03/14/ootb.html).
