### ISSUE TITLE
Option to append selection to commandline instead of replace

### ISSUE THREAD

**Issue by bdwiel** [denisidoro/navi#356]
I have some cheatsheets for partial commands. Like the history substitution command `!:$` to access the last argument of the previous command. I like to use `!:$` as an argument to a multitude of different commands. I have a cheat for `!:$` but navi replaces the start of command when I select this cheat. It'd be nice to have it appended to my command. Maybe pressing a shortcut instead of enter when making the selection.

I got this functionality to work by using this function based on [_call_navi()](https://github.com/denisidoro/navi/blob/master/shell/navi.plugin.zsh).  I have it bound to Ctrl+h but now there's one shortcut to start navi in replace mode and one shortcut to start in append mode. My preference would be one shortcut to start navi and then different keys to replace or append.

```sh
 # <C-H> to call navi and insert selection (not replace command)
_insert_navi() {
    local selected
    if selected="$(printf "$(navi --print </dev/tty)")"; then
        LBUFFER="$LBUFFER $selected"
    fi
    zle redisplay
}
zle -N _insert_navi
bindkey '^h' _insert_navi 
```

If you like this and point me to how to detect what's being pressed from within navi then I can make a PR.

**Comment by denisidoro** [comment]
What do you mean by "different keys [from within navi]"?

**Comment by denisidoro** [comment]
In any case, I guess that the current widget could be replaced by yours. I don't think there are many cases where insert > append.

**Comment by bdwiel** [comment]
I wasn't sure if there use cases for insert either. 

What I meant was if I start navi and type `git`. Then instead of pressing `enter` I press `Ctrl+g`. Where does navi process the `Ctrl+g` and decide how to react. This is where I'd made a change to append to the existing command. Is that clear? Changing the current widget is fine, too.

**Comment by denisidoro** [comment]
- https://github.com/denisidoro/navi/blob/master/src/finder/fzf.rs#L49
- https://github.com/denisidoro/navi/blob/master/src/flows/core.rs#L203

It would be somewhat ugly to implement this, because the rust binary would have to print some kind of metadata for the widget to know what to do.

I think we can replace the current behavior instead.

**Comment by denisidoro** [comment]
We just need to make sure that the behavior is the same for zsh, bash and fish. Implementing this for zsh is trivial but I'll probably need help with the other shells.

**Comment by denisidoro** [comment]
This has already been done for bash and zsh
