### ISSUE TITLE
Triggering edit on the current cheat file.

### ISSUE THREAD

**Issue by thepenguinthatwants** [denisidoro/navi#357]
Hi!

Is it possible to implement a way to trigger own editor on the current or even just a certain navi cheat file based on a keybinding?

Now feels quite cumbersome that it needs to separately navigate to those files before editing.

**Comment by denisidoro** [comment]
I'm not sure I'm following. Could you elaborate or explain it with different words?

Do you mean you would like a keybinding to directly edit a `.cheat` file?

**Comment by thepenguinthatwants** [comment]
I meant if when the navi prompt has being started then I can get the output from .cheat file.

It would be nice to get a keybinding that can triggger from the prompt to directly edit a predefined .cheat file.

**Comment by denisidoro** [comment]
Hi! Sorry for the late reply.

Being 100% honest here: this is a feature it would be nice to have but unfortunately I haven't had much free time lately, so I have no plans to implement this in the near future.

If anyone could submit a PR for this, I'll gladly accept it, though! 👍 

One workaround in the meantime for this is to set `$FZF_OVERRIDES` (please check README.md) with `--bind` and something like `vim $(_find {})` where `_find` is some command such as `rg` or `find` that's able to find a filename given the contents of the selected line.

**Comment by b3s1r** [comment]
Hi, I wanted to solve this but I just need some clarification:
So you want to bind a key to open one specific file
or a global binding to open the .cheat file of the selected entry?
I will start to implement the latter unless you have objections.

**Comment by thepenguinthatwants** [comment]
Hi,
global binding to open the .cheat file of the selected entry could make this tool more flexible but I guess u've implemented it already

**Comment by denisidoro** [comment]
Yes, it's implemented already. It's available on master but if you want to use it you'll need to build navi. In any case, I'll probably release a new version in December still

**Comment by thepenguinthatwants** [comment]
Is it possible to add keybinding reminders on the navi screen? Like ctrl+o is easy but could be nice if there is on top or bottom a quick tip bar that can be enabled.

**Comment by thepenguinthatwants** [comment]
Otherwise this is super nice feature :D and quick. Thanks!!!!
