### ISSUE TITLE
Navi path problem.

### ISSUE THREAD

**Issue by thepenguinthatwants** [denisidoro/navi#358]
I've added 

alias n="navi --path ~/.local/bin/navi"
alias navi="navi --path ~/.local/bin/navi"

both aliases into my bashrc.

When I trigger it by writing navi and then exit and n. I get

`error: The argument '--path <path>' was provided more than once, but cannot be used multiple times`

But using it as navi it works.
Also is it possible to use somekind of enviroment export  , to set a default path to navi cheats?

**Comment by denisidoro** [comment]
You can use `$NAVI_PATH`. Please check the README instructions for more details.
