### ISSUE TITLE
Put used cheat files near the start of the cursor

### ISSUE THREAD

**Issue by i30817** [denisidoro/navi#359]
**Is your feature request related to a problem? Please describe.**
I have to go up to the start of the commands listing to find the cheats on my new cheat file, starting from the bottom, and across all git repo added cheat files

**Describe the solution you'd like**
Much like zoxide, the default could be the most recently used first or something, but this looks ugly with a lot of categories and files on those categories. If there are single multiple of the same group catergory files as the last command, move *all files* of the same category to the  bottom, near the start cursor; with the one actually chosen moved to the very bottom.

**Describe alternatives you've considered**
The cheat files seems to be added by order of iteration of the dirs or something; just make sure that git repos are added first, then the rest of cheat files in the directories on the right dir that are not github from most recent to least, or alphabetic or something. I don't like this as much.

**Additional context**

**Comment by denisidoro** [comment]
> just make sure that git repos are added first, then...

What's your workflow? .cheats that are inside git repos are the ones you downloaded and all the other ones are written by you?

If that's the case, that's not valid for everyone. I, for example, push all my custom .cheats to https://github.com/denisidoro/dotfiles so this logic wouldn't hold.

Maybe I didn't get it right, though?

**Comment by i30817** [comment]
Yes, that's what i did. I don't really think it matters where the cheats come from, just that the last used / last group of the used cheat are near the cursor.

Anyway i completely understand if you don't want to keep a config file for this app to store the last used cheat/cheat group, so this is can be closed if you'd prefer not to. I meanwhile wrote some bash alias for making navi query easier to use.

**Comment by denisidoro** [comment]
I've been thinking about having a .navirc for some time now. A lot of issues could benefit from that :+1:

Could you share your bash aliases? Maybe that could give me some ideas

**Comment by i30817** [comment]
It's just some dumb thing to shorted the commands, just like zoxide:

```
alias zi="z -i"
alias za="zoxide add"
alias zq="zoxide query"
alias zr="zoxide remove"

source <(navi widget bash)
alias n="navi query"
alias na="navi"
```
Too dangerous to automatically add in short.

**Comment by i30817** [comment]
BTW, i'd recommend following the free desktop XDG standards instead of a free-floating dot file in home.

**Comment by denisidoro** [comment]
This will be tracked in https://github.com/denisidoro/navi/issues/489
