### ISSUE TITLE
Custom cheatsheet for fish command results in a bash "invalid option" error.

### ISSUE THREAD

**Issue by buster-blue** [denisidoro/navi#361]
**Describe the bug**
Trying to use the cheatsheet I've created for adding a new directory to PATH in fish results in bash giving an "invalid option" error.

**To Reproduce**
1. create the following cheatsheet, and import it:
```
% fish, environment_variable

# add a new directory to PATH in fish.
set -U fish_user_paths <directory_path> $fish_user_paths
```
2. make sure that fish is the current shell.
3. run navi and try to use the cheatsheet
4. After entering the directory argument, the output will be an error from bash.

**Expected behavior**
The command runs correctly through fish (my default shell) and adds the directory to PATH accordingly.

**Versions:**
 - OS: Fedora (Linux)
 - Shell Version: fish, version 3.1.2

**Additional context**
I'm using the cargo version with fzf. This is the actual error text that I get when I try to use the cheatsheet:
```
bash: line 0: set: -U: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
```

**Comment by denisidoro** [comment]
This happens because navi calls `bash -c "<cmd>"` internally, so this is not being called by fish.

You can either use the shell widget with Ctrl-g (check README.md) or we could support fish natively somehow.

**Comment by buster-blue** [comment]
The widget _does_ work, so I'll just do that for now, but an option to set the shell that navi calls (probably somewhere in ~/.config/navi/) would be cool, but I don't know how difficult it is to program something like that. Would that be considered its own issue, and this one would be closed?

**Comment by denisidoro** [comment]
Yeah, we simply need to load this config (from a file such as you mentioned or to have this per snippet in the `.cheat` file, which would make things more flexible) and change this line of code: https://github.com/denisidoro/navi/blob/master/src/flows/core.rs#L217

> Would that be considered its own issue[...]?
I think so. Or we could rename this issue.

**Comment by buster-blue** [comment]
I'll close this issue now, since a cheatsheet not working feels like a different issue from adding a way to change which shell is called by navi, but ultimately it's your call. I'm unfamiliar with the way github issues are supposed to work, so you know more here than me.
