### ISSUE TITLE
Use custom paths AND the default path

### ISSUE THREAD

**Issue by aserrallerios** [denisidoro/navi#362]
I wonder, how can I use the `--path` option to load the default folder and other folders?

Something like:
```
    navi --path '~/.cheats:<default_cheats_folder>'     # uses custom cheats
```

Is the `<default_cheats_folder>` available somewhere as a variable we could use?

**Comment by denisidoro** [comment]
It's not available as a variable at the moment.

However, it's always [data_dir](https://github.com/soc/dirs-rs#Features)`/navi`.

Does that cover your use case?

**Comment by aserrallerios** [comment]
Not sure if there's a way of getting the XDG folders in macos. Not that I'm aware of.

**Comment by denisidoro** [comment]
According to the link above, it's `$HOME/Library/Application Support`

**Comment by aserrallerios** [comment]
I mean, no way of getting it programmatically in a platform independent way.

Anyway, if you cannot think on something else or a new navi feature, I'll just set a platform dependent rule.

**Comment by denisidoro** [comment]
I could add a `navi path default-cheats` command. WDYT?

**Comment by aserrallerios** [comment]
Do you mean something like this?

```
    navi --path "~/.cheats:$(navi path default-cheats)"     # uses custom cheats
```

**Comment by denisidoro** [comment]
Yes

**Comment by aserrallerios** [comment]
Yeah, that'd be pretty nice :)

**Comment by shinzui** [comment]
Making the path configurable makes it easier to configure navi in Nix.

**Comment by denisidoro** [comment]
@shinzui, what path? The one that navi downloads `.cheat`s to by default?

Doesn't `$NAVI_PATH` cover you use case?

**Comment by shinzui** [comment]
> Doesn't $NAVI_PATH cover you use case?

That works. Thanks.

**Comment by aserrallerios** [comment]
What is supposed to be the right value for `$NAVI_PATH`? 

If the path it's empty, it works (shows downloaded cheats), if it points to `/Users/aserralle/Library/Application Support/navi/cheats` it doesn't.

```sh
❯ ls "/Users/aserralle/Library/Application Support/navi/cheats"
Kidman1670__cheats      caojianhua__MyCheat     chazeon__my-navi-cheats denisidoro__cheats      denisidoro__dotfiles    mrVanDalo__navi-cheats
```

**Comment by denisidoro** [comment]
At the moment, when using `$NAVI_PATH`, subfolders aren't taken into account.

I can change that in the next version (+ add `navi path default-cheats`).

In the meantime, you can separate different directories by `:`:
```bash
NAVI_PATH="$(find "$HOME/Library/Application Support/navi/cheats/" -type d | tr '\n' ':')" navi
```
