### ISSUE TITLE
line 28: cargo: command not found

### ISSUE THREAD

**Issue by dgfreemem** [denisidoro/navi#365]
After doing git clone on the repo I try to do make install and get the following error:
"scripts/make install
The final binary will be available at /usr/bin/navi...
/home/dan/navi/scripts/action: line 28: cargo: command not found
make: *** [Makefile:2: install] Error 127"

Am I missing som component not described in the installation instructions?
My distro is Ubuntu Budgie 20.04 (newly installed).

**Comment by denisidoro** [comment]
You need to install [cargo](https://doc.rust-lang.org/cargo/) first
