### ISSUE TITLE
Please don’t sort by length

### ISSUE THREAD

**Issue by lyy289065406** [denisidoro/navi#369]
```
; example.cheat
% example

# the 1st cmd
git xxx

# the 2nd cmd
git yyyyyyyyyyyyyyyyy

# the 3th cmd
git zzzzzzz
```

Now I input  `navi query example`,  The preliminary list likes this:

```
example     the 2nd cmd       git yyyyyyyyyyyyyyyyy
example     the 3th cmd        git zzzzzzz
example     the 1st cmd         git xxx
```

But I hope it likes this ：
```
example     the 1st cmd         git xxx
example     the 2nd cmd       git yyyyyyyyyyyyyyyyy
example     the 3th cmd        git zzzzzzz
```

I can't control the length of the command, if I have many commands ,  it will make me trouble to find it

**Comment by denisidoro** [comment]
navi itself doesn't control how sorting works. It uses fzf or skim under the hood.

Assuming you're using fzf (the default one), you can control this behavior by tweaking [$FZF_DEFAULT_OPTS](https://github.com/junegunn/fzf#layout):
```bash
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --no-sort" navi query example
```

**Comment by lyy289065406** [comment]
Thank you!

It's work when I append it to `.zshrc` : 

```
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --no-sort --reverse"
```

The `--reverse` is important
