### ISSUE TITLE
Create widgets for bash+zsh+fish

### ISSUE THREAD

**Issue by denisidoro** [denisidoro/navi#37]
Hitting `Ctrl-G` for example could start the script. 

When selecting an entry, instead of executing it, it could fill the prompt (similarly to ctrl-r).

This way the history will be kept clean and there will be the possibility to edit the command as you like. 

Edit: this is **done for zsh, bash and zsh** already!
Please refer to README.md.

![Widget](https://user-images.githubusercontent.com/3226564/65788699-03361080-e132-11e9-9e93-b2a4bc405bed.gif)

**Comment by denisidoro** [comment]
Problem: I don't know how to get input from user in a ZSH widget
Workaround: use fzf with `--print-query`

**Comment by denisidoro** [comment]
In case anyone is interested in trying it out (for ZSH):
```sh
navi_home="$(echo "$(brew --prefix)/navi" || echo "/opt/navi")"
source "${navi_home}/shell/widget.zsh"
# hit alt+g
```

**Comment by tfriedel** [comment]
this is cool! I would love to have this for the fish shell.

**Comment by adworacz** [comment]
Looks like this isn't working for navi installed via Linuxbrew:

```
zshrc:source:176: no such file or directory: /home/linuxbrew/.linuxbrew/navi/shell/widget.zsh
```

```
(19-09-26 10:48:13) <0> [~]
u662b1ab6f1175f % which navi
/home/linuxbrew/.linuxbrew/bin/navi

(19-09-26 10:48:15) <0> [~]
u662b1ab6f1175f % brew --prefix
/home/linuxbrew/.linuxbrew

(19-09-26 10:51:02) <0> [~]
u662b1ab6f1175f % brew info navi
denisidoro/tools/navi: stable 0.9.4
An interactive cheatsheet tool for the command-line
https://github.com/denisidoro/navi
/home/linuxbrew/.linuxbrew/Cellar/navi/0.9.4 (43 files, 107.9KB) *
  Built from source on 2019-09-26 at 10:31:23
From: https://github.com/denisidoro/homebrew-tools/blob/master/navi.rb
==> Dependencies
Build: fzf ✔

(19-09-26 10:51:13) <0> [~]
u662b1ab6f1175f %

```

**Comment by denisidoro** [comment]
@adworacz the path in the instructions were wrong. I've just updated it. Could you confirm if it's working now?

**Comment by adworacz** [comment]
I'll do you one better - instead of having the user embed the navi version into their .zshrc, it looks like we can use `brew --prefix navi` to handle things.

```
navi_home="$(echo "$(brew --prefix navi 2>/dev/null)" || echo "/opt/navi")"
source "${navi_home}/libexec/shell/widget.zsh"
```

That just worked for me, using the 0.9.4 version installed via `brew install denis.../navi`, (not HEAD).

**Comment by denisidoro** [comment]
- zsh: ✅ 
- bash: help needed!
- fish: help needed!

**Comment by aminehmida** [comment]
Just want to share [this question](https://unix.stackexchange.com/questions/213799/can-bash-write-to-its-own-input-stream) and [this one](https://unix.stackexchange.com/questions/82630/put-text-in-the-bash-command-line-buffer) from stackexchange

The second answer from the first question has an excellent detailed description of how to achieve this in Bash.

I hope this is helpful.

**Comment by denisidoro** [comment]
There's an initial version for a fish widget [here](https://github.com/denisidoro/navi/blob/master/navi.plugin.fish).

It doesn't allow editing the command before executing it, though.

Could anyone help me?
