### ISSUE TITLE
Navi cant find skim (after cheatsheet download)

### ISSUE THREAD

**Issue by matu3ba** [denisidoro/navi#371]
**Describe the bug**
After usage of `navi --finder 'skim'` a the cheatsheet is not called or opened, even though it was downloaded.

**To Reproduce**
1. Install navi + skim
2. `navi --finder 'skim'`
3. Browse for cheatsheet repos

**Expected behavior**
The error message should not be there, when navi is called with skim and some sort of instructions be given.

**Screenshots**
```
navi was unable to call fzf.
Please make sure it's correctly installed.
Refer to https://github.com/junegunn/fzf for more info.
```

**Versions:**
 - OS: Manjaro (Arch derivate)
 - Shell Version GNU bash, Version 5.0.18(1)-release (x86_64-pc-linux-gnu)

**Additional context**
Latest skim or version on crates.io yield the same behavior.

**Comment by denisidoro** [comment]
I'm not able to reproduce this locally :/

**Comment by denisidoro** [comment]
Out of curiosity: do you have fzf installed? If not, installing it "solves" the issue?

**Comment by matu3ba** [comment]
No, I did not install `fzf`. With `fzf` it works.

**Comment by denisidoro** [comment]
I'm still not able to reproduce it locally:

<img width="566" alt="Screen Shot 2020-08-07 at 10 30 11" src="https://user-images.githubusercontent.com/3226564/89650546-fe390600-d898-11ea-8fe7-57d9e6ed6155.png">

Could you share more info about your system/config?

**Comment by matu3ba** [comment]
@denisidoro I think this is a path issue from my side that was interacting in nontrivial ways with firejail sandboxing of my shell.
Sorry for your time, it works now. 👍

**Comment by pickfire** [comment]
Navi also cannot find skim by default but I need to specify `--finder`, is there a way to automatically fallback to skim if fzf is not found?
