### ISSUE TITLE
Use defined variables in cheat in another cheat

### ISSUE THREAD

**Issue by plaip** [denisidoro/navi#377]
### Is your feature request related to a problem?
In my cheats, I have duplicated variables (ie: path or helpers). 

**A.cheat** 
```
# Print variable content
echo <variable_a>
echo <variable_b>

$variable_a: foo
$variable_b: bar
```
**B.cheat** 
```
# Print variable content
echo "<variable_a> - <variable_b>"

$variable_a: foo
$variable_b: bar
```

### Describe the solution you'd like
Use a common or helpers cheat to declare all common variables between all cheats. 

**Common.cheat** 
```
# Declare all common variables in a this cheat.
$variable_a: foo
$variable_b: bar
```
**A.cheat** 
```
# Use a trigger word to include cheat in another cheat (ie: include or something else)
include  common.cheat

# Print variable content
echo <variable_a>
echo <variable_b>
```
**B.cheat** 
```
# Use a trigger word to include cheat in another cheat.
include  common.cheat

# Print variable content
echo "<variable_a> - <variable_b>"
```

Please feel free to comment this feature request if not clear.

**Comment by denisidoro** [comment]
Interesting. I like the proposed API. I'll try to implement when I have some time

**Comment by denisidoro** [comment]
One sidenote is that instead of including a `.cheat` I guess we could reference another cheatsheet by its tags.

Example:
```
% directories, common
$ picture_folder: echo "/my/pictures"

% directories, wallpapers
include directories, common

# Lists nature wallpapers
ls <nature_folder>

$ wallpaper_folder: <pictures_folder>/wallpapers
$ nature_folder: <wallpaper_folder>/nature
```

navi doesn't make any assumptions about how/where cheatsheets are stored so if we follow the `include somefile.cheat` we would introduce some limitations.

**Comment by plaip** [comment]
Good idea. Glad you consider an implementation for this feature.
