### ISSUE TITLE
Navi cheats for Navi itself

### ISSUE THREAD

**Issue by unknowledgeable** [denisidoro/navi#380]
I'm finding it amusing/ironic when I can't remember the commands for navi itself. Would be great to have navi cheats in the main repo by default instead of having to do `navi --help`.

**Comment by denisidoro** [comment]
Normally you shouldn't use too many different commands for navi. Could you explain your use-case?

I, for one, only use `navi` as-is and once in a while `navi best <query>`.

**Comment by unknowledgeable** [comment]
Just seeing as I use it for a cheatsheet for uncommon tasks that I don't feel the need to create aliases for, the uncommon task for adding new cheats from a repo escaped me. I fired up ctrl-g, as I've become accustomed to for things like weird git issues, expecting a reminder to do "navi repo browse" and to my surprise there wasn't anything there.

I feel it would be quite a good introduction on how to use and configure navi too.
