### ISSUE TITLE
Missing from Homebrew?

### ISSUE THREAD

**Issue by Boztown** [denisidoro/navi#39]
I can't find any record of Navi being a Homebrew package.

```
~/P/A brew update
Already up-to-date.

~/P/A/ brew install navi
Error: No available formula with the name "navi"
```

I search https://brew.sh/ for good measure.

The documentation doesn't say anything about a special formula, and I don't see a formula definition in the repo at first glance.

Am I missing something?

**Comment by Yiniau** [comment]
@Boztown `brew install denisidoro/tools/navi` will be fine

**Comment by denisidoro** [comment]
Oops, I had removed the install instructions without realizing. I've just added them back now.

In addition, I have a PR on homebrew to add the `navi` formula. It'll hopefully be merged later this week.

**Comment by Emigre** [comment]
This is a link to the mentioned PR

https://github.com/Homebrew/homebrew-core/pull/44514

The formula was finally not added in that PR, perhaps will be in the future it will be
