### ISSUE TITLE
Error when pressing enter with nothing selected

### ISSUE THREAD

**Issue by thatdude624** [denisidoro/navi#396]
**Describe the bug**
If you open navi, misspell a search and press enter, navi seems to crash with the following message:
```
Hey, listen! navi encountered a problem.
Do you think this is a bug? File an issue at https://github.com/denisidoro/navi.

Caused by:
    No more parts in `selections`
```

**To Reproduce**
1. Start navi (shell shortcut or bash script, either way works)
2. Enter random search text until no results show up
3. Press enter

**Expected behavior**
nothing (staying on the search screen as-is) would be preferred. I believe previously it would either silently exit or restart (clearing the search)? I don't quite remember. 

**Versions:**
 - OS: Manjaro Linux
 - Shell Version: GNU bash, version 5.0.18(1)-release (x86_64-pc-linux-gnu)
 - Navi version: 2.9.0

**Comment by denisidoro** [comment]
I've already fixed this bug but apparently there has been some regression in 2.9.0 😭 

I'll look into it, fix it in the next release and try to add a test so this doesn't come back.

Thanks for reporting.
