### ISSUE TITLE
As a Team we want to auto-refresh cheats from github repository

### ISSUE THREAD

**Issue by IvanVas** [denisidoro/navi#416]
**Is your feature request related to a problem? Please describe.**
If a team shares cheats then they periodically need to re-add the repo to refresh the cheat. 

**Describe the solution you'd like**
Auto-update of cheats from all added repos or a configured subset of repos.
Public repos will benefit as well if updated.

**Describe alternatives you've considered**
cronjob would do the job

**Additional context**

**Comment by denisidoro** [comment]
Do you normally import all cheat files from a git repository? If that's the case, this feature seems trivial from a UX standpoint.

I'm wondering what the expected behavior should be for repos which have been filtered, though. 🤔

**Comment by IvanVas** [comment]
Yeah, all of them.
I'm not aware of the filtering feature. Can you point me to the doc or code?

**Comment by denisidoro** [comment]
It's the UI that allows you to select which files you want to import

**Comment by denisidoro** [comment]
@IvanVas, I know it's not ideal, but could you let me know if https://github.com/denisidoro/navi/pull/417 covers your use case for the time being?

**Comment by IvanVas** [comment]
Great, thanks!
