### ISSUE TITLE
Navi not working with the fish shell

### ISSUE THREAD

**Issue by itmecho** [denisidoro/navi#419]
**Describe the bug**
When using `navi` with the `fish` shell, I get an error where `navi` is using invalid shell syntax

**To Reproduce**
1. start a `fish` shell
2. `navi --path ~/.config/cheats`

**Expected behavior**
Should see a list of cheats from the `~/.config/cheats` path

**Screenshots**
![screenshot](https://i.imgur.com/t9j0w8A.png)

**Versions:**
 - OS: Arch Linux
 - Shell Version [replace this text with the output of `fish, version 3.1.2`]

**Additional context**
https://github.com/denisidoro/navi/blob/6808dccf5c9d87d016734bbffe5779d35aaa70e5/src/cmds/core.rs#L101

**Comment by denisidoro** [comment]
Thanks for the report! I already have a fix in mind and I'll try to release a new version next week. I'm sorry for the trouble

**Comment by lamchau** [comment]
Homebrew is pretty frustrating for downgrading, here are the steps (last known version to work with `fish`is v2.10)

Steps for people in the future that need to do this:
```sh
# remove current version
brew uninstall navi

# find formula/bottle
# launches url
brew info --github navi

# from github url
# 1. locate version 
# 2. click 'History'
# 3. locate for the version from @BrewTestBot
# 4. click 'Commit' > 'View File' > Raw
# 5. fetch using `cURL`
curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/7c7f18795fac61747fe383d7c22ec183d5283362/Formula/navi.rb

# install older version
brew install navi.rb && rm navi.rb

# optional, pin until fix is known
brew pin navi
```

**Comment by itmecho** [comment]
@denisidoro No trouble! It's easy enough to drop into bash as a work around =]

**Comment by denisidoro** [comment]
Probably fixed by #421

**Comment by denisidoro** [comment]
I'll release a new version today. Please reopen this issue if it still doesn't work.

**Comment by lamchau** [comment]
thank you @denisidoro 🙏

**Comment by denisidoro** [comment]
The binaries are already available [here](https://github.com/denisidoro/navi/releases/tag/v2.12.1)

**Comment by LordMZTE** [comment]
This has been reintroduced in #498 by removing a check for the current shell (maybe accidental?).

**Comment by denisidoro** [comment]
I guess I need help to understand this. I removed the check because of #496

**Comment by denisidoro** [comment]
@LordMZTE, could you share your zsh + fzf/skim versions, please?

**Comment by LordMZTE** [comment]
sure thing.
```
❯ fzf --version
0.27.0 (19759ed)
❯ sk --version
0.9.4
❯ zsh --version
zsh 5.8 (x86_64-pc-linux-gnu)
❯ fish --version
fish, version 3.2.1
```
why is zsh important? I'm using fish.

**Comment by denisidoro** [comment]
Thanks!

Oops, I meant fish instead of zsh.

**Comment by mpasa** [comment]
These are the versions for me. In my case, the problem appears with the fish shell check.

```
~ λ fzf --version
0.27.0 (brew)
~ λ fzf --version
0.27.0 (brew)
~ λ fish --version
fish, version 3.2.2
```

**Comment by denisidoro** [comment]
![Screenshot_2021-04-15-18-23-43-112_com opera browser](https://user-images.githubusercontent.com/3226564/114940209-df234880-9e17-11eb-8f55-9b4ea6424716.jpg)

This is why unsetting SHELL works. If it's undefined, then it's sh. 

By default, when using fish, SHELL should be "fish", which triggers my hack. 

I still don't understand why the hack works for some people but doesn't for others. 

In any case, a fix for everyone would be to, inside navi, export SHELL to sh or bash, before calling fzf. 

I'll test it out tomorrow.

**Comment by denisidoro** [comment]
Reopening because I still haven't release a new version with the fix

**Comment by LordMZTE** [comment]
The issue has been fixed for me!

**Comment by mpasa** [comment]
Master is also working correctly for me now. Thank you!
