### ISSUE TITLE
Option "--path" not working on 2.12

### ISSUE THREAD

**Issue by moucho** [denisidoro/navi#420]
**Describe the bug**
Until now, I was using --path to set a folder in my computer where my own .cheat files were.
But since last update, 2.12, using "navi --path /some/dir" shows the basic menu, (more info, browse cheatsheets and download default cheatsheets)

**To Reproduce**
1. Create a basic .cheat file
2. Launch navi with: navi --path "/path/to/folder/where/the/file/is"
3. The file isn't loaded, default menu is shown

**Expected behavior**
It should show the loaded file entries

**Screenshots**

**Versions:**
 - OS: Manjaro Gnome
 - Shell Version: zsh 5.8

**Additional context**

**Comment by denisidoro** [comment]
Strange.. I'm not able to reproduce the problem

**Comment by denisidoro** [comment]
Could you `ls /path/to/folder/where/the/file/is`?

**Comment by moucho** [comment]
Upon futher review, if the path includes "/" at the end it will not work:
`navi --path /some/dir/`

Until now it worked. I removed it and now works as expected.

You can close the issue if this is how it should be. However, it may be advisable to add a note in the documentation IMO.

**Comment by denisidoro** [comment]
Ideally it should work regardless of a trailing slash or not. I'll try to fix it.

Thanks for reporting! 👍
