### ISSUE TITLE
[fish/bash/zsh]: Placeholder completions missing

### ISSUE THREAD

**Issue by lamchau** [denisidoro/navi#422]
**Describe the bug**
The original issue in #419 seems fixed, but I'm missing the placeholders when filling in my commands

**To Reproduce**
1. `navi` (completion should contain `<placeholder>`
2. Select command
3. Notice `<placeholder>:` is missing

**Expected behavior**
* `<placeholder>:` should appear
* Number of commands should be consistent (See **Additional context**)

**Screenshots**
### 2.12.1
```sh
> ./navi --version
navi 2.12.1
> ./navi                                                                                                                                                                             
~ normal  < 1/32 +S
» cal                                normal calendar        cal -B <before> -A <after>  ⠀

# after selecting `cal`
~   < 1/1 +S
»
```

### 2.10.0
```sh
> navi --version
navi 2.10.0
> navi 
~ normal  < 1/26 +S
» cal                                normal calendar        cal -B <before> -A <after>  ⠀

# after selecting `cal`
before:   < 0/0 +S
```

**Versions:**
 - OS: macOS
 - Shell Version: fish 3.1.2, bash 5.0.18, zsh 5.7.1

**Additional context**

I also noticed
* 2.12.1  shows 32 commands, completion shows 1/1
* 2.10.0 shows 26 commands, completion shows 0/0

maybe related to the bug?

**Comment by denisidoro** [comment]
Are you using skim?

**Comment by lamchau** [comment]
nope! 

```sh
> fzf --version
0.23.0 (brew)
```

**Comment by denisidoro** [comment]
I'm not able to reproduce the problem :(

Is there a `$ before: ...` line in your `.cheat` or is this variable free text?

**Comment by denisidoro** [comment]
Could you share your `.cheat` file?

**Comment by lamchau** [comment]
here's my `cal.cheat` 

```
% cal

# normal calendar
cal -B <before> -A <after>

# julian calendar
cal -j -B <before> -A <after>
```

**Comment by denisidoro** [comment]
I'm still not able to reproduce it. Do you mind running the following?
```
navi --version
bash --version
fish --version
uname -a
```

**Comment by lamchau** [comment]
```
navi 2.12.1
GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)
fish, version 3.1.2
Darwin laptop.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

**Comment by lamchau** [comment]
still unable to see the placeholders in anything after 2.10.0, not sure how I can help here

```
navi 2.13.0
GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)
fish, version 3.1.2
Darwin tracer.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
```

**Comment by denisidoro** [comment]
I really don't know how to investigate this 😢 

Are you a software developer? If so could try debugging this from your end to give me more input?

You just need to:
- install cargo via rustup
- add a bunch of `dbg!("reached line 42")` in the code, specially in https://github.com/denisidoro/navi/blob/master/src/cmds/core.rs

Hopefully this will help me narrow the root cause down

**Comment by lamchau** [comment]
i am! let me repro in a clean install on a parallels vm. it could be people don't use the parameterization to fill out commands very often (and use it more like `cht`

i have 2.10.0 pinned (which has always worked) and not later versions but will definitely help to try to help debug this more

**Comment by denisidoro** [comment]
Ok! Please let me know if I can be of any help

**Comment by lamchau** [comment]
@denisidoro let me know if this is any of use! the bug looks is maybe related to the rework around `prompt_finder`/`prompt_with_suggestions` (introduced in v2.11)? we can see from `dbg!` the value is there at least!

**v2.10** `src/cmds/core.rs`
```rust
let value = if let Ok(e) = env_value {
    e
} else {
    variables
        .get_suggestion(&tags, &variable_name)
        .ok_or_else(|| anyhow!("No suggestions"))
        .and_then(|suggestion| {
            let mut new_suggestion = suggestion.clone();
            new_suggestion.0 = replace_variables_from_snippet(&new_suggestion.0, tags, variables.clone(), config)?;

            prompt_with_suggestions(variable_name, &config, &new_suggestion, interpolated_snippet.clone())
        })
        .or_else(|_| prompt_without_suggestions(variable_name, &config))?
};
```

**v2.13** `src/cmds/core.rs`
```rust
let value = if let Ok(e) = env_value {
    e
} else if let Some(suggestion) = variables.get_suggestion(&tags, &variable_name) {
    let mut new_suggestion = suggestion.clone();
    new_suggestion.0 =
        replace_variables_from_snippet(&new_suggestion.0, tags, variables.clone(), config)?;
    prompt_finder(variable_name, &config, Some(&new_suggestion), variable_count)?
} else {
    prompt_finder(variable_name, &config, None, variable_count)?
};
```

<hr>

from my simplified `cal.cheat`:
```
% cal
cal -B <before> -A <after>
```

the verbose step by step (with 2 placeholders)
```
   Compiling navi v2.13.0 (/Users/lamchau/github/navi)
    Finished dev [unoptimized + debuginfo] target(s) in 3.37s
     Running `target/debug/navi`
```

we can see here `&variable_name` does show the text i'm expecting `before` but `~   < 1/1 +S (0)` shows that there's no placeholder

```
[src/cmds/core.rs:201] &variable_name = "before"
[src/cmds/core.rs:203] &env_value = Err(
    NotPresent,
)
~   < 1/1 +S (0)
»
```

```
[src/cmds/core.rs:201] &variable_name = "before"
[src/cmds/core.rs:203] &env_value = Err(
    NotPresent,
)
[src/cmds/core.rs:201] &variable_name = "after"
[src/cmds/core.rs:203] &env_value = Err(
    NotPresent,
)
~ 1  < 0/1 +S (0)
```

```
[src/cmds/core.rs:201] &variable_name = "before"
[src/cmds/core.rs:203] &env_value = Err(
    NotPresent,
)
[src/cmds/core.rs:201] &variable_name = "after"
[src/cmds/core.rs:203] &env_value = Err(
    NotPresent,
)
   November 2020         December 2020          January 2021
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa
 1  2  3  4  5  6  7         1  2  3  4  5                  1  2
 8  9 10 11 12 13 14   6  7  8  9 10 11 12   3  4  5  6  7  8  9
15 16 17 18 19 20 21  13 14 15 16 17 18 19  10 11 12 13 14 15 16
22 23 24 25 26 27 28  20 21 22 23 24 25 26  17 18 19 20 21 22 23
29 30                 27 28 29 30 31        24 25 26 27 28 29 30
                                            31
`

**Comment by denisidoro** [comment]
Thanks! This is very helpful!

While I debug it, would you mind pasting the output for the following command (assuming there are no credentials):
```sh
env | grep before
```

**Comment by denisidoro** [comment]
Also, could you share the output for `env | grep FZF`?

**Comment by denisidoro** [comment]
What if you run `FZF_DEFAULT_OPTS="" navi --finder skim`? Does it behave as expected?

**Comment by lamchau** [comment]
we're still is missing the placeholders with fish (but did the same with `bash` and `zsh`)

```fish
set -gx FZF_DEFAULT_OPTS ""
target/release/navi --finder fzf
```

here's my `FZF_DEFAULT_OPTS` before clearing
```
> echo "$FZF_DEFAULT_OPTS"
    --bind '?:toggle-preview'
    --bind 'ctrl-a:toggle-all'
    --bind 'ctrl-b:page-up'
    --bind 'ctrl-f:page-down'
    --bind '∆:preview-page-down'
    --bind '˚:preview-page-up'
    --bind 'ctrl-e:execute(echo {+} | xargs -o vim)'
    --bind 'ctrl-r:toggle-sort'
    --color=fg:#c2c2c2,bg:#000000,hl:#7ca4d3 --color=fg+:#eaeaea,bg+:#444444,hl+:#7ca4d3 --color=info:#c397d8,prompt:#eaeaea,pointer:#7ca4d3,marker:#bacb20,spinner:#c397d8,header:#e6c617
    --height=85%
    --info=inline
    --layout=reverse
    --multi
    --preview 'bat --style=numbers --color=always {} | head -500'
    --preview-window=:hidden
    --prompt='~ ' 
    --pointer='»' 
    --marker='✓'
```

and my `FZF_DEFAULT_COMMAND=rg --files --hidden --no-ignore-vcs`

> Thanks! This is very helpful!
> 
> While I debug it, would you mind pasting the output for the following command (assuming there are no credentials):
> 
> ```shell
> env | grep before
> ```

nothing shows up here:
```sh
> env | grep before
<EMPTY>
```

**Comment by denisidoro** [comment]
Interesting

I don't know if you're aware, but the variable name isn't included in the prompt anymore. It's in the preview window:

![Screen Shot 2020-12-21 at 16 53 15](https://user-images.githubusercontent.com/3226564/102816725-3efb6c80-43ad-11eb-95f7-d17b0e6c9fe4.png)


Your `FZF_DEFAULT_OPTS` is hiding the preview window, that's why you don't see `<before>: `

However, it should have worked when you set it to the empty string 🤔

**Comment by lamchau** [comment]
i ran into a new error with an empty `FZF_DEFAULT_OPTS` on the v2.13.0 tag, maybe i'm missing a migration step?

```
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ error: The subcommand 'preview-var' wasn't recognized                                                                                                                        1/9 │
│         Did you mean 'preview'?                                                                                                                                                  │
│                                                                                                                                                                                  │
│ If you believe you received this message in error, try re-running with 'navi -- preview-var'                                                                                     │
│                                                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by denisidoro** [comment]
You're using the version you built from master (>=v2.13.0), right?

Then, internally it's calling the system-level navi (<=v2.10.0), which doesn't contain the `preview-var` command.

Please try to make your local build be the system-level one, at least temporarily.

Something like `export PATH:/path/to/local/navi/target/release:$PATH`

**Comment by lamchau** [comment]
so having gone through a few different steps with my config, it looks like `--preview-window=:hidden` is the culprit here and doesn't play nicely with `navi`

i have this disabled by default because of large globs of code can slow down the experience

**Comment by denisidoro** [comment]
Alternativetly, you can add something like this to your `.bashrc` file:

```sh
alias navi='FZF_DEFAULT_OPTS="" navi'
```

**Comment by lamchau** [comment]
i use `navi` as a keybinding (`ctrl+g`), so we'd need to modify the widget then no?

also, is there a place for us within `navi` to delete out the preview flag as we parse `env`?

**Comment by denisidoro** [comment]
> i use navi as a keybinding (ctrl+g), so we'd need to modify the widget then no?
yeah. you can run `navi widget fish`, edit it accordingly and source it in your `.fishrc` directly

**Comment by denisidoro** [comment]
> also, is there a place for us within navi to delete out the preview flag as we parse env?

No, but given that navi requires this flag to be a certain value, it doesn't make sense to read it from `env`. I'll try to fix that in the next release.

**Comment by lamchau** [comment]
thank you so much for helping me figure this out! 

also, just noticed your comment 🤦‍♂️ 
> Your FZF_DEFAULT_OPTS is hiding the preview window, that's why you don't see \<before\>:

**Comment by denisidoro** [comment]
Related: https://github.com/denisidoro/navi/issues/447
