### ISSUE TITLE
Allow one to add entire cheatsheet repo rather than individual cheets

### ISSUE THREAD

**Issue by wwalker** [denisidoro/navi#424]
**Is your feature request related to a problem? Please describe.**

Just had to hold `Tab` for it to select 1829 cheats from denisidoro/navi-tldr-pages

**Describe the solution you'd like**

Allow `Tab` to be used in the repo browse list to select one or more repos to have all of their cheats to be added when `Enter` is hit

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by denisidoro** [comment]
This should already be possible in the latest version. What version are your using? (what's the output of navi --version?)

**Comment by wwalker** [comment]
Installed via 
```
cargo install navi
```
```
$ navi --version
navi 2.9.0
```

**Comment by wwalker** [comment]
I just installed 2.12.1.  I see that it will now allow importing the whole repo :-)
