### ISSUE TITLE
Invalid when command contains "^" 

### ISSUE THREAD

**Issue by lqy123000** [denisidoro/navi#43]
Add command `ls -lR|grep '^-'|wc -l` to a cheat file and choose it. Error info "No valid cheatsheet!"

**Comment by denisidoro** [comment]
Actually I don't know how to solve this... :(

Due to bash limitations, I need to use a delimiter to return "multidimensional" values in my fns. I chose `^` as delimiter. Note: emojis or hidden characters won't do the trick because sed/grep/tr will fail.

Any ideas?
