### ISSUE TITLE
请求是否能加 "$" 变量的 一个 注释

### ISSUE THREAD

**Issue by myliwenbo** [denisidoro/navi#431]
例如

$ name:  zhangsan #张三
 
张三为注释.. 表示 zhangsan 选项的解释

**Comment by myliwenbo** [comment]
类似于

$ mapped: echo 'false true' | tr ' ' '\n' --- --map "declare -A map=(["true"]="01" ["false"]="02") | echo ${map["$0"]}"
其实我想取出 true 然后作为 key 去筛选 这样我就可以定义注释了..

**Comment by denisidoro** [comment]
Hi! Could you please try translating it to English?

I tried using Google Translate but the output didn't make much sense.

---------------

嗨！ 您可以尝试将其翻译成英文吗？

我尝试使用Google Translate，但是输出没有太大意义。

**Comment by myliwenbo** [comment]
example：
I want to determine by return value  
```shell
$ mapped: echo 'one two three' | tr ' ' '\n' --- --map "declare -A map=(["one"]="01" ["two"]="02" ["three"]="03") | echo ${map["$0"]}"
```
The above example does not output the correct result
The result I want, but the output is empty

**Comment by myliwenbo** [comment]
I expect that comments can be defined for options

I can use it as a note

Sorry my english is not good.... :)

**Comment by myliwenbo** [comment]
![image](https://user-images.githubusercontent.com/29202248/96742733-d0725080-13f5-11eb-8e3f-0cf0714a05aa.png)
So I can know what my options mean

------------------------------------------------------------------------------------------------------------------------------------

Similar to this

![image](https://user-images.githubusercontent.com/29202248/96742965-0ca5b100-13f6-11eb-8b74-d55d04dc9050.png)

**Comment by denisidoro** [comment]
You could try the following:

```bash
# Issue example
echo <foo>

$ foo: echo -e 'key;description\none;1\ntwo;2\nthree;3' | column -t -s';' --- --column 1 --header-lines 1
```

<img width="265" alt="Screen Shot 2020-10-21 at 13 38 17" src="https://user-images.githubusercontent.com/3226564/96750789-c115e780-13a2-11eb-9570-881b54e52694.png">

**Comment by myliwenbo** [comment]
thank

**Comment by myliwenbo** [comment]
That's pretty cool
