### ISSUE TITLE
Improved Documentation (or a ZSH Widget Issue)

### ISSUE THREAD

**Issue by CharlesARoy** [denisidoro/navi#432]
Hello, I'd like to take advantage of the kinds of features that appear in the following images (shown on the GitHub home page for Navi). E.g. having Navi show up below the cursor, and so on. However, I'm not finding any documentation on what option this would be or how to set it up. 

If this is the shell widget in action, I have added `eval "$(navi widget zsh)"` to my .zshrc file and sourced it. On my Mac this had no effect. On a CentOS Linux server I use, this resulted in CTRL+g working to launch Navi, but Navi still looks the same as when launched by simply typing "navi". 

![image](https://user-images.githubusercontent.com/46253001/97235263-bc38a580-179f-11eb-8b2d-a49e254ce4f7.png)

![image](https://user-images.githubusercontent.com/46253001/97235302-d1adcf80-179f-11eb-8d8c-45fa310781e2.png)

**General Information about My Setup:** 
On both my Mac and Linux Os I am using the ZSH shell with powerlevel10k enabled. 
I installed navi via brew and navi is version 2.12.1

**Mac Info:**
MacOS Catalina version 10.15.7

**Linux Info:**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"

Typing "navi widget zsh" produces the following on both platforms:
```
#!/usr/bin/env zsh
_call_navi() {
  local selected
  if [ -n "$LBUFFER" ]; then
    if selected="$(printf "%s" "$(navi --print --fzf-overrides '--no-select-1' --query "${LBUFFER}" </dev/tty)")"; then
      LBUFFER="$selected"
    fi
  else
    if selected="$(printf "%s" "$(navi --print </dev/tty)")"; then
      LBUFFER="$selected"
    fi
  fi
  zle redisplay
}

zle -N _call_navi

bindkey '^g' _call_navi
```

**Comment by denisidoro** [comment]
Try setting this in your `.bashrc`-like file:
```
FZF_DEFAULT_OPTS="--height 70% --reverse --inline-info --cycle"
```

**Comment by CharlesARoy** [comment]
Awesome! That worked on both the Linux server and my Mac. Thanks!

Two follow-up questions:
1) CTRL+g isn't working on my Mac, despite having the `eval "$(navi widget zsh)"` in my .zshrc file.
2) What's going on in the second image I posted? Why is the descriptive box off to the right and how can I set up my widget to look like that?

**Comment by denisidoro** [comment]
1. did you try changing the binding to see if the error persists? Maybe from `ˆg` to `ˆl` for example

2. It's the variable suggestion preview window. Example:

```bash
# Preview example
cat "<with_preview>"

$ with_preview: ls --- --column 1 --preview-window 'right:50%' --preview '[ -d {} ] && ls {} || cat {}'
```

**Comment by CharlesARoy** [comment]
Ok, should have tried this first, but a simple reinstall did the trick. 

Thanks for all the help!

**Comment by CharlesARoy** [comment]
Strangely enough `^g` is not working again. 

I've tried changing the key binding as you suggested previously, but when I run `navi widget zsh` the keybinding isn't actually changed. 

I've been modifying the keybinding in the `.navi/shell/navi.plugin.zsh` file. Is there another file where I need to change the keybinding so that it actually gets updated?

**Comment by denisidoro** [comment]
Sorry for the late reply.

Did you manage to make it work?

> Is there another file where I need to change the keybinding so that it actually gets updated?
If you change `.navi/shell/navi.plugin.zsh` then you need to recompile the binary
What you can do is to add the contents from `navi widget zsh` directly into your `.zshrc` and adjust it accordingly

**Comment by CharlesARoy** [comment]
Ok, I tried adding the following to my .zshrc file and sourced it (testing both ^g and ^t as the keybindings) but it's still not working. 

![image](https://user-images.githubusercontent.com/46253001/99478732-ca469580-2909-11eb-9876-a4fd17d5f881.png)

**Comment by denisidoro** [comment]
The only way to debug this is if you sent me your full `.zshrc`. Would you mind?

For example, if you call `bindkey` somewhere, then the keybindings may be reset.

Have you already tried adding `eval "$(navi widget zsh)"` at the very end of your `.zshrc`?

**Comment by CharlesARoy** [comment]
Ah, perfect, you clued me in to the source of the issue. A long time ago I had set bindkey -v to use the Vim keybindings and that was messing with the Navi Widget. 

You wouldn't happen to know of a way to use the Navi keybindings in conjunction with Vim keybindings would you?

**Comment by denisidoro** [comment]
@CharlesARoy I myself use the keybindings in conjunction with Vim keybindings 👍 

You only need to make sure to add `eval "$(navi widget zsh)"` after `bindkey -v`
