### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by minioin** [denisidoro/navi#434]
**Describe the bug**
Update the examples shown in navi help. Most the examples shown don't work anymore.

**Comment by denisidoro** [comment]
Hi! Could you highlight what examples don't work anymore?

**Comment by minioin** [comment]
For the examples shown in ``navi --help``

- ``navi search docker``
```
This version of navi doesn't support searching for cheats online.
Please check https://github.com/denisidoro/navi/issues/201 for more info.

You were probably using the bash implementation of navi and are now using the Rust one, which isn't feature complete yet.
In the near future, the Rust version will have all previous features.

I'm sorry for the inconvenience.
```

Similar response for 
- navi best 'sql create db' root mydb

**Comment by denisidoro** [comment]
What version are you using? Have you tried upgrading to the latest version (2.13.0)?

**Comment by minioin** [comment]
I was using 2.9.0. Upgraded version still gives error on ``navi 'create db' --best-match``, for example.
```
error: Found argument 'create db' which wasn't expected, or isn't valid in this context

USAGE:
    navi [FLAGS] [OPTIONS] [SUBCOMMAND]

For more information try --help
```
