### ISSUE TITLE
Print Command to Command Line When Using Navi

### ISSUE THREAD

**Issue by CharlesARoy** [denisidoro/navi#435]
When running commands with Navi, all you see on the command line is "navi" and then the output of the command but you don't see the actual command that was run. For having a record of the processing steps were performed on some files it would be really helpful if Navi echoed/printed the actual command as it was constructed within Navi. 

How would one modify the cheat sheet so that Navi first prints a copy of the command to the command line before running it?

**Comment by denisidoro** [comment]
You may want to use https://github.com/denisidoro/navi/blob/master/docs/installation.md#installing-the-shell-widget

**Comment by CharlesARoy** [comment]
Hmm, I'm under the impression that I'm already using the widget. In this gif, you can see that after selecting and running a command, all that's left is the word "navi" (and the error) but the command itself isn't shown. 

![2020-11-17 18 44 16](https://user-images.githubusercontent.com/46253001/99477148-c402ea00-2906-11eb-8cfd-88a7f1477e36.gif)

**Comment by denisidoro** [comment]
If you're typing `navi` by hand, you're not using the shell widget.

The shell widget is invoked by `Ctrl-G` (or other custom keybinding)

**Comment by CharlesARoy** [comment]
I see. Now that I fixed the issue of not being able to call the Navi Widget (due to having Vim keybindings activated) I am now able to see the commands before executing them when using the Widget. Thanks so much!
