### ISSUE TITLE
Accessing Local Files while Using Navi Widget

### ISSUE THREAD

**Issue by CharlesARoy** [denisidoro/navi#445]
It seems that when the Navi widget is being used, it isn't possible to access the local files as you complete a given command. For example, in the image below, if I want to use "checksum_comet_sub.txt" as the first input, I can't start typing the file name and then tabbing to complete. It also seems like the Navi widget disables highlighting so that I can't highlight and copy the filename while I'm in the widget. Thankfully, by using a clipboard manager (e.g. Copy'em), I can copy several items before loading the Navi widget and then paste them, but if a fix for this is possible that would be much more convenient. 

![Navi_issue](https://user-images.githubusercontent.com/46253001/102274731-31d80c80-3ed9-11eb-9fae-c530917b69b8.png)

**Comment by denisidoro** [comment]
Sorry, I'm afraid I don't understand what you mean. Could you share your `.cheat`?

Anyway, this works for me:

```sh
# create backup
cp "<local_file>" "<local_file>.bak"

$ local_file: ls .
```

<img width="1521" alt="Screen Shot 2020-12-15 at 18 40 40" src="https://user-images.githubusercontent.com/3226564/102276178-361a1f00-3f05-11eb-9251-5cdb2df84592.png">
<img width="330" alt="Screen Shot 2020-12-15 at 18 40 52" src="https://user-images.githubusercontent.com/3226564/102276185-374b4c00-3f05-11eb-9152-6edc328b67ea.png">

**Comment by CharlesARoy** [comment]
Oh interesting, so as you start typing, the red arrow shows local files that match what you've typed? If so, I probably didn't set up my cheat file properly, because when I start typing the red arrow disappears. For example, despite the files checksum.txt and checksum_comet_sub.txt being present in the current directory, after typing "check" there are no suggested files and the red arrow is gone.

![image](https://user-images.githubusercontent.com/46253001/102278323-7619db80-3ede-11eb-90f1-da32c5d4c368.png)

Here's my (abridged) cheat file:
[custom.cheat.txt](https://github.com/denisidoro/navi/files/5698934/custom.cheat.txt)

**Comment by denisidoro** [comment]
*navi* doesn't know anything about variables: it ignores if they are files, folders or usernames. You need to tell it what `checksum_list_1` is. If you add the following to your `.cheat` then you'll have the result you're expecting:

```
$ checksum_list_1: ls .
```

**Comment by CharlesARoy** [comment]
Beautiful! Thanks so much for the help!

**Comment by CharlesARoy** [comment]
After adding `ls .` to a number of cheatsheet variables and referencing other cheatsheets where possible, Navi has started running really slowly. There's often a ~10-second delay when I get to a command that invokes an `ls .` variable. It's not due to having a ton of files to list in the current directory and runs slowly even if there are just a few. When I run `ls .` outside of Navi the files in the current directory are listed instantaneously. 

Here's a more complete version of my cheat file. Do you see anything problematic with it? 

[custom.cheat.txt](https://github.com/denisidoro/navi/files/5699372/custom.cheat.txt)

**Comment by denisidoro** [comment]
Hmmm everything seems correct in your `.cheat`

I'll investigate this next week to see what's causing this slowdown, ok?

**Comment by CharlesARoy** [comment]
Ok, today it's actually working with only a very slight lag. It might have been due to a slow connection with the remote server where I'm running Navi, though I would have expected that to affect running ls outside Navi too. Anyway, looks good for now. Thanks for all the help!
