### ISSUE TITLE
invalid preview window layout: up:2:nohidden

### ISSUE THREAD

**Issue by Fruitjeus** [denisidoro/navi#447]
**Describe the bug**
Typing command `navi` results in:
```
invalid preview window layout: up:2:nohidden
invalid preview window layout: up:2:nohidden
invalid preview window layout: up:2:nohidden
[1]    25537 segmentation fault  navi
```

**Versions:**
 - OS: [WSL (version 2) - Ubuntu 20.04]
 - Shell Version [zsh 5.8 (x86_64-ubuntu-linux-gnu)]

**Comment by denisidoro** [comment]
What's the value of `fzf --version`?

**Comment by denisidoro** [comment]
Could you try upgrading fzf to check it the problem is resolved?

**Comment by Fruitjeus** [comment]
Hi denisidoro, for some reason, the installed fzf version was 0.20.0. I have updated fzf to version 0.24.4 (00a3610) and am happy to report navi works as expected. Thanks!

**Comment by denisidoro** [comment]
I'm glad it worked but I'm afraid many users will face this problem...

I'll leave this as open for a while to see the impact.

**Comment by denisidoro** [comment]
➡️ *SOLUTION* ⬅️ 
Upgrade fzf using your main package manager

**Comment by ThatOtherAndrew** [comment]
APT thinks that the latest version of fzf is 0.20.0 and I can't update it to anything newer, could someone help me with what I'm doing wrong?

**Comment by Fruitjeus** [comment]
Package in APT repository is indeed out of date. I ended up installing from source, following these steps: https://github.com/junegunn/fzf#using-git

**Comment by ThatOtherAndrew** [comment]
Yep, that worked, thank you!
