### ISSUE TITLE
Support for multiline formatted preview of code snippet

### ISSUE THREAD

**Issue by m42martin** [denisidoro/navi#449]
**navi --version 2.9.0
WSL2 on Windows 10 2004 19041.685
Ubuntu 20.04
Windows Terminal Preview**

I'd like be able to preview multiline snippets so that they appear as multiline, formatted, and possibly with syntax coloring related to the language.

I haven't found a way to display the code snippet as a multiline block in the preview.  If this is already possible, I would appreciate suggestions or an example illustrating how this should be configured.

![image](https://user-images.githubusercontent.com/16886205/103291982-e0d91580-49ba-11eb-8d9a-dd88fb9bb1d7.png)

Here's the content of the .cheat file that is selected in the image above:
```
% throw, expression, syntax, c#, cs, .net

# Throw expression within property

string Name \
{ \
	get name; \
	set => name = value \
	  ?? throw new ArgumentNullException(nameof(name)); \
}
```
navi arguments
```
navi --print \
 --finder 'skim' \
  --fzf-overrides '--nth 1,2,3 --no-exact --case smart --multi --height 15 --layout=reverse-l
ist --margin=2,4 --inline-info --ansi --preview-window=right:42%:wrap --with-nth 2,3'
```

I tried numerous ways of calling `skim` but none have resulted in a clean and formatted preview.

I thought it might be possible using [bat](https://github.com/sharkdp/bat) or [prettybat](https://github.com/eth-p/bat-extras/blob/master/doc/prettybat.md) with skim's `--preview` option.

e.g., `--preview bat {3}` 

![image](https://user-images.githubusercontent.com/16886205/103293254-7ecddf80-49bd-11eb-8031-857e0870a599.png)

I've seen `: command not found` in the preview output from many variations that I've tried.

When wrapping the preview command in quotes, or providing inline arguments to a command, other issues arise

`--preview "prettybat {3}"` or `--preview "prettybat --language cs {3}"`
```
/bin/bash: -c: line 0: unexpected EOF while looking for matching `"'                                               /bin/bash: -c: line 1: syntax error: unexpected end of file
```

While this works by piping the cheat file into awk, replacing `\` with `\n`
```
awk '{ gsub(/\\/, "\n", $0); print }'  file.cheat
```
Doing the same within the fzf-overrides results in the 'unexpected EOL' error

 `--preview awk "{ gsub(/\\/, "\n", {3}); print $0; }"'` 

I suspect that's a problem with skim, or not escaping quotes or surrounding the expression correctly.

**Comment by denisidoro** [comment]
Thanks for the suggestion!

Interesting use case! I never thought about using navi for code snippets!

You can't override the preview behavior for snippets - only for variables.

I've quickly put [a code](https://github.com/denisidoro/navi/pull/450) together to simulate what you want:
![Screen Shot 2020-12-29 at 17 55 06](https://user-images.githubusercontent.com/3226564/103313770-dbea8500-49ff-11eb-8c4e-bb1dbad5b1b0.png)

Does this look like what you expected?

That said, in case I decide to support this, this would require a syntax change or something like that. This use case is completely different than what navi was originally designed for.

Maybe the `.cheat` could have something indicating what programming language the snippet is written in?

As a final note, to assess how much effort I want to put into this: have you considered alternatives that are best suited for your use case? [VSCode snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets) or [cheat.sh](https://github.com/chubin/cheat.sh), for example. If you have, what are the advantages of using navi?

**Comment by m42martin** [comment]
Yeah that looks great!

What if navi cheat files could use markdown style code blocks to define both the language, and a boundary for the multiline block?  Would that give you enough to know how tall the preview window would need to be?  

` ```cs`
```cs
foreach (var item in items)
{
  // ...
}
```
` ``` `

As for arguments for or against adding this to navi...  Naturally, I'd like to see at least the multiline option.  Syntax highlighting is cherry on top, but not as big of a value-add as the formatting.

I haven't tried cheat.sh (I'll take a look), and don't use VS Code often enough, but I'm nearly always in a shell.

**Comment by denisidoro** [comment]
Yeah, I like the markdown syntax.

It wouldn't help with dimensions, though. As soon as I start the fzf/skim process I need to give it the preview-window dimensions. They can't be changed for each input line.

Do you intend to use this for vim? If so, I've found some vim snippet solutions online. Maybe you could give them a try and see what works best.

**Comment by m42martin** [comment]
I wasn't planning on calling navi from inside vim.  I work with visual studio mostly, then code, and occasionally vim when.  Shell is the one constant regardless of the project though.

Doesn't fzf and skim allow defining the preview height?

I'd be happy with passing the height as an argument to navi and then just crop off text if the height isn't large enough.  Isn't the same thing happening now with the variable and tag column widths?

_btw, I opened a pull request of the cheats repo to include my repo of cheat files._

**Comment by denisidoro** [comment]
But where do you paste this C# code if not inside an IDE or vim?

**Comment by m42martin** [comment]
I work with visual studio mostly.  On rare occasions I use vs code or vim.  Honestly I hadn't though about copy pasting the snippet.  That's even cooler.  

I was thinking that these snippets would be handy for quick, visual reminders.  

But sending the snippets to the clipboard would be pretty cool too.

**Comment by denisidoro** [comment]
You could use something like `navi --print | clip.exe` and paste it in Visual Studio.

**Comment by denisidoro** [comment]
Closing because this feature is not in the roadmap at the moment.

Please see https://github.com/denisidoro/navi/pull/450 for more info.

**Comment by aemonge** [comment]
Doesn't this already works ?

```
     % tag1, tag2
     
     # hello world in python
     
     ```python
     print("hello")
     print("world")
     ```
```
