### ISSUE TITLE
Navi config location

### ISSUE THREAD

**Issue by DanielRivasMD** [denisidoro/navi#458]
Hi. Love this tool. But I want to customize it a bit more without changing the source code. Specifically `navi widget` keybindings. I cannot find documented anywhere where the configuration is located. Any help? Much appreciated. Cheers.

**Comment by denisidoro** [comment]
There's no way to configure (e.g. via yml, json or env vars).

What you can do is to run `navi widget bash` (assuming you use bash), copy the output, paste it into your `.bashrc`, edit the code accordingly and then remove the `navi widget bash` from your `.bashrc`

**Comment by DanielRivasMD** [comment]
Thanks for your answer. Get it. I'll do that. Cheers
