### ISSUE TITLE
Display and add to bash history full command after execution?

### ISSUE THREAD

**Issue by niksfirefly** [denisidoro/navi#462]
Is there a way to display and add to bash history full command with variables after execution?

regards

**Comment by denisidoro** [comment]
Yes: https://github.com/denisidoro/navi/blob/master/docs/installation.md#installing-the-shell-widget

**Comment by niksfirefly** [comment]
Thx i missed it
Is there a way to run bash widget with custom options for example --path?
Run multiple widgets with --paths and different shortcut Ctrl+N Ctrl+P etc.

regards

**Comment by denisidoro** [comment]
Not out-of-the-box, no. What you can do is run `navi widget bash` just to get its output, copy it, edit it accordingly and paste in your `.bashrc` file
