### ISSUE TITLE
Best match workflow

### ISSUE THREAD

**Issue by enisozgen** [denisidoro/navi#463]
Hello Denis,

I created some workflow for navi to make it easy to use. I am sharing it here
maybe it can give you some idea.

## Merge different navi outputs

As I remember correctly at first versions of navi was able to write complex one
liners by connecting with PIPE. Like navi_output1 | navi_output2. Actually it
was nice feature to piping different outputs. Maybe, you can consider to bring it
back.

## Best Match

Navi mostly offers correct command with `--best-match` parameter. By using this
feature I wrote some kind of fast auto complete. In that way it allows us to
press less keys also it does not show fzf UI.

## Code is here 
Works well with zsh

- https://gist.github.com/enisozgen/2109cc80ea9f405f80c6c383f2375e77

## GIF is here 
![smart_navi](https://i.imgur.com/CM0Io4j.gif)

Regards,
Enis

**Comment by denisidoro** [comment]
Awesome! If you don't mind I'll update the current widgets to include this.

Also, did you feel any feature missing when writing this?

You mentioned that old versions had a support of some sorts for piping. Not sure what you meant there.

Please let me know if I can help.

**Comment by denisidoro** [comment]
I'll probably write this in Rust and have thin wrappers in bash+zsh+fish.

Also, instead of having the "target" command as something that is after the last pipe, it would be nice to have it smart enough to understand `&&`, `||`, `>`, etc.

I'll try to come up with something.

**Comment by enisozgen** [comment]
Happy to see good response!! 

I was meaning this related with pipe.

![gif](https://user-images.githubusercontent.com/3226564/67864139-ebbcbf80-fb03-11e9-9abb-8e6664f77915.gif)

**Example:** I copied this from one of old README. On those times navi was
understanding pipes. After writing `ls -la |` + **CTRL+G**, we were able to
produce `ls -la | tail -n2` but now it's not possible.



Also you talked about many operator like `&&, ||, >,`. If you ask me how many
times that I wrote `&&` or `||` operator while writing one-line bash it's not
much!

Absolutely this is my opinion but writing if(with || or &&) else statements in
one line is not making us productive! Bash can be powerful but human brain is
not so capable about it. It's better to write those operators in sh file. As you
say, If navi just query with the text after last pipe, it can be great again and
It's enough for many cases.


## One more feature request 
You asked for another missing feature I'll use this chance :)

This will be hard but, After pressing CTRL + G I always see the commands which I
never(or rarely) use! It can be really nice, If navi keep track for which commands has been
used as [fasd](https://github.com/clvv/fasd) command so it will offer most used
commands on top.

**Comment by denisidoro** [comment]
### old behavior
Actually, the old widget ignored the input completely and suffixed the command line with the output from navi. That's why it "supported" pipes haha.

### && and ||
Good point. In any case I'll need to write a more advanced interpreter in order to ignore `|`s which are inside strings, for example. So it's a small step to supporting other operations.

### most used commands
Implementing the frecency algorithm is straightforward, if I use https://github.com/camdencheek/fre as reference. What's difficult is that, unless I come up with something advanced, navi will need to have all cheats in memory, then print the frecent ones, then print the remaining ones. This will make the code more complex and maybe there's gonna be a delay between starting navi and seeing the first cheat. I'll take a look at it.

**Comment by denisidoro** [comment]
Your shell widget is now included (with some modifications) in the latest release of navi. Thanks again, @enisozgen!

Sorting by frecency will be tracked in https://github.com/denisidoro/navi/issues/489

**Comment by MushiTheMoshi** [comment]
is this possible in bash?

**Comment by denisidoro** [comment]
Yes. It's possible in zsh and bash. 

It isn't possible (yet) in fish and other shells

**Comment by MushiTheMoshi** [comment]
I'm sorry, I see that it should work as a widget, but how does the interpolation happens when he did "git all" and then it replaces with "git add -A", I mean what is the navi component making that possible ?

**Comment by enisozgen** [comment]
Hello @MushiTheMoshi


Pseudo is like that,

1. I wrote `git all` # Keep this input  as environment variable

   - First interraction with widged

2. Input (LBUFFER) > Navi `--best-match` > Output (`git add -A`)


3. This is not the command what I want so I call one more time widged(Second interraction with widged)

   1. https://gist.github.com/enisozgen/2109cc80ea9f405f80c6c383f2375e77#file-smart_navi-zsh-L112 

4. Input(Previous environment variable) > Call navi without --best-match by using TUI > Replace `git add -A` with new selected output(You can check the `ChangeLastCommand` )  > Output (`git submodule update --init --recursive`)

**Comment by MushiTheMoshi** [comment]
Oh many thanks! I see so it's a pipeline, thank you so much for helping me to understand this!
