### ISSUE TITLE
The demo is about 5x faster than it should be

### ISSUE THREAD

**Issue by gerrywastaken** [denisidoro/navi#475]
**Describe the bug**
The demo gif is about five times faster than would be needed for a human to figure out what is happening. This speed is fine now that I know how Navi works, but the speed was is crazy for when I was first trying to understand what Navi did. First having to look at every part of every frame and then work out what it's trying to show was not even close to impossible. It might also be ok if browsers had video controls on gifs, but they don't :(

**To Reproduce**
1. Be completely new to Navi
2. Go to https://github.com/denisidoro/navi#navi---
3. Try to follow the GIF

**Expected behavior**
The gif progresses at a pace that works for new users without having to load externally in mpv or some other tool

**Screenshots**
![94310428-fff58080-ff4f-11ea-8c1c-29fac351340a](https://user-images.githubusercontent.com/71481/113574932-022e4b00-9615-11eb-988b-32798c407ff6.gif)

**Comment by denisidoro** [comment]
What do you think about this one?

[![asciicast](https://asciinema.org/a/n5OP3oW5cNThdwhCGx8jbVQ7T.svg)](https://asciinema.org/a/n5OP3oW5cNThdwhCGx8jbVQ7T)

**Comment by gerrywastaken** [comment]
Wow, awesome work! Thank you for that.

However, putting myself into the head space of a new user...

I first see you run `demo 0` which is a bit confusing (however I get it, although I'm wondering if this would work: https://github.com/sloria/doitlive)

On the next screen I'm watching the part that's moving and completely ignoring the heading above assuming it's just part of the command prompt, which upon pausing I think this is the main part you wanted me to see. I think a lot of presentations make sure to type out descriptions they want people to see.

Upon pausing it become apparent how you wish me to view the video. However at the start it really seems to be diving in at the deep end and more focused on configuring navi than an intro for somebody completely new. It does seem to become more of an intro at 29 seconds, but perhaps you could start with that? I think the first part is fantastic for people who already know what Navi is and want to take their use to the next level.

The fact that it's now in a format that allows pausing is much better than before. I hope this doesn't come across as critical. I just figured you've probably spent a lot of time on Navi and so I wanted to be honest in the hope it helps your project become even more successful.

**Comment by denisidoro** [comment]
I've updated it once more. Please let me know what you think

**Comment by gerrywastaken** [comment]
That is sooo perfect :heart: :clap:

**Comment by denisidoro** [comment]
Thank you for the suggestions!

**Comment by ngirard** [comment]
> I've updated it once more. Please let me know what you think

Great demo !
