### ISSUE TITLE
How the demo works like "fix commands"?

### ISSUE THREAD

**Issue by kondongx** [denisidoro/navi#491]
![image](https://user-images.githubusercontent.com/28899471/114295393-8ed67e80-9ad7-11eb-96a9-65c583f1bd98.png)

What show I do when finish "remove first line" then get "tail -n +2"?

**Comment by denisidoro** [comment]
Given that you have a cheatsheet that contains the following:
```sh
% text

# remove first line
tail -n +2
```

And you're using navi 2.15.0+ and configured the [shell widget](https://github.com/denisidoro/navi/blob/master/docs/installation.md#installing-the-shell-widget), you simply need to press Ctrl+G.

**Comment by kondongx** [comment]
I got it! Thanks.

**Comment by notDavid** [comment]
> Sidenote: the fish widget currently doesn't have as many features as the ones for bash and zsh.

@denisidoro Hi there, so could you clarify whether the [example](https://github.com/denisidoro/navi/issues/491#issuecomment-817277740) you mention in the comment above, where the `remove first line` text gets replaced with `Ctrl+G` currently does or does not work in fish, and `navi 2.18.0` ?

Thank you!

**Comment by denisidoro** [comment]
fish still doesn't support this smart "widget"

fish could totally support it, though. It's just that I'm not familiar with fish scripting.

If anyone could translate the bash/zsh widgets to fish, that would be awesome!

**Comment by notDavid** [comment]
@denisidoro Thanks. I created an issue for clarity so people know, and perhaps someone can fix it… :-)

**Comment by vivekragunathan** [comment]
> > Sidenote: the fish widget currently doesn't have as many features as the ones for bash and zsh.
> 
> @denisidoro Hi there, so could you clarify whether the [example](https://github.com/denisidoro/navi/issues/491#issuecomment-817277740) you mention in the comment above, where the `remove first line` text gets replaced with `Ctrl+G` currently does or does not work in fish, and `navi 2.18.0` ?
> 
> Thank you!

Did you get this working? I am on 2.18.0 and does not work. Hitting `Ctrl+G` looks like it attempts to run something but moves to a new prompt. In this case, I have `tail -n +2` defined in a cheatsheet, and `navi --query remove` lists the cheat.

**Comment by notDavid** [comment]
> Did you get this working?

No, the "smart replace" functionality does not work in fish shell yet, see the open issue: https://github.com/denisidoro/navi/issues/648#issue-1066297980

**Comment by funkyfisch** [comment]
I don't wanna open any other issues so I'm posting here:
Is there a way to make navi behave by default the way it behaves in the ctrl+g? As in running navi, picking a command, and that then appearing right after my prompt, ready to be executed when I press enter. I start suspecting that this is impossible - can someone redirect me to any resource explaining why it isn't possible to do so?

**Comment by alexis-opolka** [comment]
Hi @funkyfisch , sorry for the late answer but you can look at those issues: #903 #945 #953 .
These issues might give you a way to do your own implementation on what you want to do.
