### ISSUE TITLE
Wrong filename for installed cheats

### ISSUE THREAD

**Issue by DRogueRonin** [denisidoro/navi#492]
**Describe the bug**
I'm not sure whether that's a bug or intended.
Cheatsheets seem to be working but the path at the end of the installation seems wrong.

**To Reproduce**
1. `brew install navi`
2. `navi`
3. Install default cheatsheets
4. See error as in screenshot

**Expected behavior**
The filename should be `ci_cd__fly.cheat` or `ci_cd/fly.cheat` not `__Users__dweipert__Library__Application Support__navi__cheats__tmp__ci_cd__fly.cheat`

**Screenshots**
![Bildschirmfoto 2021-04-11 um 10 13 05](https://user-images.githubusercontent.com/16617893/114299877-df40e280-9abd-11eb-8784-bf18ffb3dcf6.png)
![Bildschirmfoto 2021-04-11 um 11 57 00](https://user-images.githubusercontent.com/16617893/114299881-e10aa600-9abd-11eb-8fc2-8458d2679aec.png)

**Versions:**
 - OS: macOS
 - Shell Version zsh 5.3 (x86_64-apple-darwin18.0)

**Comment by denisidoro** [comment]
Oops, thanks for repirting.

I have recently refactored this code and I must have messed it up. 

In the next release this will fixed.
