### ISSUE TITLE
Preview window for variables not working on fish shell

### ISSUE THREAD

**Issue by mpasa** [denisidoro/navi#496]
**Describe the bug**

The preview is not working if we detect that the current shell is fish. The behaviour is as expected
running on bash, if the SHELL variable is not set to `fish`, but it can be reproduced the same way
setting manually the environment variable.

**To Reproduce**

1. Start a fish shell. Check that the SHELL environment variable contains the substring `fish`
2. Create a new cheat file with a simple variable, or reuse an existing one. For example: `kubectl drain <name>`
3. Run navi and select the previous cheatsheet.
4. At this point, you are prompted to introduce the value for the `name` variable, with a description of it in the fzf preview window. Instead, we see the preview as:

    ```
    error: The argument '<selection>' requires a value but none was supplied
    USAGE:
      navi preview-var <selection> <query> <variable>
    ```

**Expected behavior**

No error should be thrown, and the preview window should work as expected.

**Screenshots**

![image](https://user-images.githubusercontent.com/5392207/114311934-1086d600-9af1-11eb-85b9-36a7e2ad1dcc.png)

Same navi version, using bash:

![image](https://user-images.githubusercontent.com/5392207/114311961-30b69500-9af1-11eb-8a3b-39d2610c0693.png)

**Versions:**
 - OS: Ubuntu (5.4.0-70-generic)
 - Shell Version: fish, version 3.2.2

**Comment by denisidoro** [comment]
What happens if you run navi after `unset $SHELL`?

**Comment by mpasa** [comment]
Running `set --erase SHELL` works as expected (no error). I see the code is adding a `bash -c` if it detects it's a fish shell. The code inside is invalid fish though (`$(code)` for example), so I'm not sure how it works without it.

**Comment by denisidoro** [comment]
I'm confused. The behavior should be the opposite.

Anyway, thanks for the report. I'll look into it during the week..

**Comment by LordMZTE** [comment]
Hey, I'm getting this error as well. [This is my fish config](https://github.com/LordMZTE/dotfiles/blob/master/fish/config.fish) in case it helps to reproduce this.

**Comment by mpasa** [comment]
The command args I'm getting are:

```
"fzf" "--preview" "" "--preview-window" "up:2:nohidden" "--with-nth" "1,2,3" "--delimiter" "  \xe2\xa0\x80" "--ansi" "--bind" "ctrl-j:down,ctrl-k:up" "--exact" "--select-1" "--print-query" "--no-select-1" "--preview" "bash -c \'navi preview-var \"$(cat <<NAVIEOF\n{+}\nNAVIEOF\n)\" \"$(cat <<NAVIEOF\n{q}\nNAVIEOF\n)\" \"name\"; \'" "--preview-window" "up:4"
```

**Comment by denisidoro** [comment]
In the PR above, I'm removing the custom behavior for fish.

However, I added the custom behavior in the first place because it didn't use to work without it.

I wonder if fzf changed its behavior. I would need to test with an old fzf version to be sure.

**Comment by denisidoro** [comment]
Please follow up on #419

**Comment by mpasa** [comment]
@denisidoro Thank you. Maybe something to take into account is whether this behaviour changes between the default `fzf` and `sk`. I will check that.
