### ISSUE TITLE
navi-git AUR package seems to not use newest git version

### ISSUE THREAD

**Issue by LordMZTE** [denisidoro/navi#500]
It looks like the [navi-git aur package](https://aur.archlinux.org/packages/navi-git/) does not seem to be using the newest commit from this repo.
in the `PKGBUILD` file there is a hard-coded commit sha:
 ```sh
pkgname=navi-git
pkgver=r305.cc8982f # <-- version hard-coded here
pkgrel=1
pkgdesc='An interactive cheatsheet tool for the command-line.'
rch=('any')
url='https://github.com/denisidoro/navi'
license=('Apache 2.0')
# -- snip --
```

as far as I understand, these `-git` packages should all use the newest commit from the git repo, and not use any specific version like this.

**Comment by denisidoro** [comment]
I'm not the author of this package. @Kibouo, could you give some instructions on how to change this, please?

**Comment by Kibouo** [comment]
`*-git` packages are always up to date with the specified branch and do not require changes to the PKGBUILD unless the installation instructions change.

See AUR capable package manager's `--devel` flag to update `-git` packages.

https://wiki.archlinux.org/index.php/Arch_User_Repository#What_is_the_difference_between_foo_and_foo-git_packages?

**Comment by LordMZTE** [comment]
> `*-git` packages are always up to date with the specified branch and do not require changes to the PKGBUILD unless the installation instructions change.
> 
> See AUR capable package manager's `--devel` flag to update `-git` packages.
> 
> https://wiki.archlinux.org/index.php/Arch_User_Repository#What_is_the_difference_between_foo_and_foo-git_packages?

I understand this, however I thought this package contained a hard-coded version, but it seems like I was mistaking. I cloned the package and downloaded its sources, and it looks to be up to date with the current git version, so this was my mistake. Sorry!
