### ISSUE TITLE
Prepopulate variable

### ISSUE THREAD

**Issue by KillTheMule** [denisidoro/navi#501]
**Is your feature request related to a problem? Please describe.**
I have a dependent variable, but before running the cheat I need to edit it. 

**Describe the solution you'd like**
I have 2 variables "basis" and "variant", where "basis" is selected via fzf. Say "basis=V100.master". Now I will want to execute "mv V100.master V101.master", but I need to choose the target name case by case. Whe using "mv <basis> <variant>" in the cheat, that would work out, but I'd really like to not type out "V101.master" for the variable "variant", but prepopulate the input line with "V100.master" so I can just edit it. Of course, my real use case involves much longer names and pathes.

**Describe alternatives you've considered**
I could generate a list of candidates for "variant", but I will invarantly run into problems when the candidates don't fit (which will be often enough to make this not useful). I could leave "variant" empty and type the whole value, but that will end up too much work.

Maybe there's already a way to do it, but I've not found it. Thanks for any help :)

**Comment by denisidoro** [comment]
Possible workarounds:

### Workaround 1
1. Have a cheatsheet with a command such as `mv <myfile> <myfile>`
2. Use the [shell widget](https://github.com/denisidoro/navi/blob/master/docs/installation.md#installing-the-shell-widget)
3. Call the snippet accordingly
4. Edit the command before running it

### Workaround 2
1. Install navi 2.15.2+ (I haven't released it yet)
2. Have a cheatsheet with a command such as `mv <myfile1> <myfile2>` and `$ myfile2: echo $myfile1; echo other stuff --- --fzf-overrides bind=ctrl-u:replace-query
3. Use the shell widget or invoke navi
4. Select `myfile1`
5. Press `Ctrl-u`
6. Edit the value
7. Press tab

**Comment by KillTheMule** [comment]
Hey I didn't realize the shell widget does this, nice! So 1 is already good, and 2 will be a slight improvement which I'm looking forward to (since I won't have to type the file extension by hand). Thanks a lot!
