### ISSUE TITLE
Support install without sudo permissions?

### ISSUE THREAD

**Issue by quadebroadwell** [denisidoro/navi#51]
Is it possible to have an install route without the need for sudo?

**Comment by UchihaSR** [comment]
shall i take this issue?

**Comment by denisidoro** [comment]
@UchihaSR feel free! But I still don't know what path we should use in this case

**Comment by alxbl** [comment]
@quadebroadwell if you use oh-my-zsh, checkout the PR that I submitted yesterday, it will let you use navi as a widget without having to do a system-wide install.

Alternatively, you can just `git clone navi` and manually set your `PATH` to include navi's directory in your dotfiles.

```sh
# .zprofile or similar
export PATH="$PATH:/path/to/navi/repo"
```

You can then manually update using `git pull`.
