### ISSUE TITLE
Deploy to AUR

### ISSUE THREAD

**Issue by gunar** [denisidoro/navi#52]
Would love to have this on Arch's User Repository ([AUR](https://aur.archlinux.org/)).

Let me know if you want me to write and maintain a git-based MAKEFILE for you ([example](https://aur.archlinux.org/packages/reredirect-git/)).

**Comment by denisidoro** [comment]
Hi! Unfortunately, I'm not sure if I can commit myself to go down the path of maintaining packages for multiple package managers (besides brew).

That said, I would really appreciate if someone could maintain it! :)

**Comment by wallace11** [comment]
[There you go](https://aur.archlinux.org/packages/navi/), wish granted.

Note to dev:
Current installation method makes it extremely clumsy to package. 
I recommend using standard `make` procedures instead of a custom script. Launcher script could live as a file in the repo - I had to create one from the installation script.

Anyways, thanks for this great useful tool. I hope to contribute some PRs in the near future, as time allows :)

**Comment by gunar** [comment]
Thanks @wallace11!

**Comment by denisidoro** [comment]
For reference, https://aur.archlinux.org/packages/navi-bin/ has been created with a newer version.

Ideally, we should keep https://aur.archlinux.org/packages/navi/ only but I don't know if that's possible.

**Comment by wallace11** [comment]
I was hoping you'd give me enough time to reply on the AUR pkg comments. 
@denisidoro Are you itmecho on AUR? If that's the case, then I can make you a co-maintainer over there. 

Anyways, I'm out of town for about a week and won't be able to do anything in the meanwhile. Please hold on as I'll take care of everything as soon as I get back.

**Comment by denisidoro** [comment]
@wallace11, no problem! Take your time!

No, I'm not itmecho. But I found him/her on Reddit if that's useful: https://www.reddit.com/r/rust/comments/fgzifj/-/fkasq7d

**Comment by itmecho** [comment]
Hi @wallace11 ! I'm itmecho everywhere =] 

I created `navi-bin` to provide the precompiled binary as an option for people who just want the binary without the dependency on rust and the compile time. The `navi` package should remain as the compiled from source version. This seems to be a common pattern, for example [starship's](https://github.com/starship/starship) AUR packages. Would you agree that it's fine to keep both of these AUR packages to give people the option?

I'm happy to make you a co-maintainer on the `navi-bin` package as well if you want!

As @denisidoro said though, I'm in no rush so take your time =]

**Comment by itmecho** [comment]
I have a PKGBUILD for the `navi` package which I took from starship and updated for navi which you're more than welcome to take a look at if you want

**Comment by denisidoro** [comment]
Just to let you know, the `.cheat` files and the shell widgets aren't bundled anymore. The executable binary is the only resource needed. The deployment process for AUR may be different now.

**Comment by itmecho** [comment]
Nice! That makes it much easier

**Comment by wallace11** [comment]
Okay, so I've just caught up with all the changes. 
I see navi has been rewritten from scratch in rust, which makes the shell version obsolete, I guess?

@denisidoro do you plan to keep supporting the shell version or at least offer it as an alternative to the "v2" rust version? Maybe some people would prefer v1 over there newer version?
Depending on your answer, we'll have to decide whether to keep the current navi package and rename it to something like `navi-v1` or completely update it to follow the newest version, and perhaps maybe rename the package to `navi-git` (I'll have to recheck the AUR guidelines to make sure it justifies the change). 

@itmecho I'll make you a co-maintainer probably tomorrow. Let's decide what to do based the the answer to my question above. 

Cheers.

**Comment by denisidoro** [comment]
@denisidoro I don't plan to support the bash version anymore. It's full of bugs, it's startup time is 10, 25-fold compared to the rust one, and it's very difficult to maintain.

Each rust release contains binaries for 5 different targets, so it should cover most cases. 

If anyone wants to use the bash version, they can download the v1.0.0 tag release.

(Just to be clear, ideally I would like to maintain both versions, but I can't :disappointed:)

**Comment by itmecho** [comment]
Thanks @wallace11!

How does this sound:
`navi` - v2 compiled from source
`navi-bin` - v2 precompiled binary
`navi-bash` - v1 bash version

That way, the main `navi` package is what you'd expect it to be but people who want the old "unmaintained" version can still get it via the specific bash package.

**Comment by wallace11** [comment]
@itmecho 
Sounds good.
The only thing I'm concerned about is that having too many packages could become a burden and also confuse users. We should at least add a short description in brackets. For instance, "An interactive cheatsheet tool for the command-line (bash v1 unmaintained version)".

You're already a co-maintainer on the `navi` package, so you can go ahead and update everything, and also add yourself to the description. If something comes up, I'll contact you via email. 
As you probably know, the whole world has gone crazy and as a result my response is always late.

Thanks.

**Comment by itmecho** [comment]
Thanks @wallace11! Yea, good idea. 

I'll set that up now and then we can close the issue.

**Comment by itmecho** [comment]
OK, this is done now!

There are 3 packages:
```
aur/navi 2.3.0-1 (+2 0.92%)
    An interactive cheatsheet tool for the command-line
aur/navi-bash 0.18.3-1 (+0 0.00%)
    An interactive cheatsheet tool for the command-line (Unmaintained v1 bash version)
aur/navi-bin 2.3.0-2 (+1 0.89%)
    An interactive cheatsheet tool for the command-line
```

I've added @wallace11 as a maintainer on `navi-bin` and `navi-bash`. As far as I'm concerned, this issue can be closed!
