### ISSUE TITLE
What is the license of the image in README.md?

### ISSUE THREAD

**Issue by kai2nenobu** [denisidoro/navi#532]
First of all, `navi` is an awesome tool and thanks to your work ❤️ 

I'm creating a [chocolatey](https://chocolatey.org/) (package manager for Windows) package for `navi` [here](https://community.chocolatey.org/packages/navi/2.15.1) to simplify the installation for Windows users. A chocolatey package can have an icon and the icon is displayed in the top-left corner on the package page.

[![image](https://user-images.githubusercontent.com/810042/115428353-46d4fb80-a23d-11eb-92df-88ef8df2a07e.png)](https://community.chocolatey.org/packages/navi/2.15.1)

I would like to use the following image in README.md as the package icon. ![icon](https://user-images.githubusercontent.com/3226564/65362934-b4432500-dbdf-11e9-8f75-815fbc5cbf8f.png)

However, this image is not tracked in `navi` repository, and its license is unclear. So, my question is what is the license of the image and can I use it?

**Comment by denisidoro** [comment]
I myself created it from scratch using an online drawing tool. Unfortunately, I don't have the SVG file anymore. I believe I could "recover" it from the PNG using some tool, though.

Versioning the SVG would be enough? (Considering that this repo is licensed under Apache2)

**Comment by denisidoro** [comment]
Btw, thanks for creating the package for chocolatey! I don't use a Windows machine so it's difficult for me to track if navi is misbehaving in Windows, etc. So feel free to open any issues you see necessary.

**Comment by kai2nenobu** [comment]
[In the chocolatey guideline](https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines), PNG is the preferred format as icon image.  I think versioning the PNG image is enough.

**Comment by denisidoro** [comment]
- https://raw.githubusercontent.com/denisidoro/navi/master/assets/icon.png
- https://raw.githubusercontent.com/denisidoro/navi/master/assets/icon.svg

**Comment by kai2nenobu** [comment]
Thanks a lot! I use the PNG icon in my chocolatey package.
