### ISSUE TITLE
Navi collapses multiple newlines into a single newline

### ISSUE THREAD

**Issue by knpwrs** [denisidoro/navi#539]
**Describe the bug**

Navi collapses multiple newlines into a single newline.

**To Reproduce**

Consider the following snippet to compose a commit message with a co-author:

```
% Git

# Commit with co-author
git commit -m "$(cat <<EOF
<commit_message>

<co_author>
EOF
)"

$ co_author: git log --pretty="%an <%ae>" | sort | uniq | sed 's|^|Co-authored-by: |g'
```

I expect the following to be populated to my shell:

```
git commit -m "$(cat <<EOF
My awesome commit message

Co-authored-by: User <user@example.com>
EOF
)"
```

Instead, the following is populated to my shell:

```
git commit -m "$(cat <<EOF
My awesome commit message
Co-authored-by: User <user@example.com>
EOF
)"
```

The newlines between the first line of the message on the `Co-authored-by` line are collapsed into a single newline.

**Versions:**
 - OS: macOS 11
 - Shell Version GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

**Comment by denisidoro** [comment]
Interesting use case, but I'm afraid multi-line snippets will never be reliable. If one of the lines between the EOFs start with `#`, navi will think a new snippet is starting. 

Anyway, consecutive newlines get collapsed because navi ignores empty lines.

Considering empty lines is tricky because it's not clear where snippets. I guess I could right trim them, though.

**Comment by knpwrs** [comment]
I managed to get something that works for my use case (i.e., pre-populating [co-authors](https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) for git commit messages based on authors in the current repo).

Feel free to close this issue if newlines aren't going to be supported.

For anyone reading this issue looking for a similar snippet, my solution is very `git`-specific (it doesn't actually solve the newlines issue outside of `git` snippets):

```
% Git

# Commit with co-author
git commit -e -m "<commit_message>" -m "<co_authors>"

$ co_authors: git log --pretty="%an <%ae>" | sort | uniq | sed 's|^|Co-authored-by: |g' --- --multi
```

I found out through [this answer on StackOverflow](https://stackoverflow.com/a/5070502/355325) that you can pass multiple `-m` flags to `git`, and git will automatically put a blank line between each message passed to each subsequent `-m`. The snippet above expands to the following:

```
git commit -e -m "Blah blah blah" -m "Co-authored-by: user1 <user1@example.com>
Co-authored-by: user2 <user2@example.com>"
```

This works for me in `zsh` and results in the following commit message:

```
Blah blah blah

Co-authored-by: user1 <user1@example.com>
Co-authored-by: user2 <user2@example.com>
```

The `-e` flag also opens `$EDITOR` or `$GIT_EDITOR`, giving you the opportunity to modify the commit message. You can remove `-e` if you'd like to just commit directly from the shell. Alternatively, if you would like to compose your commit message in your editor rather than navi you can change the snippet to the following:

```
% Git

# Commit with co-author
git commit -e -m "commit message" -m "<co_authors>"

$ co_authors: git log --pretty="%an <%ae>" | sort | uniq | sed 's|^|Co-authored-by: |g' --- --multi
```

My `$EDITOR` is set to `vim`, so from there I can just press `cc`, compose my message, and not have to remember full names and emails for my co-authors!

**Comment by denisidoro** [comment]
Nice!

I intend to make navi not ignore blank lines in near future, but multi-line snippets will always have some caveats, as you said.

Regarding workarounds, there are a multitude of ways to build multi-line strings. Example:

```
# Echo multiline
git commit -am "$(echo -e "<foo>\nlorem ipsum\n<bar>")"

$ foo: ls
$ bar: ls
```

**Comment by knpwrs** [comment]
I could have sworn I tried `echo -e` but it wasn't working for me. Just tried it again and it works 🤦🏻 .
