### ISSUE TITLE
Chaining commands

### ISSUE THREAD

**Issue by dgengtek** [denisidoro/navi#543]
**Is your feature request related to a problem? Please describe.**
I was thinking about how chaining could be done for calling navi multiple times from the shell prompt(eg bash with ctrl-g from the default navi widget bash binding).

Example:

User decides he wants to pipe output to the input of another command so he does another call to navi which leaves the expanded output from 1. unchanged including the pipe and appending the output from the second call

**Describe the solution you'd like**
1. I was thinking this could be either done by changing the widget so that a special string would indicate that a chain of commands is desired by the user like

`$ <command from first call> | navichain `

in this case `navichain` would only be expanded instead of like it is now that the last command is also replaced with the output from the navi call.

2. An addtional widget which would loop and let the user select commands until the selection is empty and either output all selections chained together by a pipe character(or by option with another separator) or give the output of the selections to the users $EDITOR separated by newlines so that the user can edit the result before executing it. 

Something like this

```
  _navi_widget_loop() {
    output=()
    while :; do
      selection=$(_navi_call --print)
      if [[ -z "$selection" ]]; then
        break
      fi
      output+=("$selection")
    done
    result=$(printf '%s\n' "${output[@]}" | vipe)
    
    READLINE_LINE="${READLINE_LINE}$result"
    READLINE_POINT=${#READLINE_LINE}
  }
```

3. Just add an additional widget for the respective shells which does no replacements but only appends the output to the prompt

What do you think? Personally I have 3. in my bashrc

```

  _navi_widget_append() {
      READLINE_LINE="${READLINE_LINE}$(_navi_call --print)"
      READLINE_POINT=${#READLINE_LINE}
  }
  # alt+s
  bind -x '"\es": _navi_widget_append'
```

Not sure how useful others find this or if this is a desired feature since at this point one would probably just add the chained command to a cheatsheet for reuse.

**Comment by denisidoro** [comment]
Thank you for the suggestion!

Unfortunately, I haven't managed to wrap my head around it. 

Could you explain the use case? In what scenarios do you append commands?

**Comment by dgengtek** [comment]
Sometimes I do an api call or if I tail some logs, stream whatever I have some snippets saved which manipulate the input to my desired output. 

`$ tail -f <somestream>`

I decide I want to manipulate the input so I press alt+s to search a snippet and append the snippet to the current line

`$ tail -f <somestream> | <some filtering command>`

' | ' I appended myself. <some filtering command> was expanded by navi to the current readline line.

I decide I want to further narrow my search so I do it again

`$ tail -f <somestream> | <some filtering command> | <another filtering command>`

This chain of commands is not something where I would immediately save it to a cheat file unless I am doing it often in the same order. Otherwise since the order could change in which I filter the input I would not really save every permutation but choose my filters on demand with navi.

**Comment by denisidoro** [comment]
Are you using the latest navi version + bash/zsh? If so, then the widget already supports your use case, if I got it right.

Please check the demo in the README

**Comment by dgengtek** [comment]
Hm I see now why I thought it did not work how I was typing it in the shell since I thought it was only for aliases and exact matches of comments. For example [shellwords::split](https://github.com/denisidoro/navi/blob/master/src/shell.rs#L51
) is unable to handle no whitespace around metacharacter and is splitting input of `echo t| read` into `['echo', 't|', 'read']` which then sets `last_command='echo t| read'` in the widget. While `echo t | read` is split correctly and works like the demo.

Also only `|` metacharacter is supported by navi. For example `echo t ; read ` does not work the same way as in the demo.

If the variable [last_command](https://github.com/denisidoro/navi/blob/master/shell/navi.plugin.bash#L15 ) is empty then the whole line gets replaced(in case you invoke navi when the input is for example `echo t |`). My intention was the following diff

```
diff --git a/shell/navi.plugin.bash b/shell/navi.plugin.bash
index 8495bf7..cda6f07 100644
--- a/shell/navi.plugin.bash
+++ b/shell/navi.plugin.bash
@@ -13,7 +13,8 @@ _navi_widget() {
     local -r last_command="$(echo "${input}" | navi fn widget::last_command)"

     if [ -z "${last_command}" ]; then
-        local -r output="$(_navi_call --print --fzf-overrides '--no-select-1')"
+        local -r append="$(_navi_call --print --fzf-overrides '--no-select-1')"
+        local -r output="${input}${append}"
     else
         local -r find="$last_command"
         local -r replacement="$(_navi_call --print --query "${last_command}")"
```
To also support other metacharacters for chaining commands I would have to update [pub fn widget_last_command() -> Result<()>](https://github.com/denisidoro/navi/blob/master/src/shell.rs#L45)

**Comment by denisidoro** [comment]
> To also support other metacharacters for chaining commands I would have to update pub fn widget_last_command() -> Result<()>

navi already supports `|`, `||` and `&&` IIRC.

> echo t| read

I believe there's no way for navi (or any other CLI other than the shell itself, for that matter) to infer what the user meant in this case.

navi reads this as a full string: `"echo t| read"`. It then needs to decide how to split it into "words". How could it determine if it should be `["echo", "t|", "read"]` or `["echo", "t", "|", "read"]`?

navi could be agressive and always consider `|` as a separate word, but I'm afraid that would lead to bugs where `|` is in the middle of a word.

**Comment by dgengtek** [comment]
> navi already supports |, || and && IIRC.


`||` does not work and pressing ctrl+g after an operator with an empty string after any operator replaces the whole line instead of appending like I desired in the feature request.


[![asciicast](https://asciinema.org/a/UC8JVnEnyxodHoMP6V0f2SNQG.svg)](https://asciinema.org/a/UC8JVnEnyxodHoMP6V0f2SNQG)
