### ISSUE TITLE
config.yaml can not parse ~ or $HOME

### ISSUE THREAD

**Issue by zanglg** [denisidoro/navi#549]
**Describe the bug**

I put my local cheat in .config/navi/cheats/sample.cheat that I push it to github and sync between different machines.
navi --path ~/.config/navi/cheats works well, but seems like navi can not parse ~ or $HOME in config.yaml
I need to modify the cheats path to absolute path in config.yaml between different machines.

Ex: path: ~/.config/navi/cheats to path: /linux/user/.config/navi/cheats and /windows/user/.config/navi/cheats

**Comment by denisidoro** [comment]
This should be easy to fix. I just need to add a logic in navi which replaces a starting `~` by `$HOME`

This will probably be present in the next release

**Comment by zanglg** [comment]
good, I'm waiting for the next release, thanks.

**Comment by gennaro-tedesco** [comment]
> , but seems like navi can not parse ~ or $HOME in config.yaml
> I need to modify the cheats path to absolute path in config.yaml between different machines.

notice that the expansion of the `~` to `$HOME` is responsibility of your shell, and `.yaml` files do not know anything about environment variables (therefore this is not specifically a `navi` bug). This said, I am synchronising my local cheatsheets on multiple machines too thus it would be awesome to have `navi` parser take care of it :)
