### ISSUE TITLE
Why variables only support numbers and no strings

### ISSUE THREAD

**Issue by Elinpf** [denisidoro/navi#55]
great tool and some suggest
I think you can add a variable support string and suggest that possible values for a given argument can be entered instead of not returning directly.

**Comment by denisidoro** [comment]
I don't get it. You're saying that you can type "hello" for <foo>, for example? If so, that's a bug.

Did you install the tool via brew or git? Could you run "navi --version"? I believe you're using a broken version

**Comment by Elinpf** [comment]
my version is `0.8.1` , installed by git.

```
echo <x> <y>
$ x: echo -e '1'
$ y: echo -e "$((x))"
```
it's fine , `y=1'

but if use
```
echo <x> <y>
$ x: echo -e 'a'
$ y: echo -e "$((x))"
```
y is noting, it's not work.

**Comment by denisidoro** [comment]
In your particular example, `"$((x))"` is a math operation, and won't work with non-numerical `x`

This should work:
```
echo <x> <y>
$ x: echo -e 'a'
$ y: echo -e "$x"
```
