### ISSUE TITLE
Import .cheat in .cheat

### ISSUE THREAD

**Issue by ejemba** [denisidoro/navi#552]
Hi , sorry if the feature already exists but is there a way to import a cheat content in another cheat.

I have different variable declarations that I wanted to share between my cheats ... 

So I'm looking for a way to do it.

Sorry if no relevant, I'll close the issue

**Comment by dgengtek** [comment]
do you mean this https://github.com/denisidoro/navi/blob/master/docs/cheatsheet_syntax.md#extending-cheatsheets ?
