### ISSUE TITLE
Add a shortcut to redo last command

### ISSUE THREAD

**Issue by qshzh** [denisidoro/navi#556]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It is common that we need to check something repeatedly. In the standard terminal, using up arrow can help get the last command we use. I think it will be nice if navi supports the feature so that it can save the typing time.

**Describe alternatives you've considered**

**Additional context**

**Comment by denisidoro** [comment]
Please consider using the [shell widget](https://github.com/denisidoro/navi/blob/master/docs/installation.md#installing-the-shell-widget)

With it, you can simply press the up arrow key.

**Comment by qshzh** [comment]
Thanks for your reply. The up arrow key only shows the `navi` command instead of the select command. 
```
> navi
# select command, for example `apt update`,  and run
# press the up arrow key
> navi
```
What I hope is
```
> navi
# select command, for example `apt update`,  and run
# press the up arrow key
> apt update
```

**Comment by denisidoro** [comment]
I see.

If you install the shell widget and invoke navi by pressing `Ctrl+G` instead of typing `navi`, the up arrow key will work as you expect.

**Comment by qshzh** [comment]
Got it. Thanks for your help!
