### ISSUE TITLE
order for parsing variables

### ISSUE THREAD

**Issue by gennaro-tedesco** [denisidoro/navi#562]
**Describe the bug**
As described [in the docs](https://github.com/denisidoro/navi/blob/master/docs/cheatsheet_syntax.md) I am creating cheatsheets syntax variables where, in particular, I have a construction that can be reduced to the below:
```
% tag

# description
mycommand <column> <filename>
```
where the variables are defined via
```
$ filename: ls *.csv | awk '{print $NF}'
$ column: given a file, extracts the column names
```
we can see that in the command instruction `mycommand <column> <filename>` the variable `<column>` comes _before_ the `<filename>`, however the `<filename>` is necessary to "calculate" the former one. This gives rise to a prompt where the former variable is presented with the prompt options of the second (see screenshot below, where instead of the column the filename is prompted first)

<img width="444" alt="Screenshot 2021-06-07 at 16 56 27" src="https://user-images.githubusercontent.com/15387611/121039428-5d192580-c7b1-11eb-875a-ade10e2ae1b0.png">

**Expected behavior**
Not a bug per sé, and the behaviour is somewhat expected (otherwise how would the prompt know what variables to calculate first?), so I do understand. However, I was wondering if there is a way to force the prompt to first calculate the second variable and then use it to calculate the first, and to reflect it in the order of the prompt as well.

**Comment by denisidoro** [comment]
Workarounds:

```sh
# method1
: <filename>; mycommand <column> <filename>

#method2
# description
filename="<filename>" mycommand <column> "$filename"
```

**Comment by gennaro-tedesco** [comment]
Thank you very much for your suggestion, with the wisdom of hindsight it is obvious to first define an env variable and then call it :). I would say it may be useful to add this particular scenario as side note to the syntax documentation (though it is a pretty rare corner case, I must admit).

P. S. Just for reference in your second example you are missing a semi-colon `filename="<filename>" mycommand <column> "$filename"`

**Comment by denisidoro** [comment]
Actually, I'm not 😄 

In bash (and I assume POSIX shell), this...
```sh
foo=bar echo "lorem $foo ipsum"
```

is equivalent to...
```sh
export foo=bar 
echo "lorem $foo ipsum"
unset foo
```

**Comment by denisidoro** [comment]
In contrast,


```sh
foo=bar; echo "lorem $foo ipsum"
```
is simply...
```sh
foo=bar 
echo "lorem $foo ipsum"
# foo still is non-empty here
```

**Comment by gennaro-tedesco** [comment]
Yes, you are right. In my specific case the example would not work because I still pass the same variable along after a pipe `|` (which unsets the variable), which is why I needed the explicit `;` to still have the variable set along (but again mine is an extreme corner case).
