### ISSUE TITLE
Navi Widget Customizations Not Implemented 

### ISSUE THREAD

**Issue by CharlesARoy** [denisidoro/navi#569]
**Describe the bug**
Unable to customize Navi widget.

**Expected behavior and screenshots**
In other installs of Navi (on macOS and Linux), adding the following settings in the zshrc file:
![Image on 2021-06-16 10 07 05 AM](https://user-images.githubusercontent.com/46253001/122262793-9bd26e00-ce8a-11eb-81b3-c8d0796636cf.jpg)

produced a widget that looks like:
![Image on 2021-06-16 10 05 28 AM](https://user-images.githubusercontent.com/46253001/122262553-62016780-ce8a-11eb-9ba7-f6010aab483a.jpg)

However, on the latest install, these don't lines don't seem to be being picked up because the widget looks like:
![Image on 2021-06-16 10 09 08 AM](https://user-images.githubusercontent.com/46253001/122263088-e48a2700-ce8a-11eb-9624-9671bb2ccf04.jpg)

Any idea what I might have missed?

**Versions:**
 - OS: 
 NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
 - Shell Version:
 zsh 5.5.1 (x86_64-redhat-linux-gnu)

**Comment by denisidoro** [comment]
The support for these env vars have been removed. Sorry for the trouble.

You should now use the config yaml instead.

**Comment by denisidoro** [comment]
https://github.com/denisidoro/navi/blob/master/docs/customization.md#changing-colors

**Comment by CharlesARoy** [comment]
Ah ok, I missed that. Thank you!
