### ISSUE TITLE
$ENV_VAR not supported in config file

### ISSUE THREAD

**Issue by rYR79435** [denisidoro/navi#572]
**Describe the bug**
I wan't my cheat files in the same directory as the config.
```
cheats:
    path: $XDG_CONFIG_HOME/navi
```
When I use `./` instead it works.

**To Reproduce**
1. Open config file
2. use $ENV_VAR in `cheats/path` option
3. Try to look up cheats
4. No cheats found

**Expected behavior**
The variable to work (or at least a warning that it won't).

**Comment by denisidoro** [comment]
The (unreleased) master branch already supports the replacement of `$HOME`.

It still doesn't support the replacement of arbitrary env vars, though.

I'm worried that may be complex, because you could have `${FOO}/bar` or `$FOO/bar` etc.

I'll look into it, though.

**Comment by denisidoro** [comment]
The next release should fix this
