### ISSUE TITLE
Output is only 2 rows high

### ISSUE THREAD

**Issue by hood** [denisidoro/navi#573]
**Describe the bug**

**To Reproduce**
Run navi

**Expected behavior**
Output takes a sane amount of rows / number of rows should be configurable

**Screenshots**
https://i.imgur.com/fC0KTY4.png

**Versions:**
 - OS: Linux arch 5.12.13-arch1-2 #1 SMP PREEMPT Fri, 25 Jun 2021 22:56:51 +0000 x86_64 GNU/Linux
 - Shell: zsh 5.8 (x86_64-pc-linux-gnu)
 - Fzf: 0.27.2 (8255aa2)
 
 ----

Consider that `navi --fzf-overrides '--height 20'` has no effect whatsoever, too.

**Comment by denisidoro** [comment]
This isn't expected. You probably have `FZF_OVERRIDES` or `FZF_DEFAULT_OPTS` or any equivalent set somewhere with `–-height 2`

**Comment by hood** [comment]
I have `--height=20%` set in my FZF_DEFAULT_OPTS. But I also have `--height 40` in my NAVI_FZF_OVERRIDES_VAR. 
Is [this](https://i.imgur.com/lVOL8by.png) expected behaviour?

**Comment by denisidoro** [comment]
Could you set `NAVI_FZF_OVERRIDES='--height 40'` too?

**Comment by hood** [comment]
> Could you set `NAVI_FZF_OVERRIDES='--height 40'` too?

Yep, this worked. Sorry for the late reply.
