### ISSUE TITLE
Arbitrary command execution when adding a repo after a new install

### ISSUE THREAD

**Issue by mkroman** [denisidoro/navi#582]
**Describe the bug**

When a repository only has a single cheat command, navi will immediately execute it when starting - presumably because it assumes it's the "best choice" for given query (i.e. no query.)

This has the other bad side effect that when navi tries to relaunch after adding the repo, it will immediately execute the command.

This has security implications because the user would not expect code execution just by adding a repo, trusted or not.

**To Reproduce**
1. Install navi without adding any repos
2. Run `navi repo add mkroman/cheats-repro`
3. Choose yes or no, it doesn't matter.

**Screenshots**
![1627178660](https://user-images.githubusercontent.com/173308/126885318-257ca96b-de9c-4a73-98ae-2b6a3786f5b2.png)

**Versions:**
 - Navi: master, 2.16.0
 - OS: Arch Linux

**Comment by denisidoro** [comment]
In the next release I'll somehow pass a parameter such as `prevent_auto_execution` [here](https://github.com/denisidoro/navi/blob/master/src/handler/mod.rs#L45)

**Comment by mkroman** [comment]
That may not be enough since it'll still execute the command when the user runs `navi`. I think this behavior should only be limited to `navi --query … --best-match`.

**Comment by denisidoro** [comment]
I see. You're suggesting that for cheat selection navi should never autoselect, unless `--best-match` is set, right?

**Comment by mkroman** [comment]
Yes, I'd argue that there's no scenario where someone wants to run `navi` without `--best-match` and have it execute an arbitrary command.
