### ISSUE TITLE
Add new command to cheatsheet ad-hoc.

### ISSUE THREAD

**Issue by Edwardlin-zlt** [denisidoro/navi#583]
I'm new here, and I assume that there's navi command like `navi add -e` to open an editor ad-hoc, then I could write down some thing which will be same to my local cheat sheet. But right now it seems no command like that.

Actually I don't want import someone else's cheat sheet other than build one from scratch of my own. Thus I will be very familiar with those hints I wrote down. So I want have that convenient way to add new hints without thinking where those hint I should put into.

Or, there's already some way to achieve this but I didn't find out myself?

**Comment by denisidoro** [comment]
More or less. Assuming you already have a cheatsheet, you can hit `Ctrl-E` to edit it.

But there's no automatic way to generate a cheatsheet from scratch.

I'll try to include such feature in a future release.

**Comment by denisidoro** [comment]
Fixed by https://github.com/denisidoro/navi/pull/599
