### ISSUE TITLE
zsh: variable with `--map` does not show in preview window

### ISSUE THREAD

**Issue by fjchen7** [denisidoro/navi#584]
**Describe the bug**
variable with parameter `--map` won't show in preview window.

**To Reproduce**

```
% rg, grep

# search lines matching a pattern in given path
rg <opts> <pattern> <path>

$ opts: echo -e 'option;description\n--column;show column numbers\n-l;print filenames with maches\n--files-without-match;print filenames without matches' | column -t -s';' --- --column 1 --header-lines 1 --multi --map "tr '\n' ' '"
```
For the above cheatsheet the variable `opts` won't show in preview window.
![Screen Shot 2021-08-02 at 22 53 27](https://user-images.githubusercontent.com/10106636/127881308-14335287-7c53-4a4d-ab13-de844c98a86f.jpg)
When I remove `--map "tr '\n' ' '` it shows, but now each item will be put into different lines which is not expected.

The other variables show as expected
![image](https://user-images.githubusercontent.com/10106636/127881844-9e058c5a-e7f6-4f05-870b-e7de4bb054f6.png)

**Versions:**
 - OS: macOS
 - Shell Version: zsh 5.8
 - navi 2.16.0

**Comment by denisidoro** [comment]
<img width="548" alt="Screen Shot 2021-08-06 at 10 55 45" src="https://user-images.githubusercontent.com/3226564/128521190-8796c856-8e23-4d76-93a5-cbbef36f028a.png">

I believe it works as expected on my machine 🤔

**Comment by denisidoro** [comment]
Could you try setting `bash` as shell in the yaml config file?

**Comment by fjchen7** [comment]
> Could you try setting `bash` as shell in the yaml config file?

It works if setting `bash` in yaml config file. Thanks!

But as it fails to show preview when setting `zsh`, I think it is still a small bug. should I close this issue?

**Comment by denisidoro** [comment]
Thanks for the report!

> should I close this issue?
Not yet. I'll look into it. I plan to release a new version this week and hopefully by then I'll have it fixed.

**Comment by kqvanity** [comment]
@denisidoro Is there a better way to annotate custom parameters other than @fjchen7's oneliner. The original string too jammed up
