### ISSUE TITLE
Allow variable names to include dashes or spaces

### ISSUE THREAD

**Issue by denisidoro** [denisidoro/navi#60]
It's not evident that variables should only contain alphanumeric characters and underscores.

Using spaces and dashes would make variable references in scripts non trivial, though (eg "image name" would become "image_name").

**Comment by engrravijain** [comment]
Hey @denisidoro, I would like to pick this issue up. Need some more clarification here what is the requirement exactly.

**Comment by denisidoro** [comment]
Thanks, @engrravijain!

These should be valid arguments: <foo>, <foo_bar>, <foo-bar> and <foo bar>.

Today, only the first two are considered valid. 

First, you need to change this regex: https://github.com/denisidoro/navi/blob/master/src/arg.sh#L3. 

Then, when assigning values, you need to replace spaces and dashes by underscores here, because foo-bar isn't a valid bash variable: https://github.com/denisidoro/navi/blob/master/src/main.sh#L41

Finally, the last step is to make the interpolation work here: https://github.com/denisidoro/navi/blob/master/src/main.sh#L42

**Comment by denisidoro** [comment]
Or, another solution is to replace the dashes and spaces when reading the files. This way no other code would be modified. However, it would make the startup a little bit slower

**Comment by engrravijain** [comment]
Got it. Thanks, Denisidoro.
