### ISSUE TITLE
install navi on ubuntu

### ISSUE THREAD

**Issue by lbgws2** [denisidoro/navi#621]
i'm use Ubuntu 20.04.2 LTS,can navi support the apt package managers

**Comment by denisidoro** [comment]
I have already [filed the request](https://bugs.launchpad.net/ubuntu/+bug/1924877) for adding it to the main apt repo to no avail 😢  

Does anyone know of any alternative methods?

**Comment by hood** [comment]
@denisidoro we could try a snap package. It should be pretty easier to set up.

**Comment by oben01** [comment]
While waiting for navi to support apt package, here is some install instructions tested with Ubuntu 20.04 :
1. Install FZF from source 
```
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
```
Check version 
```
fzf --version
0.27.2 (e086f0b)
```

2. Install rust 
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
Check version 
```
rustc --version
rustc 1.55.0 (c8dfcfe04 2021-09-06)
```
3. Install Navi 

```
bash <(curl -sL https://raw.githubusercontent.com/denisidoro/navi/master/scripts/install)
```

Check version 
```
navi --version
navi 2.17.2
```

**Comment by denisidoro** [comment]
There's no need to build from source if you don't want to. 

The releases page has a pre-compiled binary ready for you to download.

**Comment by denisidoro** [comment]
For example: https://github.com/denisidoro/navi/releases/download/v2.17.0/navi-v2.17.0-x86_64-unknown-linux-musl.tar.gz

**Comment by oben01** [comment]
@denisidoro Thank you for this great tool. Could you please release the latest version (2.17.2)?

**Comment by denisidoro** [comment]
2.17.2 is the same as 2.17.0. It only includes some fixes for the [cargo crate](https://crates.io/crates/navi).

**Comment by lbgws2** [comment]
> While waiting for navi to support apt package, here is some install instructions tested with Ubuntu 20.04 :
> 
> 1. Install FZF from source
> 
> ```
> git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
> ~/.fzf/install
> ```
> 
> Check version
> 
> ```
> fzf --version
> 0.27.2 (e086f0b)
> ```
> 
> 1. Install rust
> 
> ```
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> ```
> 
> Check version
> 
> ```
> rustc --version
> rustc 1.55.0 (c8dfcfe04 2021-09-06)
> ```
> 
> 1. Install Navi
> 
> ```
> bash <(curl -sL https://raw.githubusercontent.com/denisidoro/navi/master/scripts/install)
> ```
> 
> Check version
> 
> ```
> navi --version
> navi 2.17.2
> ```

awesome!!!
The problem has been solved. Thank you very much
