### ISSUE TITLE
Make commands cacheable

### ISSUE THREAD

**Issue by dadav** [denisidoro/navi#629]
**Is your feature request related to a problem? Please describe.**
While I was writing a cheatfile for ansible, I ran the command `ansible-doc -l` to get a list of all the modules that I could possibly use. This command is super slow and takes some seconds to finish. During this time `navi` disappears (I'm seeing my shell now) and only comes back when the command is finished. 

**Describe the solution you'd like**
It would be awesome to be able to prefix commands that should be cached for e. g. a limited time or forever. For example like this:

`$[cache;7d] modules: ansible-doc -l --- --column 1`

**Describe alternatives you've considered**
Safe the output of ansible-doc -l and simply run cat. 

**Additional context**
I already googled a bit, but could not rly find a suitable library we could use.

**Comment by denisidoro** [comment]
Hi! Nice use case!

However, I don't think we should couple this behavior with navi:

Example:
```
$ modules: some-cache-cli --days 7 --command 'ansible-doc -l' --- --column 1
```

What do you think?
