### ISSUE TITLE
Loading indicator for long running commands

### ISSUE THREAD

**Issue by richardpeng** [denisidoro/navi#639]
**Is your feature request related to a problem? Please describe.**
It's confusing when I have a command to generate the list of possible values that takes a couple seconds to run. There isn't any feedback that anything is loading

**Describe the solution you'd like**
Perhaps immediately outputting stdout to fzf and loading more into the list as each command outputs to stdout.
```
$ key: echo "Loading..."; chamber list my-vars --- --header-lines 1 --column 1
```

**Describe alternatives you've considered**
I tried various ways to output text early, but nothing worked.

**Additional context**
```
% slow

# Slow command
echo <a> <b>

$ a: sleep 2; echo "a c" | tr ' ' '\n'
$ b: sleep 2 && echo "b d" | tr ' ' '\n'
```

**Comment by denisidoro** [comment]
It's far from ideal, but here's a workaround:
```sh
$ a: echo "Loading..." >&2; sleep 2; printf '%b' '\033[2J' >&2; echo "a c" | tr ' ' '\n'
```

**Comment by denisidoro** [comment]
If this is too mouthful, you can create a bash "alias":
```sh
call_with_loading_indicator() {
   printf 'Loading...' >&2
   "$@"
   printf '%b' '\r\033[2K' >&2; 
}
```

Then:
```sh
$ a: call_with_loading_indicator echo "a c" | tr ' ' '\n'
```

**Comment by denisidoro** [comment]
For context, your attempts failed because you were printing to stdout, which gets piped to fzf's stdin instead of your terminal emulator.

stderr (`&2`) goes directly to your terminal, so you're free to print there while fzf's stdin is open.

**Comment by richardpeng** [comment]
> It's far from ideal, but here's a workaround:
> 
> ```shell
> $ a: printf 'Loading...' >&2; sleep 2; printf '%b' '\r\033[2K' >&2; echo "a c" | tr ' ' '\n'
> ```

This is very clever and works well enough! 😊 

> For context, your attempts failed because you were printing to stdout, which gets piped to fzf's stdin instead of your terminal emulator.
> 
> stderr (`&2`) goes directly to your terminal, so you're free to print there while fzf's stdin is open.

That makes a lot of sense. Thanks for the insight!

> If this is too mouthful, you can create a bash "alias":
> 
> ```shell
> call_with_loading_indicator() {
>    printf 'Loading...' >&2
>    "$@"
>    printf '%b' '\r\033[2K' >&2; 
> }
> ```
> 
> Then:
> 
> ```shell
> $ a: call_with_loading_indicator echo "a c" | tr ' ' '\n'
> ```

I couldn't get the alias to work. I tried adding `call_with_loading_indicator` in my `.cheat` file, adding it to `.bash_profile`, adding it to `.bashrc`, and adding it to `.zshrc`. All of them resulted in `call_with_loading_indicator: command not found`

As a side note, is there a way to "load" helper methods to make them available to a cheat file by sourcing a file?

**Comment by denisidoro** [comment]
> I couldn't get the alias to work

Apparently there are some limitation on how exported functions work.

Suppose I have the following code sourced in my .rc-like file
```sh
myfn() {
  echo myfn "$@"
}

export -f myfn
```

If my shell is `bash` and the shell used by navi (see config.yaml) is `bash` too this works.

If my shell is `zsh` and the shell used by navi is `bash` too this won't work.

I'll try to investigate this further.

**Comment by denisidoro** [comment]
> is there a way to "load" helper methods

This should do the trick:
```sh 
# my cmd
source "$HOME/helpers.sh"
some_helper_cmd 1 2 3
```

I could also add a global param that allows you to run arbitrary code before each shell out. WDYT?

**Comment by richardpeng** [comment]
> I could also add a global param that allows you to run arbitrary code before each shell out. WDYT?

that would be extremely useful if you could add that!

**Comment by denisidoro** [comment]
Closing in favor of https://github.com/denisidoro/navi/issues/645

**Comment by richardpeng** [comment]
The fix worked for me! Thanks!
