### ISSUE TITLE
Recv failure: Connection reset by peer?

### ISSUE THREAD

**Issue by feiyuhuahuo** [denisidoro/navi#64]
I tried use the git clone command with sudo on Ubuntu18.04, and then get this:
![image](https://user-images.githubusercontent.com/32631344/65572988-57a78780-df9c-11e9-856f-e01e8b973e5b.png)
Cloning other projects is OK. How to fix this?

**Comment by enisozgen** [comment]
I don't think that issue fault of project.

In my opinion, there should be some firewall issue. If you use cooperate network, you can share your phone internet with your PC, and try again.

Try again via
```git clone https://github.com/denisidoro/navi.git```

You need to check that
- https://askubuntu.com/questions/1058859/git-clone-fails-with-connection-reset-by-peer
