### ISSUE TITLE
Choose backend for fuzzy search during install (emerge)

### ISSUE THREAD

**Issue by orleanski** [denisidoro/navi#647]
Hello,

**Is your feature request related to a problem? Please describe.**
During installation it pulls fzf and golang even is skim is already installed.

**Describe the solution you'd like**
Would it be possible to introduce USE flag (in Gentoo) or use build time option like `--build-with-skim` or `--build-with-fzf` to use skim or fzf and build accordingly without pulling extra dependencies.

Thank you in advance.

**Comment by denisidoro** [comment]
I'm not familir with the Gentoo packaging system :/ 

If you install navi via `cargo install --navi`, then unnecessary dependencies won't be installed AFAIK.
