### ISSUE TITLE
Add “smart replace” functionality to the fish shell widget

### ISSUE THREAD

**Issue by notDavid** [denisidoro/navi#648]
The [shell widget](https://github.com/denisidoro/navi/blob/master/docs/installation.md#installing-the-shell-widget) for [fish](https://github.com/denisidoro/navi/blob/master/shell/navi.plugin.fish) currently does not yet support replacing text with a shortcut, as can be done with the bash and zsh widgets.
For info see: https://github.com/denisidoro/navi/issues/491#issuecomment-981780593 )

So, the [bash or zsh](https://github.com/denisidoro/navi/tree/master/shell) widgets need to be translated / converted to fish.

**Comment by DevAtDawn** [comment]
You can add me to assignees, I’ll work on this feature, thx

**Comment by vivekragunathan** [comment]
It's not fish I am using... So I think the issue is not restricted to fish

**Comment by DevAtDawn** [comment]
> It's not fish I am using... So I think the issue is not restricted to fish

what are you using? the fish shell widget is for fish, there is also ones for zsh/bash/elv

**Comment by vivekragunathan** [comment]
I tried bash and zsh, and they too have the same issue.

PS: I had commented in a different issue/thread and am not sure why GitHub got me commenting here.

**Comment by DevAtDawn** [comment]
@notDavid finished this, issue can be closed

**Comment by notDavid** [comment]
@DevAtDawn Awesome, thank you! 🙏🏼
