### ISSUE TITLE
Metacomment Placement

### ISSUE THREAD

**Issue by guy-who-googles** [denisidoro/navi#651]
**Describe the bug**
When a semicolon is the first character in the line, it is correctly interpreted as a metacomment.
When whitespace precedes the semicolon, the line is evaluated.

**To Reproduce**
An example shamelessly stolen from the [docs](https://github.com/denisidoro/navi/blob/master/docs/cheatsheet_syntax.md#multiline-snippets):
```
# This will output "foo\nyes"
echo foo
true \
    && echo yes \
    ; this comment may cause many a headache
    || echo no
```

Output: error because comment not ignored

**Expected behavior**
Whitespace should be ignored. As long as the first character in the line is a semicolon, then entire line should be interpreted as a metacomment

**Versions:**
 - OS: Ubuntu 20.04 LTS
 - Shell Version [GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)]
 - Navi: 2.18.0

**Workaround**
Unintuitive, so I keep forgetting, but you could always indent after using a semicolon:

```
# This will output "foo\nyes"
echo foo
true \
    && echo yes \
;   If you have better memory than this line is a comment.
    || echo no
```

**Comment by denisidoro** [comment]
Even though it should be easy to make navi understand what you're suggesting, I'm afraid that could be a breaking change, as the following isn't a valid bash script:
```sh
true \
    && echo yes \
;   If you have better memory than this line is a comment.
    || echo no
```

In other words, if you copy/paste this into a bash script, it won't behave as you intended, so I don't think navi should "extend" the language for the script it's executing.

The workaround is to use valid bash syntax instead. Example:
```sh
# This will output "foo\nyes"
echo foo
true \
    && echo yes `# comment 1` \
    || echo no `# comment 2`
```

**Comment by guy-who-googles** [comment]
> I don't think navi should "extend" the language for the script it's executing.

That's fair. I didn't consider executing the snippet in bash first, so I didn't think of it. Thanks.
