### ISSUE TITLE
Smart replace (Ctrl+G) is not working in bash/zsh

### ISSUE THREAD

**Issue by vivekragunathan** [denisidoro/navi#656]
Here is a snapshot demonstrating the issue.
![navi](https://user-images.githubusercontent.com/292160/146436514-a249dd89-5b08-4b51-b91c-0a90a6764e82.gif)

I have the line `eval "$(navi init zsh)"` in my `.zshrc` (and `.bash_profile`)
Am I missing a step or configuration for smart replace to work properly?

**Comment by DevAtDawn** [comment]
any chance your ctrl+g keybind is being remapped by your emulator or shell settings? have you tested it in a diff terminal? @vivekragunathan

**Comment by vivekragunathan** [comment]
Yes, I tried in mac terminal, iTerm and Hyper. I checked the key mappings, Ctrl+G is not mapped to anything.

**Comment by vivekragunathan** [comment]
I had to quit many of applications running and restart my mac for completely different reason. Now it is working, I have no idea why.
