### ISSUE TITLE
How to set download destination for cheats git repositories?

### ISSUE THREAD

**Issue by den-is** [denisidoro/navi#657]
I was not able to find a setting that will set the primary destination for all cheats once and forever.

I'm using navi on macos and I don't like/need the default option that [data_dir](https://github.com/dirs-dev/dirs-rs#Features) suggest by default.

My setup:
```sh
navi 2.18.0
# ENV config
export NAVI_CONFIG=$HOME/.config/navi/config.yaml
```
Navi config.yaml
```yaml
cheats:
  paths:
  - ~/.config/navi/cheats
```

`navi` and specifically `navi info` with `navi repo add` completely ignore NAVI_PATH env variable or what is configured in config.yaml

```sh
navi info cheats-path
/Users/den/Library/Application Support/navi/cheats

NAVI_PATH="$HOME/.config/navi/cheats" navi info cheats-path
/Users/den/Library/Application Support/navi/cheats
```
Why `navi info cheats-path` still returns original value from data_dir and ignores `NAVI_PATH` or `paths` in config file - uh-oh - this configs support multiple values, lists.
Probably that command should be renamed in `navi info cheats-download-path`

ok I understand that behavior - `NAVI_PATH` and `paths` are just used to indicate read-from destinations for outputs.

**So, how to update that setting and prevent navi from writing in that shitty directory and instead write in the shitty directory that I prefer?**
Because instead of pulling/cloning repo I manually place cheats where I need them.

I was not able to find anything related in `navi --help` and `navi info config-example`, as well in great(No!) docs of this repo.

**Comment by denisidoro** [comment]
You can't. 

You can use symlinks instead:
```sh
ln -s "$(navi info cheats-path)" ~/.config/navi/cheats
```

or the other way around.

**Comment by den-is** [comment]
genius. absolutely not user-friendly, not flexible and terrible UX, same relates to docs in that repo.

if it is that difficult to have just one config option for that - like other thousands of apps have. 
Unfortunately, Rust is not on the list of my interests to at least suggest PR for that.

of course, I will continue using that app, that brings me profit - such minor inconvenience won't stop knight of IT .... well .... pffff.... you got the idea :D :D

probably I just have had to say modern and hypocritical "Thanks, great job! Saves me a ton of time!" ! :D :D
(but really you know... ;) thanks )
