### ISSUE TITLE
Run last printed command

### ISSUE THREAD

**Issue by enisozgen** [denisidoro/navi#66]
Well done! Awesome project!!

This project bring new answer for the question **What is cheatsheet for Linux?**

Since that everything is good. In my opinion, default behaviour is not safe since it's runs selected command even knowing what is command. 

For example if I will use `docker rmi` command to additionally `navi` runs 
`$ docker images --- --headers 1 --column 3` and select argument by column base selector.

Any mistake in this process like 

- Column base selector may will not give correct parameter due to special character etc.. (Or output change for application)
- User can make mistake while selecting command
- User can make mistake selecting image column

In this cases user can delete wrong things and this can create problem for user.

Absolutelly I understand this is not your responsibility and also you mentioned also in the help page. To being safe and secure use `--print` option. 

To prevent those problems, I wrote 2 simple bash function which could be new feature for this project.

```
function naviprint()
{
    PRINT_OUTPUT=$(navi --print)
    export NAVI_LAST_COMMAND=$(echo $PRINT_OUTPUT)
    echo "$NAVI_LAST_COMMAND"
}

# Can be as used as navi lastcommand
function navilast()
{
    eval $NAVI_LAST_COMMAND
}

```

Thank you for your effort!

Best Regards,
Enis

**Comment by denisidoro** [comment]
I'm not sure I got it. Your concern is with the `---` syntax?

**Comment by enisozgen** [comment]
I copied line from there https://github.com/denisidoro/navi/blob/master/cheats/docker.cheat#L40

**Comment by denisidoro** [comment]
I'm not sure that would work because `export` won't apply to your main shell. It will apply to the bash shell that was triggered when calling the script. 

So the second time one runs `navi`, the variable will be undefined.

**Comment by forbesmyester** [comment]
It seems somewhat related... I want to run: `. $(navi --print)` But this doesn't seem to work.

Whereas if I do `. $(echo <what navi printed out>)` it actually does work. Am unsure about what is happening in the middle, I haven't done enough digging to satisfy myself that it's a navi bug or a bug in the script navi is executing itself. Only adding it here as it may help with this issue

**Comment by enisozgen** [comment]
> I'm not sure that would work because `export` won't apply to your main shell. It will apply to the bash shell that was triggered when calling the script.
> 
> So the second time one runs `navi`, the variable will be undefined.
 
As you say it is not possible to do it with `export`. I did it just as an example, it's not possible to do it since command opens different shell processes at background.

**Comment by denisidoro** [comment]
Maybe https://github.com/denisidoro/navi/issues/37 solves the same problem and we can close this issue? What do you think?

**Comment by enisozgen** [comment]
Thank you for solution. Also, it gives ability to change the command before execution.

1. I did small test about to being sure and found small problem. Cheatsheets which expect interactive input like `type`, `port`, `name` fails because of input not provided.

```
 Unable to fetch suggestions for 'type'! 
```
You can try this case via: 
`Ctrl-g` write  `kubernetes type` or `netstat` than press `ENTER`

2. Just small warning about keybinding. `Ctrl-g` is already binded key for `zsh`. I never used it but just I am informing here

```
bindkey | grep get-line
"^[G" get-line
"^[g" get-line
```

3. `bindkey '\eg' _call_navi` didn't worked for me! I used `bindkey ^g  _call_navi` NOTE: This can be related with my machine.

**Comment by aminehmida** [comment]
I think what you want to do it to put the command in the bash readline buffer so you have a chance to edit it before you press enter.

I am working on [similar project](https://github.com/aminehmida/aws-fzf/) related to AWS
This is very easy to do in zsh using `print -z`.

Unfortunately, I couldn't find a way to do that in Bash cross-platform (Linux/Mac OS)
Here is an [issue in stackexchange](https://unix.stackexchange.com/questions/82630/put-text-in-the-bash-command-line-buffer) maybe you will have better luck than me.

**Comment by denisidoro** [comment]
Closing in favor of #37
