### ISSUE TITLE
Question: Add custom cheats in addition to the built-in ones.

### ISSUE THREAD

**Issue by vivekragunathan** [denisidoro/navi#674]
I installed `navi`, setup my .zshrc (`eval "$(navi widget zsh)"`) that provides a lot of built-in cheats. I am trying to add a cheat of my own. 

- I read in the documentation that I can do this `export NAVI_PATH="/folder/with/cheats:/another/folder"` but that takes away the built-in and leaves only my own cheats.
- I also found `navi --path "/folder/with/cheats"` but that is a one-off at the prompt. I would like to set it up once (add custom path where my cheats are) in my `.zshrc`

Is there a way to do that?

**Comment by denisidoro** [comment]
This should do the trick:
```sh
export NAVI_PATH="$(navi info cheats-path):/folder/with/cheats:/another/folder"
```

`navi info cheats-path` returns the default path for cheats

**Comment by vivekragunathan** [comment]
Thanks. It works now.
