### ISSUE TITLE
Feature Request: Contextual Shortcuts

### ISSUE THREAD

**Issue by knpwrs** [denisidoro/navi#685]
It would be cool to have certain shortcuts only show up in certain contexts. For instance, only show certain `git` shortcuts when I'm inside a git project, only show certain `npm` and `node` shortcuts when I'm in a project with a `package.json`, `ruby` if there's a `Gemfile` or `.ruby-version`, `cargo` if there's a `Cargo.toml`, etc.

Showing only shortcuts that are relevant to what I'm working on could make the list of shortcuts easier to scan. I'm not sure how this would look in the configuration file. I'd always want `npm init --yes` to show up, for instance, but then I would want to hide a bunch of `npm` shortcuts by default. Maybe the `.cheat` files can be split into contexts?

**Comment by denisidoro** [comment]
As a workaround, you can add something like the following to your bashrc file:

```bash
function calculate_cheats() {
   local -r cheats="always/present/file.cheat"
   # if pwd/package.json exists then
   #  cheats="${cheats}:/path/to/nodejs.cheat
   # fi
   echo "$cheats"
} 

function navi() {
  NAVI_PATH="$(calculate_cheats)" command navi "$@"
}
```

**Comment by knpwrs** [comment]
That's a clever trick, and very similar to my setup for direnv and project-local shortcuts. I'll probably give this a go and utilize something like https://github.com/datagrok/findup-shhttps://github.com/datagrok/findup-sh.

**Comment by denisidoro** [comment]
Closing as the workaround is IMO clean enough to justify no native support for this in the near future
