### ISSUE TITLE
--delimiter "\s+" option shows only 3 columns and extra columns are not shown

### ISSUE THREAD

**Issue by kai2nenobu** [denisidoro/navi#691]
**Describe the bug**

If a variable is defined with `--delimiter "\s+"`, navi shows only 3 columns and extra columns are not shown.

**To Reproduce**

Sample cheat

```sh
# Extract a fourth column with delimiter
echo <variable_with_delimiter>
$ variable_with_delimiter: printf "1 2 3 4 5\na b c d e\n" --- --column 4 --delimiter "\s+"

# Extract a fourth column
echo <variable>
$ variable: printf "1 2 3 4 5\na b c d e\n" --- --column 4
```

1. Launch `navi`
2. Select `Extract a fourth column with delimiter`
    ![image](https://user-images.githubusercontent.com/810042/155248335-5e3288d7-7813-4dc2-b13d-40ebcdda300e.png)
3. In variable selection, only three columns are shown and fourth, fifth columns are disappeared.
    ![image](https://user-images.githubusercontent.com/810042/155248363-94cec9ff-f95c-4466-8f45-67df0c2ef086.png)

    If I select `1 2 3`, fourth column string (`4`) is extracted and output.
    ![image](https://user-images.githubusercontent.com/810042/155247743-3e09d83e-f17d-4440-b367-a648f1fb4f76.png)

    However, I cannot search by fourth column string.
    ![image](https://user-images.githubusercontent.com/810042/155248393-aec8f909-048a-462d-b2b6-5eecf088fb51.png)

**Expected behavior**

In variable selection, the following variable candidates are shown and navi can search them.

```
1 2 3 4 5
a b c d e
````

**Versions:**

- navi: 2.19.0
- fzf: 0.24 (devel)
 - OS: Ubuntu 20.04
 - Shell Version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Additional context**

If I select `Extract a fourth column` command, all columns are shown in variable selection but navi cannot extract a fourth column string. Is this because a default delimiter is 2 spaces?

![image](https://user-images.githubusercontent.com/810042/155248564-4d2a0287-36bb-45b5-a88a-a50c9cbd38da.png)

**Comment by spaddex** [comment]
Seems like deleting line 79 and 80 in [src/finder/mod.rs](https://github.com/denisidoro/navi/blob/master/src/finder/mod.rs#L79) might solve this.

**Comment by dgengtek** [comment]
don't think this is a bug since it is just a default which you can easily override with an export

if you want every column use

`export NAVI_FZF_OVERRIDES_VAR="--with-nth=.."`

see manpage of fzf under FIELD INDEX EXPRESSION for more details
