### ISSUE TITLE
Is there any zsh completion script for navi?

### ISSUE THREAD

**Issue by Alex-duzhichao** [denisidoro/navi#694]
Hi, thank you for the awesome tool.
I'm using zsh as my default shell. I want navi can provide a zsh completion script. So that we can use it for auto completion.
For example, when we input `nave` and press `<tab>`, zsh should suggest subcommands automitically.

**Comment by denisidoro** [comment]
There's no Tab autocompletion but there's the shell widget: https://github.com/denisidoro/navi/blob/master/docs/installation.md#installing-the-shell-widget
