### ISSUE TITLE
Can't query command with space using tldr

### ISSUE THREAD

**Issue by Alex-duzhichao** [denisidoro/navi#695]
Hi, I want using tldr to query "openssl x509". If I do `tldr openssl x509`, the result is what I want. 
But if I do `navi --tldr openssl x509`, navi complains ```error: Found argument 'x509' which wasn't expected, or isn't valid in this context```.
So I try to add quote to the parameter `navi --tldr "openssl x509"`, navi runing for a while and messes up my terminal finally.

https://user-images.githubusercontent.com/9667107/156396405-b0fad466-8d3b-48cd-9738-3a91ef5821ba.mp4

I think navi should support query command with space using tldr.
I am using `zsh 5.8.1` on ubuntu

**Comment by denisidoro** [comment]
Thanks for reporting. I'll look into it

**Comment by denisidoro** [comment]
Actually this happens whenever `tldr <arg>` fails to find a result
