### ISSUE TITLE
Variable names cannot contain dots

### ISSUE THREAD

**Issue by carlfriedrich** [denisidoro/navi#701]
**Describe the bug**
Variable names containing dots are not recognized as variables. Is this a deliberate choice?

**To Reproduce**

The following cheat sheet does not recognize `file.tar` as a variable, it only queries `files` interactively:

```
# Create tar archive
tar -cf <file.tar> <files>
```

**Expected behavior**
A variable containing dots should be queried interactively like all other variables.

**Versions:**
 - OS: WSL ubuntu
 - Shell Version GNU bash, version 5.0.17(1)-release

**Comment by denisidoro** [comment]
It's a deliberate choice.

navi variables are designed to be bash-compatible, to make integrations easier.

**Comment by carlfriedrich** [comment]
@denisidoro Alright, thanks for the clarification.

**Comment by z0xyz** [comment]
@denisidoro Is there a workaround to include dots nonetheless?

**Comment by jackandroselv** [comment]
您好！您的邮件我已收到，我会尽快的查阅邮件。谢谢您的来信！
