### ISSUE TITLE
Preview window is empty if suggestion command returns no results

### ISSUE THREAD

**Issue by carlfriedrich** [denisidoro/navi#702]
**Describe the bug**
If the supplied suggestion command following `$` does not return any results, the complete preview window becomes empty.

**To Reproduce**

Run this cheat sheet in a folder which does not contain any `.tar` files.

```
# Extract tar archive (gz/bz2/xz)
tar -xf <file>
$ file: ls *.tar
```

Then the preview window is empty:

![grafik](https://user-images.githubusercontent.com/45259958/157497034-f61c7eef-e794-4b89-9fbd-e77e499c46df.png)

**Expected behavior**

The preview window should behave as if no suggestion command has been supplied:

![grafik](https://user-images.githubusercontent.com/45259958/157497824-cb3ade6f-5985-4740-bf7e-31a2b9d442d4.png)

**Versions:**
 - OS: WSL ubuntu
 - Shell Version GNU bash, version 5.0.17(1)-release

**Comment by denisidoro** [comment]
If you type something, the behavior will be as expected:

![shot 2022-03-11 at 10 08 05](https://user-images.githubusercontent.com/3226564/157872351-8631b952-24a2-4345-a249-bba62e0aee14.png)

![shot 2022-03-11 at 10 08 10](https://user-images.githubusercontent.com/3226564/157872364-6a70de43-7c11-4995-861c-4c95f3bb7aae.png)

**Comment by denisidoro** [comment]
Yes, sure!
