### ISSUE TITLE
Find and show the cheatsheet filename with matching contents

### ISSUE THREAD

**Issue by smolin** [denisidoro/navi#714]
**Is your feature request related to a problem? Please describe.**
The problem is that I have a mix of executable cheats and descriptive cheats, and I'd like to keep them in the same place.

**Describe the solution you'd like**
I would like a flag for navi that returns the filename where the match is found:
```
% navi --filename git
<interactively narrow down the search space, then hit Return>
./config/navi/cheats/git__searching.cheat
```

**Describe alternatives you've considered**
I looked into doing this with vanilla fzf but couldn't figure out a solution.

**Additional context**
Another option would be to print the entire file instead of just the filename.

navi is great, thank you!

**Comment by denisidoro** [comment]
Hey, thanks for opening an issue.

What you're suggesting is trivial to implement but I'd like to understand what the use case actually is first and, more importantly, if this should be handled by navi or not.

Today, navi already offers the possibility to pre-filter results. Would that be enough?

Also, you can have a bash alias that calls navi with different values for NAVI_PATH, so you could have a `navigit` command that only show git-related snippets.

**Comment by smolin** [comment]
Hi! Thanks for getting back to me. I'm not sure how to describe a "use case" in helpful terms, but maybe an example would help: here's a snippet from my `vim` cheat file:
```
% vim

# Move cursor in viewport, move viewport around cursor

z.     scroll so line with cursor is at center
zt     scroll so line with cursor is at top
zb     scroll so line with cursor is at bottom

H      move cursor to top of screen
M      move cursor to middle of screen
L      move cursor to lower of screen
```
If I run navi and enter "vim move cursor" it sure enough selects that snippet, but hitting "return" at this point is not helpful, since it's not shell commands:
```
% navi
bash: line 1: z.: command not found
bash: line 2: zt: command not found
bash: line 3: zb: command not found
bash: line 5: H: command not found
bash: line 6: M: command not found
bash: line 7: L: command not found
```
(you can see how this could go horribly wrong :-) Instead of executing the match, I just want to *see* it.

I have the shell integrations, so I can also enter "vim move cursor" and hit control-G and then control-C to interrupt, but it's an awkward workflow.

Also, sometimes you want to see some context around the final selection, such as when several individual entries taken together build up a more holistic view of the problem space. As a workaround I added
```
# View this cheatsheet

cat /Users/steven.molin/resources/linuxhome/.config/navi/cheats/vim.cheat
```
to the bottom of the file.

**Comment by smolin** [comment]
Here's another situation where it's useful to see more context, in this case the formatting of the description is helpful:
```
# Move contents of a directory to another. Trailing slash on first arg is significant:
#     * "src dst" will result in dst/src
#     * "src/ dst" contents of src will be directly in dst

rsync -av --remove-source-files <source_dir> <dest_dir>
```

**Comment by smolin** [comment]
Another thought is that this would allow the always-helpful edit feature (see for example `cheat -e`)

**Comment by denisidoro** [comment]
Then I guess navi already covers it

### Printing the selected snippet
```
navi --print
# <type>
# <enter>
```

### Editing the cheatsheet where the selected snippet is defined
```
navi
# <type>
# <ctrl-o>
```

### Printing the cheatsheet where the selected snippet is defined
```
EDITOR=cat navi
# <type>
# <ctrl-o>
```

**Comment by smolin** [comment]
Sweet! Awesome. Thank you again, sorry for wasting your time.

**Comment by denisidoro** [comment]
No problem! Thanks for taking the time to ask this :)
