### ISSUE TITLE
How can I close "smart replace" feature?

### ISSUE THREAD

**Issue by HideOnLie** [denisidoro/navi#715]
For me, I don't need to open this feature. now when I just want to watch my cheatsheet for specified command. I must press <ctrl + G> twice, and delete the word which navi found the best match. In order to achieve this behavior, I must modify the widget.zsh (generated by `navi widget zsh`)
I hope have a option can control this action. Thank~

**Comment by denisidoro** [comment]
For now, the best solution is to indeed copy the contents from `navi widget zsh` and edit it to your preference
