### ISSUE TITLE
Raspberry Pi 64bit release

### ISSUE THREAD

**Issue by notDavid** [denisidoro/navi#726]
Hi there,

it seems there is no build for a Raspberry Pi 4B running 64bit ubuntu for example, is that correct or am i missing something?

- This version does not work [navi-v2.19.0-aarch64-linux-android.tar.gz](https://github.com/denisidoro/navi/releases/download/v2.19.0/navi-v2.19.0-aarch64-linux-android.tar.gz)
- This version [navi-v2.19.0-armv7-unknown-linux-musleabihf.tar.gz](https://github.com/denisidoro/navi/releases/download/v2.19.0/navi-v2.19.0-armv7-unknown-linux-musleabihf.tar.gz) works but if i understand correctly it is 32-bit?

Would be nice to add a 64 bit release? Or perhaps i'm misunderstanding something...
Please advise, thank you :-)

```
 ❯ uname -a
Linux pi 5.4.0-1059-raspi #67-Ubuntu SMP PREEMPT Mon Apr 11 14:16:01 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
 ❯ dpkg --print-architecture
arm64
 ❯ cat /proc/device-tree/model
Raspberry Pi 4 Model B Rev 1.2
```

**Comment by denisidoro** [comment]
I suppose I forgot to make Github Actions release a binary for Linux ARM64.

I'll try to release 2.20.0 in a week or so and it should include the build you want.
