### ISSUE TITLE
Add keywords to snippets

### ISSUE THREAD

**Issue by amacfie** [denisidoro/navi#742]
It would be nice to be able to include a list of keywords for a snippet. These keywords wouldn't be shown in the UI, but they would be used for search. I.e. if the user's search query matches the keywords, the snippet will show up in the search. This way the user doesn't have to use the exact words in the description. 

This is how cmdmenu works: https://github.com/amacfie/cmdmenu_tasks/blob/19c24e7d403107ae825e8d5ad744be48e50d5feb/ubuntu_general.json#L14

**Comment by denisidoro** [comment]
Navi uses fzf under the hood and fzf can only search for visible content

**Comment by denisidoro** [comment]
Closing as there's no easy fix in the foreseeable future :/
