### ISSUE TITLE
Feature Request: Customize the action when selecting a cheat

### ISSUE THREAD

**Issue by davidgoldcode** [denisidoro/navi#746]
**Is your feature request related to a problem? Please describe.**
When choosing a cheatsheet, I'd like to be able to change the action that occurs. For instance, rather than executing the command, I would prefer to use `pbcopy` to copy the code. This would allow me to edit before running the command & pasting will assure the code is in my history file

**Describe the solution you'd like**
An area in the configuration file to override default cheat behavior

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by denisidoro** [comment]
You can use `--print` and write a wrapper.

```
function mynavi() {
    navi --print "$@" | pbcopy
}
```

In the particular case of `pbcopy`, [you can use ctrl-y](https://github.com/denisidoro/navi/blob/0f95a29dfd595fd43d19f1269618fd03bab50f8f/src/actor.rs#L225) instead of enter.
