### ISSUE TITLE
Overriding NAVI_FZF_OVERRIDES_VAR --header doesn't work with spaces

### ISSUE THREAD

**Issue by bagohart** [denisidoro/navi#752]
**Describe the bug**
I'm trying to override the --header function of fzf for the variable selection so I can print help text about distinguishing selecting the query or the selection like so (in fish shell):
```
$ begin; set -lx NAVI_FZF_OVERRIDES_VAR '--header "Press Enter or Tab to choose selection or query."'; navi --print; end
```
I get 'unknown option: Enter' and choosing the variable is skipped. It seems to me that parsing the spaces fails? Maybe this is related to #695 ? I also tried it with various escaping (escaping the spaces, using different quotes " and ', escaping the quotes \" and \') but couldn't get it to work. Setting it in the config.yaml failed, too.
fzf does support spaces in its header, so this works:
```
fzf --header "Press Enter"
```

**To Reproduce**
1. Use fish shell.
2. Use the example cheatsheet:
```
% git, code

# Change branch
git checkout <branch>

$ branch: git branch | awk '{print $NF}'
```
in a git repo with at least 2 branches.

3. This works:
```
begin; set -lx NAVI_FZF_OVERRIDES_VAR '--header "Press_Enter_Or_Tab"'; navi --print; end
```
but this doesn't:
```
begin; set -lx NAVI_FZF_OVERRIDES_VAR '--header "Press Enter Or Tab"'; navi --print; end
```
4. Selection of the variable is skipped, and the output is
```
unknown option: Enter
git checkout
```

**Expected behavior**
The variable selection should work, and the header should be correctly displayed as "Press Enter Or Tab".

**Versions:**
 - OS: kubuntu 22.04 LTS
 - fish, version 3.5.0
 - navi 2.20.1 (downloaded latest navi binary)

**Comment by denisidoro** [comment]
The problem is in https://github.com/denisidoro/navi/blob/8725654a746fa8c999fbd5437559fdfcf1f7fb53/src/finder/mod.rs#L154

Instead of splitting by spaces, navi should honor bash's conventions for "word" splitting.

It should be trivial to fix it by calling the shellwords library, which already is a dependency.
