### ISSUE TITLE
unset EDITOR env var crashes navi snippets for "Edit local cheatsheets / config file"

### ISSUE THREAD

**Issue by PikaBlue107** [denisidoro/navi#759]
**Describe the bug**
When the `EDITOR` environment variable is not set, the "Edit main local cheatsheets" and "Edit config file" snippets crash when running `$EDITOR "$f"`.

The full "Edit main local cheatsheets" snippet is:

```sh
f="$(navi info cheats-path)/main.cheat"
[ -f "$f" ] || navi info cheats-example > "$f"
$EDITOR "$f"
```

When I run this snippet, I get the following error:

    bash: line 2: /Users/mgriesen/Library/Application Support/navi/cheats/main.cheat: Permission denied

This is because `$EDITOR` is not set, meaning it tries to run `main.cheat` as an executable, which it lacks permissions for.

**To Reproduce**
1. Run `unset EDITOR`
2. Run the "Edit main local cheatsheets" Navi snippet
    - this command will do so:
      ```sh
      navi --query "Edit main local cheatsheets" --best-match fn welcome
      ```
    - or run `navi fn welcome` and select this cheatsheet
3. Observe above "Permission denied" error

**Expected behavior**
In these two "Edit" snippets, Navi should identify that the `EDITOR` env variable is unset, and either:
1. warn the user and pick a sensible default (e.g. `nano`, `vim`, `emacs`)
2. crash the snippet and request the user export their choice of `EDITOR`

**Screenshots**
Demonstration:
<img width="734" alt="Screen Shot 2022-07-21 at 11 14 06 AM" src="https://user-images.githubusercontent.com/6174468/180256282-904c7a62-acb3-4c28-8ec4-6cc2f5d1e490.png">

**Versions:**
 - Navi: `navi 2.20.1`
 - OS: macOS Monterey v12.4 (MacBook Pro 16-inch 2021. Chip: Apple M1 Pro)
 - Shell Version (`sh --version`):

        GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
        Copyright (C) 2007 Free Software Foundation, Inc.

 - Shell Version (the one I normally use, `zsh --version`):

        zsh 5.8.1 (x86_64-apple-darwin21.0)

**Additional context**
Going forward I'm just going to set my `$EDITOR` var, but I thought it'd be nice to be aware of this.

Here's a suggestion for Expected Behavior#1 (my preferred, but not sure how portable it is):

```sh
f="$(navi info cheats-path)/main.cheat"
[ -f "$f" ] || navi info cheats-example > "$f"

# if $EDITOR is unset, warn the user and pick a default editor
 if [ -z "$EDITOR" ]; then
  echo "(navi) WARNING: Your \$EDITOR environment variable is unset. Using default: /usr/bin/nano"
  EDITOR=/usr/bin/nano
fi

$EDITOR "$f"
```

**Comment by denisidoro** [comment]
Nice catch! I guess I'll make navi fallback to nano, then (in general vim users can use nano but the other way around is uncommon)

**Comment by PikaBlue107** [comment]
Yep, as a vim user I fully agree with your logic there.

**Comment by PikaBlue107** [comment]
That's slick; I need to remember that shell feature for myself.
