### ISSUE TITLE
Ability to set multiple arguments

### ISSUE THREAD

**Issue by wallace11** [denisidoro/navi#77]
Take this snippet for example:
```
# Copy file/s from source to destination
cp <source> <dest>

$ source: ls
$ dest: ls
```

This simply breaks the whole operation of the script.

**Comment by denisidoro** [comment]
Related: https://github.com/denisidoro/navi/issues/65

This should be fixed in the latest version. 

Could you confirm if you're facing the same problem in the latest version, please?
