### ISSUE TITLE
echoin the command executed in full navi call

### ISSUE THREAD

**Issue by x0341** [denisidoro/navi#796]
**Is your feature request related to a problem? Please describe.**

The command executed should be echoed to the screen after calling the command in the navi (called directly in the bash prompt)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jackandroselv** [comment]
您好！您的邮件我已收到，我会尽快的查阅邮件。谢谢您的来信！

**Comment by denisidoro** [comment]
`navi --print` should do the trick
