### ISSUE TITLE
`--tldr` always shows 0/0 results

### ISSUE THREAD

**Issue by aserrallerios** [denisidoro/navi#798]
**Describe the bug**
See title. I receive no error from the tool. I don't know how to troubleshot it.

**To Reproduce**
```
navi --tldr docker
```

**Expected behavior**
Show some cheats.

**Versions:**

- OS: macOS
- Shell Version 3.2.57
- navi: 2.20.1
- fzf: 0.33.0

**Comment by denisidoro** [comment]
<img width="948" alt="shot 2023-04-08 at 20 57 38" src="https://user-images.githubusercontent.com/3226564/230747390-dbd36dfe-3301-4312-8e33-f62b26359e3d.png">

<img width="335" alt="shot 2023-04-08 at 20 57 47" src="https://user-images.githubusercontent.com/3226564/230747391-50e2ec3a-0fbd-4e9c-b3d5-3ecad64d8c32.png">

It's working on my machine, using the master branch.

I'll release a new version soon. Feel free to reopen if the error persists.
