### ISSUE TITLE
Please adapt to Chinese

### ISSUE THREAD

**Issue by 1trapcode** [denisidoro/navi#804]
When the cheat file contains Chinese, the navi interface will be misplaced when opened.

**Comment by denisidoro** [comment]
I believe this is fixed in master:

<img width="956" alt="shot 2023-04-08 at 19 42 55" src="https://user-images.githubusercontent.com/3226564/230745589-985eea92-7e0f-4606-aab0-9ca36883c927.png">

**Comment by denisidoro** [comment]
<img width="613" alt="shot 2023-04-08 at 20 03 19" src="https://user-images.githubusercontent.com/3226564/230746018-df2edc87-cc36-42d2-bb5f-c4ad8279ff71.png">

I'm not sure how to solve this. Apparently, a Chinese character is ~1.5x the size of a western character, so I don't see how padding will work in this case.
