### ISSUE TITLE
broken character

### ISSUE THREAD

**Issue by jens-hmmh** [denisidoro/navi#813]
**Describe the bug**
How to fix the broken characters, you can also see in the video in the README before each column?

**Screenshots**
![Bildschirmfoto vom 2023-03-18 03-09-28](https://user-images.githubusercontent.com/77965225/226077739-6fad2b84-6ca9-4875-8bf0-e21d0fd9fe17.png)

**Comment by denisidoro** [comment]
This character should be invisible and is used as a splitter for different fields.

Could you please check your terminal configs to understand why this character is appearing?

**Comment by jens-hmmh** [comment]
Thanks for pointing me in the right direction.

These character that were missing are braille characters. The fix was to install the symbola font.
Under fedora it is in the dnf package `gdouros-symbola-fonts`.

**Comment by jens-struct** [comment]
@Konfekt It will act as an fallback font, if your main terminal font does not support the braille characters. You don't need to set it explicitely, normally.

**Comment by Konfekt** [comment]
Do you know how this is set up ? I know that one can define fall back fonts for the specific font used in terminal in `~/.config/fontconfig/fonts.conf` but I wonder how the terminal learns automatically about the availability of this character in that font? 

To my surprise, the same user config that works in Debian 13 breaks in Ubuntu 22.04 (based on Debian 11?)
