### ISSUE TITLE
Unexpected argument '--print' found

### ISSUE THREAD

**Issue by strboul** [denisidoro/navi#832]
**Describe the bug**

`--print` flag doesn't work although it's the correct use according to the help page.

**To Reproduce**

```
navi --print
# error: unexpected argument '--print' found
# 
# Usage: navi [OPTIONS] [COMMAND]
# 
# For more information, try '--help'.
```

**Versions:**

- OS: `6.2.11-arch1-1`
- Shell Version: `zsh 5.9 (x86_64-pc-linux-gnu)`
- Navi version: `navi 2.22.1`

**Comment by denisidoro** [comment]
That's odd... It's working on my machine 🤔 

![shot 2023-04-20 at 16 26 19](https://user-images.githubusercontent.com/3226564/233467941-33b70c55-3a38-44c6-850e-eda297b3fdd3.png)

![shot 2023-04-20 at 16 26 12](https://user-images.githubusercontent.com/3226564/233467952-0b2ca479-4b7a-452e-a1e2-e85920c259c3.png)

**Comment by strboul** [comment]
That's odd to me. Could that somehow be related with the Arch updates? My problems started after I updated my packages https://github.com/archlinux/svntogit-community/commit/71abdd4d85da2c19c343e1b683c7d0527a7fcaef cc @orhun ?

**Comment by orhun** [comment]
Ah, I see the problem. The `PKGBUILD` that I adopted from `navi-git` was using `--all-features` flag which enabled `disable-command-execution` feature. I just removed that flag and pushed `2.22.1-2` to the Arch repos.

This should be fixed now 🐻

One question though, I'm just curious, what is the point of having `disable-*` features?

**Comment by strboul** [comment]
Version `2.22.1-2` works for me. Thanks @orhun :raised_hands:

**Comment by denisidoro** [comment]
> what is the point of having disable-* features?

https://github.com/denisidoro/navi/pull/678 has more info
