### ISSUE TITLE
ctrl-G include cheats in current folder

### ISSUE THREAD

**Issue by qsh-zh** [denisidoro/navi#848]
**Is your feature request related to a problem? Please describe.**

Thank you for developing such an incredible tool like navi. I utilize it on a daily basis.

However, I have noticed that navi does not currently support including cheats from the current folder. I believe this feature would be highly beneficial. For instance, I create cheatsheets for various projects, encompassing tasks such as building, testing, and deployment. Currently, I have to manually make note of them and copy-paste whenever needed. Yet, if navi could include cheatsheets from the current folder or a specific folder dedicated to project-related cheatsheets, it would greatly simplify research and task execution.

I notice I can use `--path` in the terminal. However, I do not know how to do it with the shell widget. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I am a zsh user.

**Comment by phanirithvij** [comment]
I am interested in this too, project level cheats. Would be very useful.

**Comment by denisidoro** [comment]
You can edit the code for the widget.

For example, instead of adding `source "$(navi shell widget bash)"` to your `.bashrc` file, you can:

1. run `navi shell widget bash > my_custom_navi_widget.bash`
2. edit the recently created file
3. add `source my_custom_navi_widget.sh` to your `.bashrc` file

As for 2, you're probably interested in replacing the line
```sh
local -r replacement="$(_navi_call --print --query "$last_command")"
```
into
```sh
local -r replacement="$(_navi_call --path YOUR_CUSTOM_PATH --print --query "$last_command")"
```

**Comment by phanirithvij** [comment]
Did it as

```
eval "$(navi widget bash | sed 's/--print/--print --path \"\$PWD\"/g')"
eval "$(navi widget zsh | sed 's/--print/--print --path \"\$PWD\"/g')"
navi widget fish | sed 's/--print/--print --path "$PWD"/g' | source
```

Need to figure out a way to bind another keybind for this, I got used to ctrl+g for global.
