### ISSUE TITLE
Non-Interactive Cheatsheet Install

### ISSUE THREAD

**Issue by jfmercer** [denisidoro/navi#863]
How do I do a non-interactive install of my cheatsheets? When I run `yes | navi repo add denisidoro/cheats`, I still get the interactive prompt. I have not succeeded in write an `expect` to automate this. 

Any ideas? I'm happy to contribute to `navi`'s documentation if there is a solution. 

Thanks.

**Comment by davidandreoletti** [comment]
@denisidoro (ping)

**Comment by davidandreoletti** [comment]
Workaround until a better solution comes along: 

```
f_navi_install_repo() {
    local url="$1"
    local name="$2"

    local cheatpath="$(navi info cheats-path)"
    local dir="$cheatpath/$name"

    git -C "$dir" pull || git clone "$url" "$dir"

}

#navi repo add denisidoro/navi-tldr-pages
f_navi_install_repo "https://github.com/denisidoro/navi-tldr-pages" "denisidoro__navi-tldr-pages"
```

then `navi` will display the cheats :-)

**Comment by denisidoro** [comment]
Yeah, the workaround is so simple that I'd rather not implement it in navi itself. I'll close this ticket as the workaround is good enough.

**Comment by denisidoro** [comment]
I guess Navi could skip the call to fzf in this case and optimistically assume the value which makes the most sense in this case.

I can't give an ETA for implementing it, though.

If someone submits a PR for it, I can review it and ensure it's going to be live in the next release.
