### ISSUE TITLE
Any way to have snippets on the left rather than on the right?

### ISSUE THREAD

**Issue by jbrilha** [denisidoro/navi#868]
I usually just use a quarter of my screen for each terminal window and with the default config most snippets aren't visible, so I was wondering if there's a way to move columns around?

I can change the width percentages and such of the tags and comments in the config to make the snippets more visible, but I'd still prefer having them on the left if possible, did I miss something in the documentation or is it just not doable?

Thanks!

**Comment by denisidoro** [comment]
That's not possible and implementing it isn't trivial: basically navi needs to build the input to fzf in the `col1;col2;col2` format. Then, it needs to [parse](https://github.com/denisidoro/navi/blob/9e20adeb4140dd11cd74f91e0b38e48438bbd1c9/src/deser/terminal.rs#L65-L68) this result into `col1` then `col2` then `col3`.

So everything is hardcoded and there's an explicit assumption of what the nth column means.

The cleanest way to implement this would be to fzf implement the _column moving_ functionality. This way navi wouldn't need to know about it: in this scenario, perhaps col1 was replaced with col2 but navi still sees the first column as col1.
