### ISSUE TITLE
Multiline commands

### ISSUE THREAD

**Issue by calexicoz** [denisidoro/navi#88]
Hi @denisidoro,

Any chance of supporting multiline commands, such as:

```
command abc xyz \
  --param1 foo \
  --param2 bar
```

Or some other method of running more complex commands (think involved things with pipes).

Thanks 🙏

**Comment by denisidoro** [comment]
Yeah, I think it's possible to add this feature. I'll try to work on some implementation today, maybe

**Comment by denisidoro** [comment]
I'm trying to implement this, but I can't figure out a way to make it work on OSX. Only on Linux 😞

**Comment by denisidoro** [comment]
`sed -E 's/\\\n//g` won't work on OSX

**Comment by denisidoro** [comment]
Fixed in the `dev` branch already.

While there's no another release, please run navi from the `dev` branch or run `brew install --HEAD denisidoro/tools/navi-nightly` to see the changes.

**Comment by calexicoz** [comment]
Awesome. Thanks!
