### ISSUE TITLE
Optional placeholder value for variable

### ISSUE THREAD

**Issue by xy-241** [denisidoro/navi#889]
**Is your feature request related to a problem? Please describe.**
I created my own .cheat file. However, I realized that when I give a placeholder value to a variable using $, I don't have an option to modify the placeholder value directly within the navi program. Instead, I can only modify it in the terminal after selecting the command, which becomes inconvenient for long commands.

**Describe the solution you'd like**
Maybe we can have shortcut to indicate we want to modify the placeholder value.

**Comment by jc-SpaceXp** [comment]
Doesn't `$ navi --fzf-overrides-var '--no-select-1'` provide this? 

This gif demonstrates the behaviour: https://asciinema.org/a/Su5eUYFHn7M5A6Yccvcv7WH7k/
With each <VAR> in your cheatsheet being $ VAR : echo 'placeholder'

**Comment by xy-241** [comment]
That is exactly what I was looking for, thanks 🙏🏼!
