### ISSUE TITLE
Print command before executing, add to history

### ISSUE THREAD

**Issue by calexicoz** [denisidoro/navi#89]
Hi @denisidoro,

Is it possible to get a flag to show the command before it gets executed. It would be even better if it could be added to shell history, so it can be quickly recalled.

Thoughts?

Thanks 🙏

**Comment by denisidoro** [comment]
Show the command before it gets executed: how would this be different from the preview window? I'm not sure I got your question right

Shell history: https://github.com/denisidoro/navi/issues/37

**Comment by denisidoro** [comment]
Ah I think I got your first question. You mean to print in the prompt before hitting enter? If so, that's precisely the issue #37

**Comment by calexicoz** [comment]
Thanks, I'll follow #37. Closing this as duplicate.

:+1:
