### ISSUE TITLE
Is this for Mac? Can't install on Ubuntu 18.04 x86_64 bit

### ISSUE THREAD

**Issue by adipginting** [denisidoro/navi#9]
After
`git clone http://github.com/denisidoro/navi /opt/navi`
`sudo git clone http://github.com/denisidoro/navi /opt/navi`
`cd /opt/navi`
Everything is normal.
But after
`sudo make install`
It outputs 
`scripts/install` and I can't invoke navi. 

The output after invoking navi is
`/opt/navi/src/ui.sh: line 4: fzf: command not found`
`grep: Invalid range end`

**Comment by aasutossh** [comment]
Installing fzf should fix it.

**Comment by city41** [comment]
@adipginting navi doesn't look to be compatible with gnu grep, making it not work on ubuntu. I found a temporary workaround, details in #11
